// 英语趣学 H5 · 种子词库（MVP 演示，由 tools/gen_words.py 生成）
// 字段: term 单词, phonetic 音标, level 级别, def 中文释义,
//       emoji 联想图, hook 记忆口诀(趣味钩子，与正确拼写视觉分离), example 例句
const WORD_BANK = [
  {"term": "apple", "phonetic": "/ˈæp.əl/", "level": "L1", "def": "苹果", "emoji": "🍎", "hook": "红红的、咬一口脆甜——🍎 就是苹果", "example": "I eat an apple every day."},
  {"term": "cat", "phonetic": "/kæt/", "level": "L1", "def": "猫", "emoji": "🐱", "hook": "喵星人，会撒娇的小动物", "example": "The cat is sleeping."},
  {"term": "dog", "phonetic": "/dɒɡ/", "level": "L1", "def": "狗", "emoji": "🐶", "hook": "人类最忠诚的朋友", "example": "A dog is a good friend."},
  {"term": "book", "phonetic": "/bʊk/", "level": "L1", "def": "书", "emoji": "📖", "hook": "知识的载体，翻开就有故事", "example": "I read a book at night."},
  {"term": "water", "phonetic": "/ˈwɔː.tər/", "level": "L1", "def": "水", "emoji": "💧", "hook": "生命之源，渴了喝它", "example": "Please drink more water."},
  {"term": "sun", "phonetic": "/sʌn/", "level": "L1", "def": "太阳", "emoji": "☀️", "hook": "白天发光发热的那颗恒星", "example": "The sun is bright."},
  {"term": "happy", "phonetic": "/ˈhæp.i/", "level": "L1", "def": "开心的", "emoji": "😊", "hook": "心里甜丝丝的开心", "example": "She is happy today."},
  {"term": "red", "phonetic": "/red/", "level": "L1", "def": "红色", "emoji": "🔴", "hook": "交通灯里“停”的颜色", "example": "I like the red apple."},
  {"term": "eat", "phonetic": "/iːt/", "level": "L1", "def": "吃", "emoji": "🍴", "hook": "把食物送进嘴里的动作", "example": "Let us eat lunch."},
  {"term": "go", "phonetic": "/ɡəʊ/", "level": "L1", "def": "去；走", "emoji": "🚶", "hook": "迈开腿往前走", "example": "We go to school."},
  {"term": "tree", "phonetic": "/triː/", "level": "L1", "def": "树", "emoji": "🌳", "hook": "大地上的绿色大伞", "example": "A bird is in the tree."},
  {"term": "fish", "phonetic": "/fɪʃ/", "level": "L1", "def": "鱼", "emoji": "🐟", "hook": "在水里游、不用肺呼吸的动物", "example": "The fish swims fast."},
  {"term": "bird", "phonetic": "/bɜːd/", "level": "L1", "def": "鸟", "emoji": "🐦", "hook": "长翅膀会飞的小动物", "example": "A bird is singing."},
  {"term": "egg", "phonetic": "/eɡ/", "level": "L1", "def": "蛋", "emoji": "🥚", "hook": "小鸡破壳前住的地方", "example": "I had an egg for breakfast."},
  {"term": "milk", "phonetic": "/mɪlk/", "level": "L1", "def": "牛奶", "emoji": "🥛", "hook": "奶牛给的白白营养饮品", "example": "Drink milk before bed."},
  {"term": "school", "phonetic": "/skuːl/", "level": "L1", "def": "学校", "emoji": "🏫", "hook": "每天去学知识的地方", "example": "We go to school by bus."},
  {"term": "friend", "phonetic": "/frend/", "level": "L1", "def": "朋友", "emoji": "🤝", "hook": "一起玩、互相帮的人", "example": "He is my best friend."},
  {"term": "house", "phonetic": "/haʊs/", "level": "L1", "def": "房子", "emoji": "🏠", "hook": "一家人住的小窝", "example": "Our house is near the park."},
  {"term": "car", "phonetic": "/kɑːr/", "level": "L1", "def": "汽车", "emoji": "🚗", "hook": "四个轮子带你去远方", "example": "The red car is fast."},
  {"term": "flower", "phonetic": "/ˈflaʊ.ər/", "level": "L1", "def": "花", "emoji": "🌸", "hook": "香香的、蜜蜂爱采它", "example": "She picked a flower."},
  {"term": "rain", "phonetic": "/reɪn/", "level": "L1", "def": "雨", "emoji": "🌧️", "hook": "天上掉下来的水珠", "example": "The rain stopped at noon."},
  {"term": "star", "phonetic": "/stɑːr/", "level": "L1", "def": "星星", "emoji": "⭐", "hook": "夜里天上眨眼的亮点", "example": "I wish upon a star."},
  {"term": "sleep", "phonetic": "/sliːp/", "level": "L1", "def": "睡觉", "emoji": "😴", "hook": "闭眼充电的休息时间", "example": "The baby is asleep."},
  {"term": "run", "phonetic": "/rʌn/", "level": "L1", "def": "跑", "emoji": "🏃", "hook": "比走快得多的移动", "example": "He can run very fast."},
  {"term": "ambulance", "phonetic": "/ˈæm.bjə.ləns/", "level": "L2", "def": "救护车", "emoji": "🚑", "hook": "发音联想“俺不能死”→ 救护车救人命（正确拼写 a-m-b-u-l-a-n-c-e）", "example": "Call an ambulance now!"},
  {"term": "bicycle", "phonetic": "/ˈbaɪ.sɪ.kl/", "level": "L2", "def": "自行车", "emoji": "🚲", "hook": "两个轮子(bi=双)的骑车工具", "example": "He rides a bicycle to work."},
  {"term": "forest", "phonetic": "/ˈfɒr.ɪst/", "level": "L2", "def": "森林", "emoji": "🌲", "hook": "很多树连成片的大森林", "example": "They walked into the forest."},
  {"term": "secret", "phonetic": "/ˈsiː.krət/", "level": "L2", "def": "秘密", "emoji": "🤫", "hook": "不能说的悄悄话", "example": "It is a secret between us."},
  {"term": "fragile", "phonetic": "/ˈfrædʒ.aɪl/", "level": "L2", "def": "易碎的", "emoji": "🥚", "hook": "像鸡蛋一样一碰就碎 → 易碎的", "example": "The box is fragile."},
  {"term": "brilliant", "phonetic": "/ˈbrɪl.jənt/", "level": "L2", "def": "聪明的；耀眼的", "emoji": "💡", "hook": "像灯泡突然亮了 → 聪明的/耀眼的", "example": "She is a brilliant student."},
  {"term": "enormous", "phonetic": "/ɪˈnɔː.məs/", "level": "L2", "def": "巨大的", "emoji": "🐘", "hook": "比大象还大 → 巨大的", "example": "An enormous whale appeared."},
  {"term": "patient", "phonetic": "/ˈpeɪ.ʃənt/", "level": "L2", "def": "病人；有耐心的", "emoji": "🧘", "hook": "生病时等你的是病人；能等的是有耐心的", "example": "Be patient, it takes time."},
  {"term": "environment", "phonetic": "/ɪnˈvaɪ.rən.mənt/", "level": "L2", "def": "环境", "emoji": "🌍", "hook": "我们周围的“环”境", "example": "We must protect the environment."},
  {"term": "consider", "phonetic": "/kənˈsɪd.ər/", "level": "L2", "def": "考虑", "emoji": "🤔", "hook": "把事放在心里反复想 → 考虑", "example": "Please consider my idea."},
  {"term": "whisper", "phonetic": "/ˈwɪs.pər/", "level": "L2", "def": "耳语；低声说", "emoji": "🤫", "hook": "凑近耳朵轻轻说 → 耳语", "example": "She whispered to me."},
  {"term": "mountain", "phonetic": "/ˈmaʊn.tən/", "level": "L2", "def": "山", "emoji": "⛰️", "hook": "高耸入云的大山", "example": "We climbed the mountain."},
  {"term": "library", "phonetic": "/ˈlaɪ.brər.i/", "level": "L2", "def": "图书馆", "emoji": "📚", "hook": "摆满书、安静看书的地方", "example": "I borrow books from the library."},
  {"term": "restaurant", "phonetic": "/ˈres.trɒnt/", "level": "L2", "def": "餐厅", "emoji": "🍽️", "hook": "点菜吃饭的地方", "example": "We met at a restaurant."},
  {"term": "umbrella", "phonetic": "/ʌmˈbrel.ə/", "level": "L2", "def": "雨伞", "emoji": "☂️", "hook": "下雨撑开挡雨的用具", "example": "Take an umbrella, it may rain."},
  {"term": "vegetable", "phonetic": "/ˈvedʒ.tə.bəl/", "level": "L2", "def": "蔬菜", "emoji": "🥦", "hook": "绿绿的、健康的食物", "example": "Eat more vegetables daily."},
  {"term": "window", "phonetic": "/ˈwɪn.dəʊ/", "level": "L2", "def": "窗户", "emoji": "🪟", "hook": "墙上透光能看外面的口", "example": "Open the window for fresh air."},
  {"term": "bridge", "phonetic": "/brɪdʒ/", "level": "L2", "def": "桥", "emoji": "🌉", "hook": "跨过河的通道", "example": "We crossed the bridge."},
  {"term": "telephone", "phonetic": "/ˈtel.ɪ.fəʊn/", "level": "L2", "def": "电话", "emoji": "📞", "hook": "用来远距离说话的工具", "example": "Call me on the telephone."},
  {"term": "birthday", "phonetic": "/ˈbɜːθ.deɪ/", "level": "L2", "def": "生日", "emoji": "🎂", "hook": "你来到这天的纪念日", "example": "Happy birthday to you!"},
  {"term": "weather", "phonetic": "/ˈweð.ər/", "level": "L2", "def": "天气", "emoji": "🌤️", "hook": "今天冷热处理况", "example": "The weather is nice today."},
  {"term": "language", "phonetic": "/ˈlæŋ.ɡwɪdʒ/", "level": "L2", "def": "语言", "emoji": "🗣️", "hook": "人和人沟通的密码", "example": "English is a useful language."},
  {"term": "travel", "phonetic": "/ˈtræv.əl/", "level": "L2", "def": "旅行", "emoji": "✈️", "hook": "去远方看世界的动作", "example": "We love to travel in summer."},
  {"term": "healthy", "phonetic": "/ˈhel.θi/", "level": "L2", "def": "健康的", "emoji": "💪", "hook": "身体棒、少生病 → 健康的", "example": "Eat well to stay healthy."},
  {"term": "ambition", "phonetic": "/æmˈbɪʃ.ən/", "level": "L3", "def": "野心；抱负", "emoji": "🚀", "hook": "心里有火想往上冲 → 野心/抱负", "example": "His ambition is to be a pilot."},
  {"term": "circumstance", "phonetic": "/ˈsɜː.kəm.stɑːns/", "level": "L3", "def": "环境；情况", "emoji": "🔄", "hook": "站在圆环(circle)里做事 → 周围的情况", "example": "Under the circumstance, we waited."},
  {"term": "dilemma", "phonetic": "/dɪˈlem.ə/", "level": "L3", "def": "困境；两难", "emoji": "😣", "hook": "两难(di=双)的困境", "example": "He faced a real dilemma."},
  {"term": "elaborate", "phonetic": "/ɪˈlæb.ər.ət/", "level": "L3", "def": "精心制作的；详尽的", "emoji": "🎨", "hook": "往外(e-)劳动(labor)打磨 → 精心制作的", "example": "She made an elaborate plan."},
  {"term": "phenomenon", "phonetic": "/fəˈnɒm.ɪ.nən/", "level": "L3", "def": "现象", "emoji": "🌈", "hook": "天上出现的奇景 → 现象", "example": "The rainbow is a natural phenomenon."},
  {"term": "spontaneous", "phonetic": "/spɒnˈteɪ.ni.əs/", "level": "L3", "def": "自发的", "emoji": "✨", "hook": "自己(spon)冒出来的 → 自发的", "example": "A spontaneous trip sounds fun."},
  {"term": "reluctant", "phonetic": "/rɪˈlʌk.tənt/", "level": "L3", "def": "不情愿的", "emoji": "🛑", "hook": "不肯往前 → 不情愿的", "example": "He was reluctant to leave."},
  {"term": "tedious", "phonetic": "/ˈtiː.di.əs/", "level": "L3", "def": "冗长乏味的", "emoji": "⏳", "hook": "时间长到让人烦 → 冗长乏味的", "example": "The meeting was tedious."},
  {"term": "vulnerable", "phonetic": "/ˈvʌl.nər.ə.bəl/", "level": "L3", "def": "脆弱的", "emoji": "🛡️", "hook": "盾牌挡不住 → 脆弱的", "example": "Children are vulnerable."},
  {"term": "alleviate", "phonetic": "/əˈliː.vi.eɪt/", "level": "L3", "def": "缓解；减轻", "emoji": "🪶", "hook": "把重量(lev)减轻 → 缓解", "example": "This medicine alleviates pain."},
  {"term": "magnificent", "phonetic": "/mæɡˈnɪf.ɪ.sənt/", "level": "L3", "def": "宏伟的；壮丽的", "emoji": "👑", "hook": "配得上加冕的 → 宏伟的/壮丽的", "example": "What a magnificent view!"},
  {"term": "subsequent", "phonetic": "/ˈsʌb.sɪ.kwənt/", "level": "L3", "def": "随后的", "emoji": "➡️", "hook": "跟在(sub-)后面的 → 随后的", "example": "Subsequent events proved him right."},
  {"term": "inevitable", "phonetic": "/ɪnˈev.ɪ.tə.bəl/", "level": "L3", "def": "不可避免的", "emoji": "⛓️", "hook": "躲不掉的 → 必然发生的", "example": "Mistakes are inevitable sometimes."},
  {"term": "comprehensive", "phonetic": "/ˌkɒm.prɪˈhen.sɪv/", "level": "L3", "def": "全面的；综合的", "emoji": "🧩", "hook": "全抓(com-)理解 → 全面的", "example": "We need a comprehensive plan."},
  {"term": "scrutinize", "phonetic": "/ˈskruː.tɪ.naɪz/", "level": "L3", "def": "仔细审查", "emoji": "🔍", "hook": "用放大镜看 → 细查", "example": "Scrutinize the contract carefully."},
  {"term": "resilient", "phonetic": "/rɪˈzɪl.i.ənt/", "level": "L3", "def": "有韧性的", "emoji": "🌱", "hook": "压弯还能弹回 → 坚韧的", "example": "She is resilient under pressure."},
  {"term": "profound", "phonetic": "/prəˈfaʊnd/", "level": "L3", "def": "深刻的", "emoji": "🌊", "hook": "像深海一样深 → 深刻的", "example": "A profound question worth thinking."},
  {"term": "diligent", "phonetic": "/ˈdɪl.ɪ.dʒənt/", "level": "L3", "def": "勤勉的", "emoji": "📖", "hook": "努力不偷懒 → 勤奋的", "example": "A diligent student studies daily."},
  {"term": "candidate", "phonetic": "/ˈkæn.dɪ.dət/", "level": "L3", "def": "候选人", "emoji": "🗳️", "hook": "等着被选的人 → 候选人", "example": "He is a candidate for the job."},
  {"term": "negotiate", "phonetic": "/nɪˈɡəʊ.ʃi.eɪt/", "level": "L3", "def": "谈判；协商", "emoji": "🤝", "hook": "双方来回谈条件 → 协商", "example": "They negotiate a better price."},
];
