// 英语趣学 H5 · 种子词库（MVP 演示，由 tools/gen_words.py 生成）
// 字段: term 单词, phonetic 音标, level 级别, def 中文释义,
//       emoji 联想图, hook 记忆口诀(趣味钩子，与正确拼写视觉分离), example 例句
const WORD_BANK = [
  {"term": "apple", "phonetic": "/ˈæp.əl/", "level": "L1", "def": "苹果", "emoji": "🍎", "hook": "红红的、咬一口脆甜——🍎 就是苹果", "example": "I eat an apple every day."},
  {"term": "cat", "phonetic": "/kæt/", "level": "L1", "def": "猫", "emoji": "🐱", "hook": "喵星人，会撒娇的小动物", "example": "The cat is sleeping."},
  {"term": "dog", "phonetic": "/dɒɡ/", "level": "L1", "def": "狗", "emoji": "🐶", "hook": "人类最忠诚的朋友", "example": "A dog is a good friend."},
  {"term": "book", "phonetic": "/bʊk/", "level": "L1", "def": "书", "emoji": "📖", "hook": "知识的载体，翻开就有故事", "example": "I read a book at night."},
  {"term": "water", "phonetic": "/ˈwɔː.tər/", "level": "L1", "def": "水", "emoji": "💧", "hook": "生命之源，渴了喝它", "example": "Please drink more water."},
  {"term": "sun", "phonetic": "/sʌn/", "level": "L1", "def": "太阳", "emoji": "☀️", "hook": "白天发光发热的那颗恒星", "example": "The sun is bright."},
  {"term": "happy", "phonetic": "/ˈhæp.i/", "level": "L1", "def": "开心的", "emoji": "😊", "hook": "心里甜丝丝的开心", "example": "She is happy today."},
  {"term": "red", "phonetic": "/red/", "level": "L1", "def": "红色", "emoji": "🔴", "hook": "交通灯里“停”的颜色", "example": "I like the red apple."},
  {"term": "eat", "phonetic": "/iːt/", "level": "L1", "def": "吃", "emoji": "🍴", "hook": "把食物送进嘴里的动作", "example": "Let us eat lunch."},
  {"term": "go", "phonetic": "/ɡəʊ/", "level": "L1", "def": "去；走", "emoji": "🚶", "hook": "迈开腿往前走", "example": "We go to school."},
  {"term": "tree", "phonetic": "/triː/", "level": "L1", "def": "树", "emoji": "🌳", "hook": "大地上的绿色大伞", "example": "A bird is in the tree."},
  {"term": "fish", "phonetic": "/fɪʃ/", "level": "L1", "def": "鱼", "emoji": "🐟", "hook": "在水里游、不用肺呼吸的动物", "example": "The fish swims fast."},
  {"term": "bird", "phonetic": "/bɜːd/", "level": "L1", "def": "鸟", "emoji": "🐦", "hook": "长翅膀会飞的小动物", "example": "A bird is singing."},
  {"term": "egg", "phonetic": "/eɡ/", "level": "L1", "def": "蛋", "emoji": "🥚", "hook": "小鸡破壳前住的地方", "example": "I had an egg for breakfast."},
  {"term": "milk", "phonetic": "/mɪlk/", "level": "L1", "def": "牛奶", "emoji": "🥛", "hook": "奶牛给的白白营养饮品", "example": "Drink milk before bed."},
  {"term": "school", "phonetic": "/skuːl/", "level": "L1", "def": "学校", "emoji": "🏫", "hook": "每天去学知识的地方", "example": "We go to school by bus."},
  {"term": "friend", "phonetic": "/frend/", "level": "L1", "def": "朋友", "emoji": "🤝", "hook": "一起玩、互相帮的人", "example": "He is my best friend."},
  {"term": "house", "phonetic": "/haʊs/", "level": "L1", "def": "房子", "emoji": "🏠", "hook": "一家人住的小窝", "example": "Our house is near the park."},
  {"term": "car", "phonetic": "/kɑːr/", "level": "L1", "def": "汽车", "emoji": "🚗", "hook": "四个轮子带你去远方", "example": "The red car is fast."},
  {"term": "flower", "phonetic": "/ˈflaʊ.ər/", "level": "L1", "def": "花", "emoji": "🌸", "hook": "香香的、蜜蜂爱采它", "example": "She picked a flower."},
  {"term": "rain", "phonetic": "/reɪn/", "level": "L1", "def": "雨", "emoji": "🌧️", "hook": "天上掉下来的水珠", "example": "The rain stopped at noon."},
  {"term": "star", "phonetic": "/stɑːr/", "level": "L1", "def": "星星", "emoji": "⭐", "hook": "夜里天上眨眼的亮点", "example": "I wish upon a star."},
  {"term": "sleep", "phonetic": "/sliːp/", "level": "L1", "def": "睡觉", "emoji": "😴", "hook": "闭眼充电的休息时间", "example": "The baby is asleep."},
  {"term": "run", "phonetic": "/rʌn/", "level": "L1", "def": "跑", "emoji": "🏃", "hook": "比走快得多的移动", "example": "He can run very fast."},
  {"term": "eye", "phonetic": "/aɪ/", "level": "L1", "def": "眼睛", "emoji": "👁️", "hook": "👁️ 眼睛 —— 多读多听，记住 eye", "example": "跟读：\"eye\" 意思是「眼睛」"},
  {"term": "hand", "phonetic": "/hænd/", "level": "L1", "def": "手", "emoji": "✋", "hook": "✋ 手 —— 多读多听，记住 hand", "example": "跟读：\"hand\" 意思是「手」"},
  {"term": "foot", "phonetic": "/fʊt/", "level": "L1", "def": "脚", "emoji": "🦶", "hook": "🦶 脚 —— 多读多听，记住 foot", "example": "跟读：\"foot\" 意思是「脚」"},
  {"term": "head", "phonetic": "/hed/", "level": "L1", "def": "头", "emoji": "🙆", "hook": "🙆 头 —— 多读多听，记住 head", "example": "跟读：\"head\" 意思是「头」"},
  {"term": "mouth", "phonetic": "/maʊθ/", "level": "L1", "def": "嘴", "emoji": "👄", "hook": "👄 嘴 —— 多读多听，记住 mouth", "example": "跟读：\"mouth\" 意思是「嘴」"},
  {"term": "nose", "phonetic": "/nəʊz/", "level": "L1", "def": "鼻子", "emoji": "👃", "hook": "👃 鼻子 —— 多读多听，记住 nose", "example": "跟读：\"nose\" 意思是「鼻子」"},
  {"term": "ear", "phonetic": "/ɪər/", "level": "L1", "def": "耳朵", "emoji": "👂", "hook": "👂 耳朵 —— 多读多听，记住 ear", "example": "跟读：\"ear\" 意思是「耳朵」"},
  {"term": "face", "phonetic": "/feɪs/", "level": "L1", "def": "脸", "emoji": "😊", "hook": "😊 脸 —— 多读多听，记住 face", "example": "跟读：\"face\" 意思是「脸」"},
  {"term": "hair", "phonetic": "/heər/", "level": "L1", "def": "头发", "emoji": "💇", "hook": "💇 头发 —— 多读多听，记住 hair", "example": "跟读：\"hair\" 意思是「头发」"},
  {"term": "mother", "phonetic": "/ˈmʌð.ər/", "level": "L1", "def": "妈妈", "emoji": "👩", "hook": "👩 妈妈 —— 多读多听，记住 mother", "example": "跟读：\"mother\" 意思是「妈妈」"},
  {"term": "father", "phonetic": "/ˈfɑː.ðər/", "level": "L1", "def": "爸爸", "emoji": "👨", "hook": "👨 爸爸 —— 多读多听，记住 father", "example": "跟读：\"father\" 意思是「爸爸」"},
  {"term": "brother", "phonetic": "/ˈbrʌð.ər/", "level": "L1", "def": "兄弟", "emoji": "👦", "hook": "👦 兄弟 —— 多读多听，记住 brother", "example": "跟读：\"brother\" 意思是「兄弟」"},
  {"term": "sister", "phonetic": "/ˈsɪs.tər/", "level": "L1", "def": "姐妹", "emoji": "👧", "hook": "👧 姐妹 —— 多读多听，记住 sister", "example": "跟读：\"sister\" 意思是「姐妹」"},
  {"term": "boy", "phonetic": "/bɔɪ/", "level": "L1", "def": "男孩", "emoji": "👦", "hook": "👦 男孩 —— 多读多听，记住 boy", "example": "跟读：\"boy\" 意思是「男孩」"},
  {"term": "girl", "phonetic": "/ɡɜːl/", "level": "L1", "def": "女孩", "emoji": "👧", "hook": "👧 女孩 —— 多读多听，记住 girl", "example": "跟读：\"girl\" 意思是「女孩」"},
  {"term": "teacher", "phonetic": "/ˈtiː.tʃər/", "level": "L1", "def": "老师", "emoji": "👩‍🏫", "hook": "👩‍🏫 老师 —— 多读多听，记住 teacher", "example": "跟读：\"teacher\" 意思是「老师」"},
  {"term": "student", "phonetic": "/ˈstjuː.dənt/", "level": "L1", "def": "学生", "emoji": "🧑‍🎓", "hook": "🧑‍🎓 学生 —— 多读多听，记住 student", "example": "跟读：\"student\" 意思是「学生」"},
  {"term": "bag", "phonetic": "/bæɡ/", "level": "L1", "def": "书包", "emoji": "🎒", "hook": "🎒 书包 —— 多读多听，记住 bag", "example": "跟读：\"bag\" 意思是「书包」"},
  {"term": "pen", "phonetic": "/pen/", "level": "L1", "def": "钢笔", "emoji": "🖊️", "hook": "🖊️ 钢笔 —— 多读多听，记住 pen", "example": "跟读：\"pen\" 意思是「钢笔」"},
  {"term": "tea", "phonetic": "/tiː/", "level": "L1", "def": "茶", "emoji": "🍵", "hook": "🍵 茶 —— 多读多听，记住 tea", "example": "跟读：\"tea\" 意思是「茶」"},
  {"term": "coffee", "phonetic": "/ˈkɒf.i/", "level": "L1", "def": "咖啡", "emoji": "☕", "hook": "☕ 咖啡 —— 多读多听，记住 coffee", "example": "跟读：\"coffee\" 意思是「咖啡」"},
  {"term": "sugar", "phonetic": "/ˈʃʊɡ.ər/", "level": "L1", "def": "糖", "emoji": "🍬", "hook": "🍬 糖 —— 多读多听，记住 sugar", "example": "跟读：\"sugar\" 意思是「糖」"},
  {"term": "salt", "phonetic": "/sɔːlt/", "level": "L1", "def": "盐", "emoji": "🧂", "hook": "🧂 盐 —— 多读多听，记住 salt", "example": "跟读：\"salt\" 意思是「盐」"},
  {"term": "ball", "phonetic": "/bɔːl/", "level": "L1", "def": "球", "emoji": "⚽", "hook": "⚽ 球 —— 多读多听，记住 ball", "example": "跟读：\"ball\" 意思是「球」"},
  {"term": "toy", "phonetic": "/tɔɪ/", "level": "L1", "def": "玩具", "emoji": "🧸", "hook": "🧸 玩具 —— 多读多听，记住 toy", "example": "跟读：\"toy\" 意思是「玩具」"},
  {"term": "blue", "phonetic": "/bluː/", "level": "L1", "def": "蓝色", "emoji": "🔵", "hook": "🔵 蓝色 —— 多读多听，记住 blue", "example": "跟读：\"blue\" 意思是「蓝色」"},
  {"term": "green", "phonetic": "/ɡriːn/", "level": "L1", "def": "绿色", "emoji": "🟢", "hook": "🟢 绿色 —— 多读多听，记住 green", "example": "跟读：\"green\" 意思是「绿色」"},
  {"term": "yellow", "phonetic": "/ˈjel.əʊ/", "level": "L1", "def": "黄色", "emoji": "🟡", "hook": "🟡 黄色 —— 多读多听，记住 yellow", "example": "跟读：\"yellow\" 意思是「黄色」"},
  {"term": "black", "phonetic": "/blæk/", "level": "L1", "def": "黑色", "emoji": "⚫", "hook": "⚫ 黑色 —— 多读多听，记住 black", "example": "跟读：\"black\" 意思是「黑色」"},
  {"term": "white", "phonetic": "/waɪt/", "level": "L1", "def": "白色", "emoji": "⚪", "hook": "⚪ 白色 —— 多读多听，记住 white", "example": "跟读：\"white\" 意思是「白色」"},
  {"term": "good", "phonetic": "/ɡʊd/", "level": "L1", "def": "好的", "emoji": "👍", "hook": "👍 好的 —— 多读多听，记住 good", "example": "跟读：\"good\" 意思是「好的」"},
  {"term": "bad", "phonetic": "/bæd/", "level": "L1", "def": "坏的", "emoji": "👎", "hook": "👎 坏的 —— 多读多听，记住 bad", "example": "跟读：\"bad\" 意思是「坏的」"},
  {"term": "today", "phonetic": "/təˈdeɪ/", "level": "L1", "def": "今天", "emoji": "📅", "hook": "📅 今天 —— 多读多听，记住 today", "example": "跟读：\"today\" 意思是「今天」"},
  {"term": "tomorrow", "phonetic": "/təˈmɒr.əʊ/", "level": "L1", "def": "明天", "emoji": "📆", "hook": "📆 明天 —— 多读多听，记住 tomorrow", "example": "跟读：\"tomorrow\" 意思是「明天」"},
  {"term": "hello", "phonetic": "/həˈləʊ/", "level": "L1", "def": "你好", "emoji": "👋", "hook": "👋 你好 —— 多读多听，记住 hello", "example": "跟读：\"hello\" 意思是「你好」"},
  {"term": "thanks", "phonetic": "/θæŋks/", "level": "L1", "def": "谢谢", "emoji": "🙏", "hook": "🙏 谢谢 —— 多读多听，记住 thanks", "example": "跟读：\"thanks\" 意思是「谢谢」"},
  {"term": "please", "phonetic": "/pliːz/", "level": "L1", "def": "请", "emoji": "🤲", "hook": "🤲 请 —— 多读多听，记住 please", "example": "跟读：\"please\" 意思是「请」"},
  {"term": "sorry", "phonetic": "/ˈsɒr.i/", "level": "L1", "def": "抱歉", "emoji": "😔", "hook": "😔 抱歉 —— 多读多听，记住 sorry", "example": "跟读：\"sorry\" 意思是「抱歉」"},
  {"term": "like", "phonetic": "/laɪk/", "level": "L1", "def": "喜欢", "emoji": "💗", "hook": "💗 喜欢 —— 多读多听，记住 like", "example": "跟读：\"like\" 意思是「喜欢」"},
  {"term": "want", "phonetic": "/wɒnt/", "level": "L1", "def": "想要", "emoji": "🤲", "hook": "🤲 想要 —— 多读多听，记住 want", "example": "跟读：\"want\" 意思是「想要」"},
  {"term": "see", "phonetic": "/siː/", "level": "L1", "def": "看见", "emoji": "👀", "hook": "👀 看见 —— 多读多听，记住 see", "example": "跟读：\"see\" 意思是「看见」"},
  {"term": "look", "phonetic": "/lʊk/", "level": "L1", "def": "看", "emoji": "👁️", "hook": "👁️ 看 —— 多读多听，记住 look", "example": "跟读：\"look\" 意思是「看」"},
  {"term": "hear", "phonetic": "/hɪər/", "level": "L1", "def": "听见", "emoji": "👂", "hook": "👂 听见 —— 多读多听，记住 hear", "example": "跟读：\"hear\" 意思是「听见」"},
  {"term": "sad", "phonetic": "/sæd/", "level": "L1", "def": "伤心的", "emoji": "😢", "hook": "😢 伤心的 —— 多读多听，记住 sad", "example": "跟读：\"sad\" 意思是「伤心的」"},
  {"term": "angry", "phonetic": "/ˈæŋ.ɡri/", "level": "L1", "def": "生气的", "emoji": "😠", "hook": "😠 生气的 —— 多读多听，记住 angry", "example": "跟读：\"angry\" 意思是「生气的」"},
  {"term": "tired", "phonetic": "/ˈtaɪ.əd/", "level": "L1", "def": "累的", "emoji": "😩", "hook": "😩 累的 —— 多读多听，记住 tired", "example": "跟读：\"tired\" 意思是「累的」"},
  {"term": "ambulance", "phonetic": "/ˈæm.bjə.ləns/", "level": "L2", "def": "救护车", "emoji": "🚑", "hook": "发音联想“俺不能死”→ 救护车救人命（正确拼写 a-m-b-u-l-a-n-c-e）", "example": "Call an ambulance now!"},
  {"term": "bicycle", "phonetic": "/ˈbaɪ.sɪ.kl/", "level": "L2", "def": "自行车", "emoji": "🚲", "hook": "两个轮子(bi=双)的骑车工具", "example": "He rides a bicycle to work."},
  {"term": "forest", "phonetic": "/ˈfɒr.ɪst/", "level": "L2", "def": "森林", "emoji": "🌲", "hook": "很多树连成片的大森林", "example": "They walked into the forest."},
  {"term": "secret", "phonetic": "/ˈsiː.krət/", "level": "L2", "def": "秘密", "emoji": "🤫", "hook": "不能说的悄悄话", "example": "It is a secret between us."},
  {"term": "fragile", "phonetic": "/ˈfrædʒ.aɪl/", "level": "L2", "def": "易碎的", "emoji": "🥚", "hook": "像鸡蛋一样一碰就碎 → 易碎的", "example": "The box is fragile."},
  {"term": "brilliant", "phonetic": "/ˈbrɪl.jənt/", "level": "L2", "def": "聪明的；耀眼的", "emoji": "💡", "hook": "像灯泡突然亮了 → 聪明的/耀眼的", "example": "She is a brilliant student."},
  {"term": "enormous", "phonetic": "/ɪˈnɔː.məs/", "level": "L2", "def": "巨大的", "emoji": "🐘", "hook": "比大象还大 → 巨大的", "example": "An enormous whale appeared."},
  {"term": "patient", "phonetic": "/ˈpeɪ.ʃənt/", "level": "L2", "def": "病人；有耐心的", "emoji": "🧘", "hook": "生病时等你的是病人；能等的是有耐心的", "example": "Be patient, it takes time."},
  {"term": "environment", "phonetic": "/ɪnˈvaɪ.rən.mənt/", "level": "L2", "def": "环境", "emoji": "🌍", "hook": "我们周围的“环”境", "example": "We must protect the environment."},
  {"term": "consider", "phonetic": "/kənˈsɪd.ər/", "level": "L2", "def": "考虑", "emoji": "🤔", "hook": "把事放在心里反复想 → 考虑", "example": "Please consider my idea."},
  {"term": "whisper", "phonetic": "/ˈwɪs.pər/", "level": "L2", "def": "耳语；低声说", "emoji": "🤫", "hook": "凑近耳朵轻轻说 → 耳语", "example": "She whispered to me."},
  {"term": "mountain", "phonetic": "/ˈmaʊn.tən/", "level": "L2", "def": "山", "emoji": "⛰️", "hook": "高耸入云的大山", "example": "We climbed the mountain."},
  {"term": "library", "phonetic": "/ˈlaɪ.brər.i/", "level": "L2", "def": "图书馆", "emoji": "📚", "hook": "摆满书、安静看书的地方", "example": "I borrow books from the library."},
  {"term": "restaurant", "phonetic": "/ˈres.trɒnt/", "level": "L2", "def": "餐厅", "emoji": "🍽️", "hook": "点菜吃饭的地方", "example": "We met at a restaurant."},
  {"term": "umbrella", "phonetic": "/ʌmˈbrel.ə/", "level": "L2", "def": "雨伞", "emoji": "☂️", "hook": "下雨撑开挡雨的用具", "example": "Take an umbrella, it may rain."},
  {"term": "vegetable", "phonetic": "/ˈvedʒ.tə.bəl/", "level": "L2", "def": "蔬菜", "emoji": "🥦", "hook": "绿绿的、健康的食物", "example": "Eat more vegetables daily."},
  {"term": "window", "phonetic": "/ˈwɪn.dəʊ/", "level": "L2", "def": "窗户", "emoji": "🪟", "hook": "墙上透光能看外面的口", "example": "Open the window for fresh air."},
  {"term": "bridge", "phonetic": "/brɪdʒ/", "level": "L2", "def": "桥", "emoji": "🌉", "hook": "跨过河的通道", "example": "We crossed the bridge."},
  {"term": "telephone", "phonetic": "/ˈtel.ɪ.fəʊn/", "level": "L2", "def": "电话", "emoji": "📞", "hook": "用来远距离说话的工具", "example": "Call me on the telephone."},
  {"term": "birthday", "phonetic": "/ˈbɜːθ.deɪ/", "level": "L2", "def": "生日", "emoji": "🎂", "hook": "你来到这天的纪念日", "example": "Happy birthday to you!"},
  {"term": "weather", "phonetic": "/ˈweð.ər/", "level": "L2", "def": "天气", "emoji": "🌤️", "hook": "今天冷热处理况", "example": "The weather is nice today."},
  {"term": "language", "phonetic": "/ˈlæŋ.ɡwɪdʒ/", "level": "L2", "def": "语言", "emoji": "🗣️", "hook": "人和人沟通的密码", "example": "English is a useful language."},
  {"term": "travel", "phonetic": "/ˈtræv.əl/", "level": "L2", "def": "旅行", "emoji": "✈️", "hook": "去远方看世界的动作", "example": "We love to travel in summer."},
  {"term": "healthy", "phonetic": "/ˈhel.θi/", "level": "L2", "def": "健康的", "emoji": "💪", "hook": "身体棒、少生病 → 健康的", "example": "Eat well to stay healthy."},
  {"term": "hospital", "phonetic": "/ˈhɒs.pɪ.tl/", "level": "L2", "def": "医院", "emoji": "🏥", "hook": "🏥 医院 —— 多读多听，记住 hospital", "example": "跟读：\"hospital\" 意思是「医院」"},
  {"term": "nurse", "phonetic": "/nɜːs/", "level": "L2", "def": "护士", "emoji": "👩‍⚕️", "hook": "👩‍⚕️ 护士 —— 多读多听，记住 nurse", "example": "跟读：\"nurse\" 意思是「护士」"},
  {"term": "medicine", "phonetic": "/ˈmed.ɪ.sɪn/", "level": "L2", "def": "药", "emoji": "💊", "hook": "💊 药 —— 多读多听，记住 medicine", "example": "跟读：\"medicine\" 意思是「药」"},
  {"term": "sick", "phonetic": "/sɪk/", "level": "L2", "def": "生病的", "emoji": "🤒", "hook": "🤒 生病的 —— 多读多听，记住 sick", "example": "跟读：\"sick\" 意思是「生病的」"},
  {"term": "sky", "phonetic": "/skaɪ/", "level": "L2", "def": "天空", "emoji": "🌌", "hook": "🌌 天空 —— 多读多听，记住 sky", "example": "跟读：\"sky\" 意思是「天空」"},
  {"term": "ice", "phonetic": "/aɪs/", "level": "L2", "def": "冰", "emoji": "🧊", "hook": "🧊 冰 —— 多读多听，记住 ice", "example": "跟读：\"ice\" 意思是「冰」"},
  {"term": "horse", "phonetic": "/hɔːs/", "level": "L2", "def": "马", "emoji": "🐴", "hook": "🐴 马 —— 多读多听，记住 horse", "example": "跟读：\"horse\" 意思是「马」"},
  {"term": "cow", "phonetic": "/kaʊ/", "level": "L2", "def": "奶牛", "emoji": "🐄", "hook": "🐄 奶牛 —— 多读多听，记住 cow", "example": "跟读：\"cow\" 意思是「奶牛」"},
  {"term": "pig", "phonetic": "/pɪɡ/", "level": "L2", "def": "猪", "emoji": "🐷", "hook": "🐷 猪 —— 多读多听，记住 pig", "example": "跟读：\"pig\" 意思是「猪」"},
  {"term": "sheep", "phonetic": "/ʃiːp/", "level": "L2", "def": "羊", "emoji": "🐑", "hook": "🐑 羊 —— 多读多听，记住 sheep", "example": "跟读：\"sheep\" 意思是「羊」"},
  {"term": "rabbit", "phonetic": "/ˈræb.ɪt/", "level": "L2", "def": "兔子", "emoji": "🐰", "hook": "🐰 兔子 —— 多读多听，记住 rabbit", "example": "跟读：\"rabbit\" 意思是「兔子」"},
  {"term": "monkey", "phonetic": "/ˈmʌŋ.ki/", "level": "L2", "def": "猴子", "emoji": "🐵", "hook": "🐵 猴子 —— 多读多听，记住 monkey", "example": "跟读：\"monkey\" 意思是「猴子」"},
  {"term": "tiger", "phonetic": "/ˈtaɪ.ɡər/", "level": "L2", "def": "老虎", "emoji": "🐯", "hook": "🐯 老虎 —— 多读多听，记住 tiger", "example": "跟读：\"tiger\" 意思是「老虎」"},
  {"term": "lion", "phonetic": "/ˈlaɪ.ən/", "level": "L2", "def": "狮子", "emoji": "🦁", "hook": "🦁 狮子 —— 多读多听，记住 lion", "example": "跟读：\"lion\" 意思是「狮子」"},
  {"term": "bear", "phonetic": "/beər/", "level": "L2", "def": "熊", "emoji": "🐻", "hook": "🐻 熊 —— 多读多听，记住 bear", "example": "跟读：\"bear\" 意思是「熊」"},
  {"term": "snake", "phonetic": "/sneɪk/", "level": "L2", "def": "蛇", "emoji": "🐍", "hook": "🐍 蛇 —— 多读多听，记住 snake", "example": "跟读：\"snake\" 意思是「蛇」"},
  {"term": "mouse", "phonetic": "/maʊs/", "level": "L2", "def": "老鼠", "emoji": "🐭", "hook": "🐭 老鼠 —— 多读多听，记住 mouse", "example": "跟读：\"mouse\" 意思是「老鼠」"},
  {"term": "long", "phonetic": "/lɒŋ/", "level": "L2", "def": "长的", "emoji": "📏", "hook": "📏 长的 —— 多读多听，记住 long", "example": "跟读：\"long\" 意思是「长的」"},
  {"term": "short", "phonetic": "/ʃɔːt/", "level": "L2", "def": "短的", "emoji": "✂️", "hook": "✂️ 短的 —— 多读多听，记住 short", "example": "跟读：\"short\" 意思是「短的」"},
  {"term": "tall", "phonetic": "/tɔːl/", "level": "L2", "def": "高的", "emoji": "📏", "hook": "📏 高的 —— 多读多听，记住 tall", "example": "跟读：\"tall\" 意思是「高的」"},
  {"term": "early", "phonetic": "/ˈɜːli/", "level": "L2", "def": "早的", "emoji": "🌅", "hook": "🌅 早的 —— 多读多听，记住 early", "example": "跟读：\"early\" 意思是「早的」"},
  {"term": "late", "phonetic": "/leɪt/", "level": "L2", "def": "晚的", "emoji": "🌙", "hook": "🌙 晚的 —— 多读多听，记住 late", "example": "跟读：\"late\" 意思是「晚的」"},
  {"term": "young", "phonetic": "/jʌŋ/", "level": "L2", "def": "年轻的", "emoji": "🧒", "hook": "🧒 年轻的 —— 多读多听，记住 young", "example": "跟读：\"young\" 意思是「年轻的」"},
  {"term": "busy", "phonetic": "/ˈbɪz.i/", "level": "L2", "def": "忙碌的", "emoji": "🏃", "hook": "🏃 忙碌的 —— 多读多听，记住 busy", "example": "跟读：\"busy\" 意思是「忙碌的」"},
  {"term": "free", "phonetic": "/friː/", "level": "L2", "def": "空闲的", "emoji": "🆓", "hook": "🆓 空闲的 —— 多读多听，记住 free", "example": "跟读：\"free\" 意思是「空闲的」"},
  {"term": "buy", "phonetic": "/baɪ/", "level": "L2", "def": "买", "emoji": "🛒", "hook": "🛒 买 —— 多读多听，记住 buy", "example": "跟读：\"buy\" 意思是「买」"},
  {"term": "sell", "phonetic": "/sel/", "level": "L2", "def": "卖", "emoji": "💱", "hook": "💱 卖 —— 多读多听，记住 sell", "example": "跟读：\"sell\" 意思是「卖」"},
  {"term": "price", "phonetic": "/praɪs/", "level": "L2", "def": "价格", "emoji": "🏷️", "hook": "🏷️ 价格 —— 多读多听，记住 price", "example": "跟读：\"price\" 意思是「价格」"},
  {"term": "market", "phonetic": "/ˈmɑː.kɪt/", "level": "L2", "def": "市场", "emoji": "🛒", "hook": "🛒 市场 —— 多读多听，记住 market", "example": "跟读：\"market\" 意思是「市场」"},
  {"term": "shop", "phonetic": "/ʃɒp/", "level": "L2", "def": "商店", "emoji": "🏪", "hook": "🏪 商店 —— 多读多听，记住 shop", "example": "跟读：\"shop\" 意思是「商店」"},
  {"term": "bank", "phonetic": "/bæŋk/", "level": "L2", "def": "银行", "emoji": "🏦", "hook": "🏦 银行 —— 多读多听，记住 bank", "example": "跟读：\"bank\" 意思是「银行」"},
  {"term": "post", "phonetic": "/pəʊst/", "level": "L2", "def": "邮政", "emoji": "📮", "hook": "📮 邮政 —— 多读多听，记住 post", "example": "跟读：\"post\" 意思是「邮政」"},
  {"term": "gift", "phonetic": "/ɡɪft/", "level": "L2", "def": "礼物", "emoji": "🎁", "hook": "🎁 礼物 —— 多读多听，记住 gift", "example": "跟读：\"gift\" 意思是「礼物」"},
  {"term": "party", "phonetic": "/ˈpɑː.ti/", "level": "L2", "def": "聚会", "emoji": "🎉", "hook": "🎉 聚会 —— 多读多听，记住 party", "example": "跟读：\"party\" 意思是「聚会」"},
  {"term": "holiday", "phonetic": "/ˈhɒl.ə.deɪ/", "level": "L2", "def": "假期", "emoji": "🏖️", "hook": "🏖️ 假期 —— 多读多听，记住 holiday", "example": "跟读：\"holiday\" 意思是「假期」"},
  {"term": "trip", "phonetic": "/trɪp/", "level": "L2", "def": "旅行", "emoji": "🧳", "hook": "🧳 旅行 —— 多读多听，记住 trip", "example": "跟读：\"trip\" 意思是「旅行」"},
  {"term": "country", "phonetic": "/ˈkʌn.tri/", "level": "L2", "def": "国家", "emoji": "🏳️", "hook": "🏳️ 国家 —— 多读多听，记住 country", "example": "跟读：\"country\" 意思是「国家」"},
  {"term": "world", "phonetic": "/wɜːld/", "level": "L2", "def": "世界", "emoji": "🌐", "hook": "🌐 世界 —— 多读多听，记住 world", "example": "跟读：\"world\" 意思是「世界」"},
  {"term": "culture", "phonetic": "/ˈkʌl.tʃər/", "level": "L2", "def": "文化", "emoji": "🏛️", "hook": "🏛️ 文化 —— 多读多听，记住 culture", "example": "跟读：\"culture\" 意思是「文化」"},
  {"term": "history", "phonetic": "/ˈhɪs.tə.ri/", "level": "L2", "def": "历史", "emoji": "📜", "hook": "📜 历史 —— 多读多听，记住 history", "example": "跟读：\"history\" 意思是「历史」"},
  {"term": "future", "phonetic": "/ˈfjuː.tʃər/", "level": "L2", "def": "未来", "emoji": "🔮", "hook": "🔮 未来 —— 多读多听，记住 future", "example": "跟读：\"future\" 意思是「未来」"},
  {"term": "past", "phonetic": "/pɑːst/", "level": "L2", "def": "过去", "emoji": "⏳", "hook": "⏳ 过去 —— 多读多听，记住 past", "example": "跟读：\"past\" 意思是「过去」"},
  {"term": "airport", "phonetic": "/ˈeə.pɔːt/", "level": "L2", "def": "机场", "emoji": "✈️", "hook": "✈️ 机场 —— 多读多听，记住 airport", "example": "跟读：\"airport\" 意思是「机场」"},
  {"term": "station", "phonetic": "/ˈsteɪ.ʃən/", "level": "L2", "def": "车站", "emoji": "🚉", "hook": "🚉 车站 —— 多读多听，记住 station", "example": "跟读：\"station\" 意思是「车站」"},
  {"term": "ticket", "phonetic": "/ˈtɪk.ɪt/", "level": "L2", "def": "票", "emoji": "🎫", "hook": "🎫 票 —— 多读多听，记住 ticket", "example": "跟读：\"ticket\" 意思是「票」"},
  {"term": "ambition", "phonetic": "/æmˈbɪʃ.ən/", "level": "L3", "def": "野心；抱负", "emoji": "🚀", "hook": "心里有火想往上冲 → 野心/抱负", "example": "His ambition is to be a pilot."},
  {"term": "circumstance", "phonetic": "/ˈsɜː.kəm.stɑːns/", "level": "L3", "def": "环境；情况", "emoji": "🔄", "hook": "站在圆环(circle)里做事 → 周围的情况", "example": "Under the circumstance, we waited."},
  {"term": "dilemma", "phonetic": "/dɪˈlem.ə/", "level": "L3", "def": "困境；两难", "emoji": "😣", "hook": "两难(di=双)的困境", "example": "He faced a real dilemma."},
  {"term": "elaborate", "phonetic": "/ɪˈlæb.ər.ət/", "level": "L3", "def": "精心制作的；详尽的", "emoji": "🎨", "hook": "往外(e-)劳动(labor)打磨 → 精心制作的", "example": "She made an elaborate plan."},
  {"term": "phenomenon", "phonetic": "/fəˈnɒm.ɪ.nən/", "level": "L3", "def": "现象", "emoji": "🌈", "hook": "天上出现的奇景 → 现象", "example": "The rainbow is a natural phenomenon."},
  {"term": "spontaneous", "phonetic": "/spɒnˈteɪ.ni.əs/", "level": "L3", "def": "自发的", "emoji": "✨", "hook": "自己(spon)冒出来的 → 自发的", "example": "A spontaneous trip sounds fun."},
  {"term": "reluctant", "phonetic": "/rɪˈlʌk.tənt/", "level": "L3", "def": "不情愿的", "emoji": "🛑", "hook": "不肯往前 → 不情愿的", "example": "He was reluctant to leave."},
  {"term": "tedious", "phonetic": "/ˈtiː.di.əs/", "level": "L3", "def": "冗长乏味的", "emoji": "⏳", "hook": "时间长到让人烦 → 冗长乏味的", "example": "The meeting was tedious."},
  {"term": "vulnerable", "phonetic": "/ˈvʌl.nər.ə.bəl/", "level": "L3", "def": "脆弱的", "emoji": "🛡️", "hook": "盾牌挡不住 → 脆弱的", "example": "Children are vulnerable."},
  {"term": "alleviate", "phonetic": "/əˈliː.vi.eɪt/", "level": "L3", "def": "缓解；减轻", "emoji": "🪶", "hook": "把重量(lev)减轻 → 缓解", "example": "This medicine alleviates pain."},
  {"term": "magnificent", "phonetic": "/mæɡˈnɪf.ɪ.sənt/", "level": "L3", "def": "宏伟的；壮丽的", "emoji": "👑", "hook": "配得上加冕的 → 宏伟的/壮丽的", "example": "What a magnificent view!"},
  {"term": "subsequent", "phonetic": "/ˈsʌb.sɪ.kwənt/", "level": "L3", "def": "随后的", "emoji": "➡️", "hook": "跟在(sub-)后面的 → 随后的", "example": "Subsequent events proved him right."},
  {"term": "inevitable", "phonetic": "/ɪnˈev.ɪ.tə.bəl/", "level": "L3", "def": "不可避免的", "emoji": "⛓️", "hook": "躲不掉的 → 必然发生的", "example": "Mistakes are inevitable sometimes."},
  {"term": "comprehensive", "phonetic": "/ˌkɒm.prɪˈhen.sɪv/", "level": "L3", "def": "全面的；综合的", "emoji": "🧩", "hook": "全抓(com-)理解 → 全面的", "example": "We need a comprehensive plan."},
  {"term": "scrutinize", "phonetic": "/ˈskruː.tɪ.naɪz/", "level": "L3", "def": "仔细审查", "emoji": "🔍", "hook": "用放大镜看 → 细查", "example": "Scrutinize the contract carefully."},
  {"term": "resilient", "phonetic": "/rɪˈzɪl.i.ənt/", "level": "L3", "def": "有韧性的", "emoji": "🌱", "hook": "压弯还能弹回 → 坚韧的", "example": "She is resilient under pressure."},
  {"term": "profound", "phonetic": "/prəˈfaʊnd/", "level": "L3", "def": "深刻的", "emoji": "🌊", "hook": "像深海一样深 → 深刻的", "example": "A profound question worth thinking."},
  {"term": "diligent", "phonetic": "/ˈdɪl.ɪ.dʒənt/", "level": "L3", "def": "勤勉的", "emoji": "📖", "hook": "努力不偷懒 → 勤奋的", "example": "A diligent student studies daily."},
  {"term": "candidate", "phonetic": "/ˈkæn.dɪ.dət/", "level": "L3", "def": "候选人", "emoji": "🗳️", "hook": "等着被选的人 → 候选人", "example": "He is a candidate for the job."},
  {"term": "negotiate", "phonetic": "/nɪˈɡəʊ.ʃi.eɪt/", "level": "L3", "def": "谈判；协商", "emoji": "🤝", "hook": "双方来回谈条件 → 协商", "example": "They negotiate a better price."},
  {"term": "abandon", "phonetic": "/əˈbæn.dən/", "level": "L3", "def": "放弃", "emoji": "🚪", "hook": "a(离开)+band(绑)→ 解开束缚 → 放弃", "example": "跟读：\"abandon\" 意思是「放弃」"},
  {"term": "accumulate", "phonetic": "/əˈkjuː.mjə.leɪt/", "level": "L3", "def": "积累", "emoji": "📚", "hook": "积累(ac-)到一起 → 越攒越多", "example": "跟读：\"accumulate\" 意思是「积累」"},
  {"term": "adequate", "phonetic": "/ˈæd.ɪ.kwət/", "level": "L3", "def": "足够的", "emoji": "✅", "hook": "ad(去)+equ(相等)→ 刚好够 → 足够的", "example": "跟读：\"adequate\" 意思是「足够的」"},
  {"term": "anticipate", "phonetic": "/ænˈtɪs.ɪ.peɪt/", "level": "L3", "def": "预期", "emoji": "🔮", "hook": "提前(after)抓(cap)住 → 预期", "example": "跟读：\"anticipate\" 意思是「预期」"},
  {"term": "apparent", "phonetic": "/əˈpær.ənt/", "level": "L3", "def": "明显的", "emoji": "👀", "hook": "👀 明显的 —— 多读多听，记住 apparent", "example": "跟读：\"apparent\" 意思是「明显的」"},
  {"term": "approximate", "phonetic": "/əˈprɒk.sɪ.mət/", "level": "L3", "def": "近似的", "emoji": "📏", "hook": "📏 近似的 —— 多读多听，记住 approximate", "example": "跟读：\"approximate\" 意思是「近似的」"},
  {"term": "arbitrary", "phonetic": "/ˈɑː.bɪ.trər.i/", "level": "L3", "def": "武断的", "emoji": "🎲", "hook": "🎲 武断的 —— 多读多听，记住 arbitrary", "example": "跟读：\"arbitrary\" 意思是「武断的」"},
  {"term": "assess", "phonetic": "/əˈses/", "level": "L3", "def": "评估", "emoji": "⚖️", "hook": "坐下来细看 → 评估", "example": "跟读：\"assess\" 意思是「评估」"},
  {"term": "attribute", "phonetic": "/əˈtrɪb.juːt/", "level": "L3", "def": "归因于", "emoji": "🔗", "hook": "把原因(a-)归给(tribute) → 归因于", "example": "跟读：\"attribute\" 意思是「归因于」"},
  {"term": "authentic", "phonetic": "/ɔːˈθen.tɪk/", "level": "L3", "def": "真实的", "emoji": "✅", "hook": "✅ 真实的 —— 多读多听，记住 authentic", "example": "跟读：\"authentic\" 意思是「真实的」"},
  {"term": "bias", "phonetic": "/ˈbaɪ.əs/", "level": "L3", "def": "偏见", "emoji": "⚖️", "hook": "⚖️ 偏见 —— 多读多听，记住 bias", "example": "跟读：\"bias\" 意思是「偏见」"},
  {"term": "coherent", "phonetic": "/kəʊˈhɪə.rənt/", "level": "L3", "def": "连贯的", "emoji": "🔗", "hook": "🔗 连贯的 —— 多读多听，记住 coherent", "example": "跟读：\"coherent\" 意思是「连贯的」"},
  {"term": "comply", "phonetic": "/kəmˈplaɪ/", "level": "L3", "def": "遵守", "emoji": "📋", "hook": "com(一起)+ply(折)→ 折服照做 → 遵守", "example": "跟读：\"comply\" 意思是「遵守」"},
  {"term": "conceive", "phonetic": "/kənˈsiːv/", "level": "L3", "def": "构想", "emoji": "💡", "hook": "💡 构想 —— 多读多听，记住 conceive", "example": "跟读：\"conceive\" 意思是「构想」"},
  {"term": "consequence", "phonetic": "/ˈkɒn.sɪ.kwəns/", "level": "L3", "def": "后果", "emoji": "⛓️", "hook": "跟着(con-)结果(sequence)→ 后果", "example": "跟读：\"consequence\" 意思是「后果」"},
  {"term": "consolidate", "phonetic": "/kənˈsɒl.ɪ.deɪt/", "level": "L3", "def": "巩固", "emoji": "🧱", "hook": "一起(con-)变 solid → 巩固", "example": "跟读：\"consolidate\" 意思是「巩固」"},
  {"term": "contemporary", "phonetic": "/kənˈtem.pər.ər.i/", "level": "L3", "def": "当代的", "emoji": "🕰️", "hook": "🕰️ 当代的 —— 多读多听，记住 contemporary", "example": "跟读：\"contemporary\" 意思是「当代的」"},
  {"term": "contradict", "phonetic": "/ˌkɒn.trəˈdɪkt/", "level": "L3", "def": "矛盾", "emoji": "⚡", "hook": "contra(反)+dict(说)→ 反着说 → 矛盾", "example": "跟读：\"contradict\" 意思是「矛盾」"},
  {"term": "deliberate", "phonetic": "/dɪˈlɪb.ər.ət/", "level": "L3", "def": "故意的", "emoji": "🎯", "hook": "de(下)+liber(秤)→ 掂量后 → 故意的", "example": "跟读：\"deliberate\" 意思是「故意的」"},
  {"term": "diminish", "phonetic": "/dɪˈmɪn.ɪʃ/", "level": "L3", "def": "减少", "emoji": "📉", "hook": "一点点(min)变小 → 减少", "example": "跟读：\"diminish\" 意思是「减少」"},
  {"term": "distinct", "phonetic": "/dɪˈstɪŋkt/", "level": "L3", "def": "明显的", "emoji": "🔍", "hook": "🔍 明显的 —— 多读多听，记住 distinct", "example": "跟读：\"distinct\" 意思是「明显的」"},
  {"term": "elegant", "phonetic": "/ˈel.ɪ.ɡənt/", "level": "L3", "def": "优雅的", "emoji": "💃", "hook": "💃 优雅的 —— 多读多听，记住 elegant", "example": "跟读：\"elegant\" 意思是「优雅的」"},
  {"term": "emphasize", "phonetic": "/ˈem.fə.saɪz/", "level": "L3", "def": "强调", "emoji": "📣", "hook": "em(使)+phase(显)→ 使其显眼 → 强调", "example": "跟读：\"emphasize\" 意思是「强调」"},
  {"term": "enhance", "phonetic": "/ɪnˈhɑːns/", "level": "L3", "def": "提升", "emoji": "⬆️", "hook": "en(使)+hance(高)→ 抬高 → 提升", "example": "跟读：\"enhance\" 意思是「提升」"},
  {"term": "explicit", "phonetic": "/ɪkˈsplɪs.ɪt/", "level": "L3", "def": "明确的", "emoji": "🗣️", "hook": "🗣️ 明确的 —— 多读多听，记住 explicit", "example": "跟读：\"explicit\" 意思是「明确的」"},
  {"term": "feasible", "phonetic": "/ˈfiː.zə.bəl/", "level": "L3", "def": "可行的", "emoji": "✅", "hook": "✅ 可行的 —— 多读多听，记住 feasible", "example": "跟读：\"feasible\" 意思是「可行的」"},
  {"term": "fluctuate", "phonetic": "/ˈflʌk.tʃu.eɪt/", "level": "L3", "def": "波动", "emoji": "📈", "hook": "📈 波动 —— 多读多听，记住 fluctuate", "example": "跟读：\"fluctuate\" 意思是「波动」"},
  {"term": "formulate", "phonetic": "/ˈfɔː.mju.leɪt/", "level": "L3", "def": "制定", "emoji": "📝", "hook": "📝 制定 —— 多读多听，记住 formulate", "example": "跟读：\"formulate\" 意思是「制定」"},
  {"term": "fundamental", "phonetic": "/ˌfʌn.dəˈmen.təl/", "level": "L3", "def": "基本的", "emoji": "🏗️", "hook": "🏗️ 基本的 —— 多读多听，记住 fundamental", "example": "跟读：\"fundamental\" 意思是「基本的」"},
  {"term": "hypothesis", "phonetic": "/haɪˈpɒθ.ə.sɪs/", "level": "L3", "def": "假设", "emoji": "❓", "hook": "❓ 假设 —— 多读多听，记住 hypothesis", "example": "跟读：\"hypothesis\" 意思是「假设」"},
  {"term": "implement", "phonetic": "/ˈɪm.plɪ.ment/", "level": "L3", "def": "实施", "emoji": "🔧", "hook": "im(进)+ple(满)→ 落实填满 → 实施", "example": "跟读：\"implement\" 意思是「实施」"},
  {"term": "integrate", "phonetic": "/ˈɪn.tɪ.ɡreɪt/", "level": "L3", "def": "整合", "emoji": "🧩", "hook": "in(整)+teg(触)→ 触成一体 → 整合", "example": "跟读：\"integrate\" 意思是「整合」"},
  {"term": "legitimate", "phonetic": "/lɪˈdʒɪt.ɪ.mət/", "level": "L3", "def": "合法的", "emoji": "⚖️", "hook": "⚖️ 合法的 —— 多读多听，记住 legitimate", "example": "跟读：\"legitimate\" 意思是「合法的」"},
  {"term": "manipulate", "phonetic": "/məˈnɪp.jə.leɪt/", "level": "L3", "def": "操纵", "emoji": "🕹️", "hook": "🕹️ 操纵 —— 多读多听，记住 manipulate", "example": "跟读：\"manipulate\" 意思是「操纵」"},
  {"term": "negligible", "phonetic": "/ˈneɡ.lɪ.dʒə.bəl/", "level": "L3", "def": "可忽略的", "emoji": "🤏", "hook": "🤏 可忽略的 —— 多读多听，记住 negligible", "example": "跟读：\"negligible\" 意思是「可忽略的」"},
  {"term": "notion", "phonetic": "/ˈnəʊ.ʃən/", "level": "L3", "def": "概念", "emoji": "💭", "hook": "💭 概念 —— 多读多听，记住 notion", "example": "跟读：\"notion\" 意思是「概念」"},
  {"term": "objective", "phonetic": "/əbˈdʒek.tɪv/", "level": "L3", "def": "客观的", "emoji": "🎯", "hook": "obj(物)+ive→ 看物体而非主观 → 客观的", "example": "跟读：\"objective\" 意思是「客观的」"},
  {"term": "paradox", "phonetic": "/ˈpær.ə.dɒks/", "level": "L3", "def": "悖论", "emoji": "🌀", "hook": "🌀 悖论 —— 多读多听，记住 paradox", "example": "跟读：\"paradox\" 意思是「悖论」"},
  {"term": "persist", "phonetic": "/pəˈsɪst/", "level": "L3", "def": "坚持", "emoji": "💪", "hook": "per(始终)+sist(站)→ 一直站着 → 坚持", "example": "跟读：\"persist\" 意思是「坚持」"},
  {"term": "prevalent", "phonetic": "/ˈprev.əl.ənt/", "level": "L3", "def": "普遍的", "emoji": "🌐", "hook": "🌐 普遍的 —— 多读多听，记住 prevalent", "example": "跟读：\"prevalent\" 意思是「普遍的」"},
  {"term": "rational", "phonetic": "/ˈræʃ.ən.əl/", "level": "L3", "def": "理性的", "emoji": "🧠", "hook": "🧠 理性的 —— 多读多听，记住 rational", "example": "跟读：\"rational\" 意思是「理性的」"},
  {"term": "reinforce", "phonetic": "/ˌriː.ɪnˈfɔːs/", "level": "L3", "def": "加强", "emoji": "🛡️", "hook": "re(再)+in(入)+force→ 再加力 → 加强", "example": "跟读：\"reinforce\" 意思是「加强」"},
  {"term": "subtle", "phonetic": "/ˈsʌt.əl/", "level": "L3", "def": "微妙的", "emoji": "🔍", "hook": "🔍 微妙的 —— 多读多听，记住 subtle", "example": "跟读：\"subtle\" 意思是「微妙的」"},
  {"term": "tremendous", "phonetic": "/trəˈmen.dəs/", "level": "L3", "def": "巨大的", "emoji": "🌟", "hook": "trem(颤抖)→ 大得让人抖 → 巨大的", "example": "跟读：\"tremendous\" 意思是「巨大的」"},
  {"term": "unanimous", "phonetic": "/juˈnæn.ɪ.məs/", "level": "L3", "def": "一致的", "emoji": "🤝", "hook": "🤝 一致的 —— 多读多听，记住 unanimous", "example": "跟读：\"unanimous\" 意思是「一致的」"},
  {"term": "versatile", "phonetic": "/ˈvɜː.sə.taɪl/", "level": "L3", "def": "多才多艺的", "emoji": "🎨", "hook": "🎨 多才多艺的 —— 多读多听，记住 versatile", "example": "跟读：\"versatile\" 意思是「多才多艺的」"},
  {"term": "vivid", "phonetic": "/ˈvɪv.ɪd/", "level": "L3", "def": "生动的", "emoji": "🌈", "hook": "🌈 生动的 —— 多读多听，记住 vivid", "example": "跟读：\"vivid\" 意思是「生动的」"},
];
