// 英语趣学 H5 · 种子词库（MVP 演示，由 tools/gen_words.py 生成）
// 字段: term 单词, phonetic 音标, level 级别, def 中文释义,
//       emoji 联想图, hook 记忆口诀(趣味钩子，与正确拼写视觉分离), example 例句
const WORD_BANK = [
  {"term": "apple", "phonetic": "/ˈæp.əl/", "level": "L1", "def": "苹果", "emoji": "🍎", "hook": "红红的、咬一口脆甜——🍎 就是苹果", "example": "I eat an apple every day."},
  {"term": "cat", "phonetic": "/kæt/", "level": "L1", "def": "猫", "emoji": "🐱", "hook": "喵星人，会撒娇的小动物", "example": "The cat is sleeping."},
  {"term": "dog", "phonetic": "/dɒɡ/", "level": "L1", "def": "狗", "emoji": "🐶", "hook": "人类最忠诚的朋友", "example": "A dog is a good friend."},
  {"term": "book", "phonetic": "/bʊk/", "level": "L1", "def": "书", "emoji": "📖", "hook": "知识的载体，翻开就有故事", "example": "I read a book at night."},
  {"term": "water", "phonetic": "/ˈwɔː.tər/", "level": "L1", "def": "水", "emoji": "💧", "hook": "生命之源，渴了喝它", "example": "Please drink more water."},
  {"term": "sun", "phonetic": "/sʌn/", "level": "L1", "def": "太阳", "emoji": "☀️", "hook": "白天发光发热的那颗恒星", "example": "The sun is bright."},
  {"term": "happy", "phonetic": "/ˈhæp.i/", "level": "L1", "def": "开心的", "emoji": "😊", "hook": "心里甜丝丝的开心", "example": "She is happy today."},
  {"term": "red", "phonetic": "/red/", "level": "L1", "def": "红色", "emoji": "🔴", "hook": "交通灯里“停”的颜色", "example": "I like the red apple."},
  {"term": "eat", "phonetic": "/iːt/", "level": "L1", "def": "吃", "emoji": "🍴", "hook": "把食物送进嘴里的动作", "example": "Let us eat lunch."},
  {"term": "go", "phonetic": "/ɡəʊ/", "level": "L1", "def": "去；走", "emoji": "🚶", "hook": "迈开腿往前走", "example": "We go to school."},
  {"term": "tree", "phonetic": "/triː/", "level": "L1", "def": "树", "emoji": "🌳", "hook": "大地上的绿色大伞", "example": "A bird is in the tree."},
  {"term": "fish", "phonetic": "/fɪʃ/", "level": "L1", "def": "鱼", "emoji": "🐟", "hook": "在水里游、不用肺呼吸的动物", "example": "The fish swims fast."},
  {"term": "bird", "phonetic": "/bɜːd/", "level": "L1", "def": "鸟", "emoji": "🐦", "hook": "长翅膀会飞的小动物", "example": "A bird is singing."},
  {"term": "egg", "phonetic": "/eɡ/", "level": "L1", "def": "蛋", "emoji": "🥚", "hook": "小鸡破壳前住的地方", "example": "I had an egg for breakfast."},
  {"term": "milk", "phonetic": "/mɪlk/", "level": "L1", "def": "牛奶", "emoji": "🥛", "hook": "奶牛给的白白营养饮品", "example": "Drink milk before bed."},
  {"term": "school", "phonetic": "/skuːl/", "level": "L1", "def": "学校", "emoji": "🏫", "hook": "每天去学知识的地方", "example": "We go to school by bus."},
  {"term": "friend", "phonetic": "/frend/", "level": "L1", "def": "朋友", "emoji": "🤝", "hook": "一起玩、互相帮的人", "example": "He is my best friend."},
  {"term": "house", "phonetic": "/haʊs/", "level": "L1", "def": "房子", "emoji": "🏠", "hook": "一家人住的小窝", "example": "Our house is near the park."},
  {"term": "car", "phonetic": "/kɑːr/", "level": "L1", "def": "汽车", "emoji": "🚗", "hook": "四个轮子带你去远方", "example": "The red car is fast."},
  {"term": "flower", "phonetic": "/ˈflaʊ.ər/", "level": "L1", "def": "花", "emoji": "🌸", "hook": "香香的、蜜蜂爱采它", "example": "She picked a flower."},
  {"term": "rain", "phonetic": "/reɪn/", "level": "L1", "def": "雨", "emoji": "🌧️", "hook": "天上掉下来的水珠", "example": "The rain stopped at noon."},
  {"term": "star", "phonetic": "/stɑːr/", "level": "L1", "def": "星星", "emoji": "⭐", "hook": "夜里天上眨眼的亮点", "example": "I wish upon a star."},
  {"term": "sleep", "phonetic": "/sliːp/", "level": "L1", "def": "睡觉", "emoji": "😴", "hook": "闭眼充电的休息时间", "example": "The baby is asleep."},
  {"term": "run", "phonetic": "/rʌn/", "level": "L1", "def": "跑", "emoji": "🏃", "hook": "比走快得多的移动", "example": "He can run very fast."},
  {"term": "eye", "phonetic": "/aɪ/", "level": "L1", "def": "眼睛", "emoji": "👁️", "hook": "👁️ 眼睛 —— 多读多听，记住 eye", "example": "跟读：\"eye\" 意思是「眼睛」"},
  {"term": "hand", "phonetic": "/hænd/", "level": "L1", "def": "手", "emoji": "✋", "hook": "✋ 手 —— 多读多听，记住 hand", "example": "跟读：\"hand\" 意思是「手」"},
  {"term": "foot", "phonetic": "/fʊt/", "level": "L1", "def": "脚", "emoji": "🦶", "hook": "🦶 脚 —— 多读多听，记住 foot", "example": "跟读：\"foot\" 意思是「脚」"},
  {"term": "head", "phonetic": "/hed/", "level": "L1", "def": "头", "emoji": "🙆", "hook": "🙆 头 —— 多读多听，记住 head", "example": "跟读：\"head\" 意思是「头」"},
  {"term": "mouth", "phonetic": "/maʊθ/", "level": "L1", "def": "嘴", "emoji": "👄", "hook": "👄 嘴 —— 多读多听，记住 mouth", "example": "跟读：\"mouth\" 意思是「嘴」"},
  {"term": "nose", "phonetic": "/nəʊz/", "level": "L1", "def": "鼻子", "emoji": "👃", "hook": "👃 鼻子 —— 多读多听，记住 nose", "example": "跟读：\"nose\" 意思是「鼻子」"},
  {"term": "ear", "phonetic": "/ɪər/", "level": "L1", "def": "耳朵", "emoji": "👂", "hook": "👂 耳朵 —— 多读多听，记住 ear", "example": "跟读：\"ear\" 意思是「耳朵」"},
  {"term": "face", "phonetic": "/feɪs/", "level": "L1", "def": "脸", "emoji": "😊", "hook": "😊 脸 —— 多读多听，记住 face", "example": "跟读：\"face\" 意思是「脸」"},
  {"term": "hair", "phonetic": "/heər/", "level": "L1", "def": "头发", "emoji": "💇", "hook": "💇 头发 —— 多读多听，记住 hair", "example": "跟读：\"hair\" 意思是「头发」"},
  {"term": "mother", "phonetic": "/ˈmʌð.ər/", "level": "L1", "def": "妈妈", "emoji": "👩", "hook": "👩 妈妈 —— 多读多听，记住 mother", "example": "跟读：\"mother\" 意思是「妈妈」"},
  {"term": "father", "phonetic": "/ˈfɑː.ðər/", "level": "L1", "def": "爸爸", "emoji": "👨", "hook": "👨 爸爸 —— 多读多听，记住 father", "example": "跟读：\"father\" 意思是「爸爸」"},
  {"term": "brother", "phonetic": "/ˈbrʌð.ər/", "level": "L1", "def": "兄弟", "emoji": "👦", "hook": "👦 兄弟 —— 多读多听，记住 brother", "example": "跟读：\"brother\" 意思是「兄弟」"},
  {"term": "sister", "phonetic": "/ˈsɪs.tər/", "level": "L1", "def": "姐妹", "emoji": "👧", "hook": "👧 姐妹 —— 多读多听，记住 sister", "example": "跟读：\"sister\" 意思是「姐妹」"},
  {"term": "boy", "phonetic": "/bɔɪ/", "level": "L1", "def": "男孩", "emoji": "👦", "hook": "👦 男孩 —— 多读多听，记住 boy", "example": "跟读：\"boy\" 意思是「男孩」"},
  {"term": "girl", "phonetic": "/ɡɜːl/", "level": "L1", "def": "女孩", "emoji": "👧", "hook": "👧 女孩 —— 多读多听，记住 girl", "example": "跟读：\"girl\" 意思是「女孩」"},
  {"term": "teacher", "phonetic": "/ˈtiː.tʃər/", "level": "L1", "def": "老师", "emoji": "👩‍🏫", "hook": "👩‍🏫 老师 —— 多读多听，记住 teacher", "example": "跟读：\"teacher\" 意思是「老师」"},
  {"term": "student", "phonetic": "/ˈstjuː.dənt/", "level": "L1", "def": "学生", "emoji": "🧑‍🎓", "hook": "🧑‍🎓 学生 —— 多读多听，记住 student", "example": "跟读：\"student\" 意思是「学生」"},
  {"term": "bag", "phonetic": "/bæɡ/", "level": "L1", "def": "书包", "emoji": "🎒", "hook": "🎒 书包 —— 多读多听，记住 bag", "example": "跟读：\"bag\" 意思是「书包」"},
  {"term": "pen", "phonetic": "/pen/", "level": "L1", "def": "钢笔", "emoji": "🖊️", "hook": "🖊️ 钢笔 —— 多读多听，记住 pen", "example": "跟读：\"pen\" 意思是「钢笔」"},
  {"term": "tea", "phonetic": "/tiː/", "level": "L1", "def": "茶", "emoji": "🍵", "hook": "🍵 茶 —— 多读多听，记住 tea", "example": "跟读：\"tea\" 意思是「茶」"},
  {"term": "coffee", "phonetic": "/ˈkɒf.i/", "level": "L1", "def": "咖啡", "emoji": "☕", "hook": "☕ 咖啡 —— 多读多听，记住 coffee", "example": "跟读：\"coffee\" 意思是「咖啡」"},
  {"term": "sugar", "phonetic": "/ˈʃʊɡ.ər/", "level": "L1", "def": "糖", "emoji": "🍬", "hook": "🍬 糖 —— 多读多听，记住 sugar", "example": "跟读：\"sugar\" 意思是「糖」"},
  {"term": "salt", "phonetic": "/sɔːlt/", "level": "L1", "def": "盐", "emoji": "🧂", "hook": "🧂 盐 —— 多读多听，记住 salt", "example": "跟读：\"salt\" 意思是「盐」"},
  {"term": "ball", "phonetic": "/bɔːl/", "level": "L1", "def": "球", "emoji": "⚽", "hook": "⚽ 球 —— 多读多听，记住 ball", "example": "跟读：\"ball\" 意思是「球」"},
  {"term": "toy", "phonetic": "/tɔɪ/", "level": "L1", "def": "玩具", "emoji": "🧸", "hook": "🧸 玩具 —— 多读多听，记住 toy", "example": "跟读：\"toy\" 意思是「玩具」"},
  {"term": "blue", "phonetic": "/bluː/", "level": "L1", "def": "蓝色", "emoji": "🔵", "hook": "🔵 蓝色 —— 多读多听，记住 blue", "example": "跟读：\"blue\" 意思是「蓝色」"},
  {"term": "green", "phonetic": "/ɡriːn/", "level": "L1", "def": "绿色", "emoji": "🟢", "hook": "🟢 绿色 —— 多读多听，记住 green", "example": "跟读：\"green\" 意思是「绿色」"},
  {"term": "yellow", "phonetic": "/ˈjel.əʊ/", "level": "L1", "def": "黄色", "emoji": "🟡", "hook": "🟡 黄色 —— 多读多听，记住 yellow", "example": "跟读：\"yellow\" 意思是「黄色」"},
  {"term": "black", "phonetic": "/blæk/", "level": "L1", "def": "黑色", "emoji": "⚫", "hook": "⚫ 黑色 —— 多读多听，记住 black", "example": "跟读：\"black\" 意思是「黑色」"},
  {"term": "white", "phonetic": "/waɪt/", "level": "L1", "def": "白色", "emoji": "⚪", "hook": "⚪ 白色 —— 多读多听，记住 white", "example": "跟读：\"white\" 意思是「白色」"},
  {"term": "good", "phonetic": "/ɡʊd/", "level": "L1", "def": "好的", "emoji": "👍", "hook": "👍 好的 —— 多读多听，记住 good", "example": "跟读：\"good\" 意思是「好的」"},
  {"term": "bad", "phonetic": "/bæd/", "level": "L1", "def": "坏的", "emoji": "👎", "hook": "👎 坏的 —— 多读多听，记住 bad", "example": "跟读：\"bad\" 意思是「坏的」"},
  {"term": "today", "phonetic": "/təˈdeɪ/", "level": "L1", "def": "今天", "emoji": "📅", "hook": "📅 今天 —— 多读多听，记住 today", "example": "跟读：\"today\" 意思是「今天」"},
  {"term": "tomorrow", "phonetic": "/təˈmɒr.əʊ/", "level": "L1", "def": "明天", "emoji": "📆", "hook": "📆 明天 —— 多读多听，记住 tomorrow", "example": "跟读：\"tomorrow\" 意思是「明天」"},
  {"term": "hello", "phonetic": "/həˈləʊ/", "level": "L1", "def": "你好", "emoji": "👋", "hook": "👋 你好 —— 多读多听，记住 hello", "example": "跟读：\"hello\" 意思是「你好」"},
  {"term": "thanks", "phonetic": "/θæŋks/", "level": "L1", "def": "谢谢", "emoji": "🙏", "hook": "🙏 谢谢 —— 多读多听，记住 thanks", "example": "跟读：\"thanks\" 意思是「谢谢」"},
  {"term": "please", "phonetic": "/pliːz/", "level": "L1", "def": "请", "emoji": "🤲", "hook": "🤲 请 —— 多读多听，记住 please", "example": "跟读：\"please\" 意思是「请」"},
  {"term": "sorry", "phonetic": "/ˈsɒr.i/", "level": "L1", "def": "抱歉", "emoji": "😔", "hook": "😔 抱歉 —— 多读多听，记住 sorry", "example": "跟读：\"sorry\" 意思是「抱歉」"},
  {"term": "like", "phonetic": "/laɪk/", "level": "L1", "def": "喜欢", "emoji": "💗", "hook": "💗 喜欢 —— 多读多听，记住 like", "example": "跟读：\"like\" 意思是「喜欢」"},
  {"term": "want", "phonetic": "/wɒnt/", "level": "L1", "def": "想要", "emoji": "🤲", "hook": "🤲 想要 —— 多读多听，记住 want", "example": "跟读：\"want\" 意思是「想要」"},
  {"term": "see", "phonetic": "/siː/", "level": "L1", "def": "看见", "emoji": "👀", "hook": "👀 看见 —— 多读多听，记住 see", "example": "跟读：\"see\" 意思是「看见」"},
  {"term": "look", "phonetic": "/lʊk/", "level": "L1", "def": "看", "emoji": "👁️", "hook": "👁️ 看 —— 多读多听，记住 look", "example": "跟读：\"look\" 意思是「看」"},
  {"term": "hear", "phonetic": "/hɪər/", "level": "L1", "def": "听见", "emoji": "👂", "hook": "👂 听见 —— 多读多听，记住 hear", "example": "跟读：\"hear\" 意思是「听见」"},
  {"term": "sad", "phonetic": "/sæd/", "level": "L1", "def": "伤心的", "emoji": "😢", "hook": "😢 伤心的 —— 多读多听，记住 sad", "example": "跟读：\"sad\" 意思是「伤心的」"},
  {"term": "angry", "phonetic": "/ˈæŋ.ɡri/", "level": "L1", "def": "生气的", "emoji": "😠", "hook": "😠 生气的 —— 多读多听，记住 angry", "example": "跟读：\"angry\" 意思是「生气的」"},
  {"term": "tired", "phonetic": "/ˈtaɪ.əd/", "level": "L1", "def": "累的", "emoji": "😩", "hook": "😩 累的 —— 多读多听，记住 tired", "example": "跟读：\"tired\" 意思是「累的」"},
  {"term": "walk", "phonetic": "/wɔːk/", "level": "L1", "def": "走路", "emoji": "🚶", "hook": "🚶 走路 —— 多读多听，记住 walk", "example": "跟读：\"walk\" 意思是「走路」"},
  {"term": "talk", "phonetic": "/tɔːk/", "level": "L1", "def": "说话", "emoji": "💬", "hook": "💬 说话 —— 多读多听，记住 talk", "example": "跟读：\"talk\" 意思是「说话」"},
  {"term": "come", "phonetic": "/kʌm/", "level": "L1", "def": "来", "emoji": "🚶", "hook": "🚶 来 —— 多读多听，记住 come", "example": "跟读：\"come\" 意思是「来」"},
  {"term": "play", "phonetic": "/pleɪ/", "level": "L1", "def": "玩", "emoji": "🎮", "hook": "🎮 玩 —— 多读多听，记住 play", "example": "跟读：\"play\" 意思是「玩」"},
  {"term": "read", "phonetic": "/riːd/", "level": "L1", "def": "读", "emoji": "📖", "hook": "📖 读 —— 多读多听，记住 read", "example": "跟读：\"read\" 意思是「读」"},
  {"term": "write", "phonetic": "/raɪt/", "level": "L1", "def": "写", "emoji": "✍️", "hook": "✍️ 写 —— 多读多听，记住 write", "example": "跟读：\"write\" 意思是「写」"},
  {"term": "drink", "phonetic": "/drɪŋk/", "level": "L1", "def": "喝", "emoji": "🥤", "hook": "🥤 喝 —— 多读多听，记住 drink", "example": "跟读：\"drink\" 意思是「喝」"},
  {"term": "sit", "phonetic": "/sɪt/", "level": "L1", "def": "坐", "emoji": "🪑", "hook": "🪑 坐 —— 多读多听，记住 sit", "example": "跟读：\"sit\" 意思是「坐」"},
  {"term": "stand", "phonetic": "/stænd/", "level": "L1", "def": "站", "emoji": "🧍", "hook": "🧍 站 —— 多读多听，记住 stand", "example": "跟读：\"stand\" 意思是「站」"},
  {"term": "open", "phonetic": "/ˈəʊ.pən/", "level": "L1", "def": "打开", "emoji": "🔓", "hook": "🔓 打开 —— 多读多听，记住 open", "example": "跟读：\"open\" 意思是「打开」"},
  {"term": "close", "phonetic": "/kləʊz/", "level": "L1", "def": "关上", "emoji": "🔒", "hook": "🔒 关上 —— 多读多听，记住 close", "example": "跟读：\"close\" 意思是「关上」"},
  {"term": "help", "phonetic": "/help/", "level": "L1", "def": "帮助", "emoji": "🆘", "hook": "🆘 帮助 —— 多读多听，记住 help", "example": "跟读：\"help\" 意思是「帮助」"},
  {"term": "give", "phonetic": "/ɡɪv/", "level": "L1", "def": "给", "emoji": "🎁", "hook": "🎁 给 —— 多读多听，记住 give", "example": "跟读：\"give\" 意思是「给」"},
  {"term": "take", "phonetic": "/teɪk/", "level": "L1", "def": "拿", "emoji": "✋", "hook": "✋ 拿 —— 多读多听，记住 take", "example": "跟读：\"take\" 意思是「拿」"},
  {"term": "make", "phonetic": "/meɪk/", "level": "L1", "def": "做；制作", "emoji": "🛠️", "hook": "🛠️ 做；制作 —— 多读多听，记住 make", "example": "跟读：\"make\" 意思是「做；制作」"},
  {"term": "find", "phonetic": "/faɪnd/", "level": "L1", "def": "找到", "emoji": "🔎", "hook": "🔎 找到 —— 多读多听，记住 find", "example": "跟读：\"find\" 意思是「找到」"},
  {"term": "clean", "phonetic": "/kliːn/", "level": "L1", "def": "干净的", "emoji": "🧼", "hook": "🧼 干净的 —— 多读多听，记住 clean", "example": "跟读：\"clean\" 意思是「干净的」"},
  {"term": "dirty", "phonetic": "/ˈdɜː.ti/", "level": "L1", "def": "脏的", "emoji": "🪣", "hook": "🪣 脏的 —— 多读多听，记住 dirty", "example": "跟读：\"dirty\" 意思是「脏的」"},
  {"term": "hot", "phonetic": "/hɒt/", "level": "L1", "def": "热的", "emoji": "🥵", "hook": "🥵 热的 —— 多读多听，记住 hot", "example": "跟读：\"hot\" 意思是「热的」"},
  {"term": "cold", "phonetic": "/kəʊld/", "level": "L1", "def": "冷的", "emoji": "🥶", "hook": "🥶 冷的 —— 多读多听，记住 cold", "example": "跟读：\"cold\" 意思是「冷的」"},
  {"term": "new", "phonetic": "/njuː/", "level": "L1", "def": "新的", "emoji": "🆕", "hook": "🆕 新的 —— 多读多听，记住 new", "example": "跟读：\"new\" 意思是「新的」"},
  {"term": "old", "phonetic": "/əʊld/", "level": "L1", "def": "旧的；老的", "emoji": "👴", "hook": "👴 旧的；老的 —— 多读多听，记住 old", "example": "跟读：\"old\" 意思是「旧的；老的」"},
  {"term": "big", "phonetic": "/bɪɡ/", "level": "L1", "def": "大的", "emoji": "🐘", "hook": "🐘 大的 —— 多读多听，记住 big", "example": "跟读：\"big\" 意思是「大的」"},
  {"term": "small", "phonetic": "/smɔːl/", "level": "L1", "def": "小的", "emoji": "🔹", "hook": "🔹 小的 —— 多读多听，记住 small", "example": "跟读：\"small\" 意思是「小的」"},
  {"term": "food", "phonetic": "/fuːd/", "level": "L1", "def": "食物", "emoji": "🍲", "hook": "🍲 食物 —— 多读多听，记住 food", "example": "跟读：\"food\" 意思是「食物」"},
  {"term": "money", "phonetic": "/ˈmʌn.i/", "level": "L1", "def": "钱", "emoji": "💰", "hook": "💰 钱 —— 多读多听，记住 money", "example": "跟读：\"money\" 意思是「钱」"},
  {"term": "time", "phonetic": "/taɪm/", "level": "L1", "def": "时间", "emoji": "⏰", "hook": "⏰ 时间 —— 多读多听，记住 time", "example": "跟读：\"time\" 意思是「时间」"},
  {"term": "morning", "phonetic": "/ˈmɔː.nɪŋ/", "level": "L1", "def": "早晨", "emoji": "🌅", "hook": "🌅 早晨 —— 多读多听，记住 morning", "example": "跟读：\"morning\" 意思是「早晨」"},
  {"term": "night", "phonetic": "/naɪt/", "level": "L1", "def": "夜晚", "emoji": "🌃", "hook": "🌃 夜晚 —— 多读多听，记住 night", "example": "跟读：\"night\" 意思是「夜晚」"},
  {"term": "week", "phonetic": "/wiːk/", "level": "L1", "def": "星期", "emoji": "🗓️", "hook": "🗓️ 星期 —— 多读多听，记住 week", "example": "跟读：\"week\" 意思是「星期」"},
  {"term": "name", "phonetic": "/neɪm/", "level": "L1", "def": "名字", "emoji": "🏷️", "hook": "🏷️ 名字 —— 多读多听，记住 name", "example": "跟读：\"name\" 意思是「名字」"},
  {"term": "home", "phonetic": "/həʊm/", "level": "L1", "def": "家", "emoji": "🏡", "hook": "🏡 家 —— 多读多听，记住 home", "example": "跟读：\"home\" 意思是「家」"},
  {"term": "door", "phonetic": "/dɔːr/", "level": "L1", "def": "门", "emoji": "🚪", "hook": "🚪 门 —— 多读多听，记住 door", "example": "跟读：\"door\" 意思是「门」"},
  {"term": "light", "phonetic": "/laɪt/", "level": "L1", "def": "灯；光", "emoji": "💡", "hook": "💡 灯；光 —— 多读多听，记住 light", "example": "跟读：\"light\" 意思是「灯；光」"},
  {"term": "dark", "phonetic": "/dɑːk/", "level": "L1", "def": "黑暗的", "emoji": "🌑", "hook": "🌑 黑暗的 —— 多读多听，记住 dark", "example": "跟读：\"dark\" 意思是「黑暗的」"},
  {"term": "warm", "phonetic": "/wɔːm/", "level": "L1", "def": "温暖的", "emoji": "🌡️", "hook": "🌡️ 温暖的 —— 多读多听，记住 warm", "example": "跟读：\"warm\" 意思是「温暖的」"},
  {"term": "love", "phonetic": "/lʌv/", "level": "L1", "def": "爱", "emoji": "❤️", "hook": "❤️ 爱 —— 多读多听，记住 love", "example": "跟读：\"love\" 意思是「爱」"},
  {"term": "work", "phonetic": "/wɜːk/", "level": "L1", "def": "工作", "emoji": "💼", "hook": "💼 工作 —— 多读多听，记住 work", "example": "跟读：\"work\" 意思是「工作」"},
  {"term": "year", "phonetic": "/jɪər/", "level": "L1", "def": "年", "emoji": "🎉", "hook": "🎉 年 —— 多读多听，记住 year", "example": "跟读：\"year\" 意思是「年」"},
  {"term": "number", "phonetic": "/ˈnʌm.bər/", "level": "L1", "def": "数字", "emoji": "🔢", "hook": "🔢 数字 —— 多读多听，记住 number", "example": "跟读：\"number\" 意思是「数字」"},
  {"term": "city", "phonetic": "/ˈsɪt.i/", "level": "L1", "def": "城市", "emoji": "🏙️", "hook": "🏙️ 城市 —— 多读多听，记住 city", "example": "跟读：\"city\" 意思是「城市」"},
  {"term": "park", "phonetic": "/pɑːk/", "level": "L1", "def": "公园", "emoji": "🏞️", "hook": "🏞️ 公园 —— 多读多听，记住 park", "example": "跟读：\"park\" 意思是「公园」"},
  {"term": "chair", "phonetic": "/tʃeər/", "level": "L1", "def": "椅子", "emoji": "🪑", "hook": "🪑 椅子 —— 多读多听，记住 chair", "example": "跟读：\"chair\" 意思是「椅子」"},
  {"term": "table", "phonetic": "/ˈteɪ.bəl/", "level": "L1", "def": "桌子", "emoji": "🛋️", "hook": "🛋️ 桌子 —— 多读多听，记住 table", "example": "跟读：\"table\" 意思是「桌子」"},
  {"term": "phone", "phonetic": "/fəʊn/", "level": "L1", "def": "电话", "emoji": "📱", "hook": "📱 电话 —— 多读多听，记住 phone", "example": "跟读：\"phone\" 意思是「电话」"},
  {"term": "computer", "phonetic": "/kəmˈpjuː.tər/", "level": "L1", "def": "电脑", "emoji": "💻", "hook": "💻 电脑 —— 多读多听，记住 computer", "example": "跟读：\"computer\" 意思是「电脑」"},
  {"term": "music", "phonetic": "/ˈmjuː.zɪk/", "level": "L1", "def": "音乐", "emoji": "🎵", "hook": "🎵 音乐 —— 多读多听，记住 music", "example": "跟读：\"music\" 意思是「音乐」"},
  {"term": "song", "phonetic": "/sɒŋ/", "level": "L1", "def": "歌曲", "emoji": "🎶", "hook": "🎶 歌曲 —— 多读多听，记住 song", "example": "跟读：\"song\" 意思是「歌曲」"},
  {"term": "game", "phonetic": "/ɡeɪm/", "level": "L1", "def": "游戏", "emoji": "🎲", "hook": "🎲 游戏 —— 多读多听，记住 game", "example": "跟读：\"game\" 意思是「游戏」"},
  {"term": "sport", "phonetic": "/spɔːt/", "level": "L1", "def": "运动", "emoji": "⚽", "hook": "⚽ 运动 —— 多读多听，记住 sport", "example": "跟读：\"sport\" 意思是「运动」"},
  {"term": "swim", "phonetic": "/swɪm/", "level": "L1", "def": "游泳", "emoji": "🏊", "hook": "🏊 游泳 —— 多读多听，记住 swim", "example": "跟读：\"swim\" 意思是「游泳」"},
  {"term": "jump", "phonetic": "/dʒʌmp/", "level": "L1", "def": "跳", "emoji": "🦘", "hook": "🦘 跳 —— 多读多听，记住 jump", "example": "跟读：\"jump\" 意思是「跳」"},
  {"term": "sing", "phonetic": "/sɪŋ/", "level": "L1", "def": "唱歌", "emoji": "🎤", "hook": "🎤 唱歌 —— 多读多听，记住 sing", "example": "跟读：\"sing\" 意思是「唱歌」"},
  {"term": "dance", "phonetic": "/dɑːns/", "level": "L1", "def": "跳舞", "emoji": "💃", "hook": "💃 跳舞 —— 多读多听，记住 dance", "example": "跟读：\"dance\" 意思是「跳舞」"},
  {"term": "smile", "phonetic": "/smaɪl/", "level": "L1", "def": "微笑", "emoji": "😄", "hook": "😄 微笑 —— 多读多听，记住 smile", "example": "跟读：\"smile\" 意思是「微笑」"},
  {"term": "cry", "phonetic": "/kraɪ/", "level": "L1", "def": "哭", "emoji": "😢", "hook": "😢 哭 —— 多读多听，记住 cry", "example": "跟读：\"cry\" 意思是「哭」"},
  {"term": "know", "phonetic": "/nəʊ/", "level": "L1", "def": "知道", "emoji": "🧠", "hook": "🧠 知道 —— 多读多听，记住 know", "example": "跟读：\"know\" 意思是「知道」"},
  {"term": "think", "phonetic": "/θɪŋk/", "level": "L1", "def": "思考", "emoji": "💭", "hook": "💭 思考 —— 多读多听，记住 think", "example": "跟读：\"think\" 意思是「思考」"},
  {"term": "learn", "phonetic": "/lɜːn/", "level": "L1", "def": "学习", "emoji": "📚", "hook": "📚 学习 —— 多读多听，记住 learn", "example": "跟读：\"learn\" 意思是「学习」"},
  {"term": "dream", "phonetic": "/driːm/", "level": "L1", "def": "梦想", "emoji": "💭", "hook": "💭 梦想 —— 多读多听，记住 dream", "example": "跟读：\"dream\" 意思是「梦想」"},
  {"term": "wish", "phonetic": "/wɪʃ/", "level": "L1", "def": "愿望", "emoji": "⭐", "hook": "⭐ 愿望 —— 多读多听，记住 wish", "example": "跟读：\"wish\" 意思是「愿望」"},
  {"term": "hope", "phonetic": "/həʊp/", "level": "L1", "def": "希望", "emoji": "🌟", "hook": "🌟 希望 —— 多读多听，记住 hope", "example": "跟读：\"hope\" 意思是「希望」"},
  {"term": "ambulance", "phonetic": "/ˈæm.bjə.ləns/", "level": "L2", "def": "救护车", "emoji": "🚑", "hook": "发音联想“俺不能死”→ 救护车救人命（正确拼写 a-m-b-u-l-a-n-c-e）", "example": "Call an ambulance now!"},
  {"term": "bicycle", "phonetic": "/ˈbaɪ.sɪ.kl/", "level": "L2", "def": "自行车", "emoji": "🚲", "hook": "两个轮子(bi=双)的骑车工具", "example": "He rides a bicycle to work."},
  {"term": "forest", "phonetic": "/ˈfɒr.ɪst/", "level": "L2", "def": "森林", "emoji": "🌲", "hook": "很多树连成片的大森林", "example": "They walked into the forest."},
  {"term": "secret", "phonetic": "/ˈsiː.krət/", "level": "L2", "def": "秘密", "emoji": "🤫", "hook": "不能说的悄悄话", "example": "It is a secret between us."},
  {"term": "fragile", "phonetic": "/ˈfrædʒ.aɪl/", "level": "L2", "def": "易碎的", "emoji": "🥚", "hook": "像鸡蛋一样一碰就碎 → 易碎的", "example": "The box is fragile."},
  {"term": "brilliant", "phonetic": "/ˈbrɪl.jənt/", "level": "L2", "def": "聪明的；耀眼的", "emoji": "💡", "hook": "像灯泡突然亮了 → 聪明的/耀眼的", "example": "She is a brilliant student."},
  {"term": "enormous", "phonetic": "/ɪˈnɔː.məs/", "level": "L2", "def": "巨大的", "emoji": "🐘", "hook": "比大象还大 → 巨大的", "example": "An enormous whale appeared."},
  {"term": "patient", "phonetic": "/ˈpeɪ.ʃənt/", "level": "L2", "def": "病人；有耐心的", "emoji": "🧘", "hook": "生病时等你的是病人；能等的是有耐心的", "example": "Be patient, it takes time."},
  {"term": "environment", "phonetic": "/ɪnˈvaɪ.rən.mənt/", "level": "L2", "def": "环境", "emoji": "🌍", "hook": "我们周围的“环”境", "example": "We must protect the environment."},
  {"term": "consider", "phonetic": "/kənˈsɪd.ər/", "level": "L2", "def": "考虑", "emoji": "🤔", "hook": "把事放在心里反复想 → 考虑", "example": "Please consider my idea."},
  {"term": "whisper", "phonetic": "/ˈwɪs.pər/", "level": "L2", "def": "耳语；低声说", "emoji": "🤫", "hook": "凑近耳朵轻轻说 → 耳语", "example": "She whispered to me."},
  {"term": "mountain", "phonetic": "/ˈmaʊn.tən/", "level": "L2", "def": "山", "emoji": "⛰️", "hook": "高耸入云的大山", "example": "We climbed the mountain."},
  {"term": "library", "phonetic": "/ˈlaɪ.brər.i/", "level": "L2", "def": "图书馆", "emoji": "📚", "hook": "摆满书、安静看书的地方", "example": "I borrow books from the library."},
  {"term": "restaurant", "phonetic": "/ˈres.trɒnt/", "level": "L2", "def": "餐厅", "emoji": "🍽️", "hook": "点菜吃饭的地方", "example": "We met at a restaurant."},
  {"term": "umbrella", "phonetic": "/ʌmˈbrel.ə/", "level": "L2", "def": "雨伞", "emoji": "☂️", "hook": "下雨撑开挡雨的用具", "example": "Take an umbrella, it may rain."},
  {"term": "vegetable", "phonetic": "/ˈvedʒ.tə.bəl/", "level": "L2", "def": "蔬菜", "emoji": "🥦", "hook": "绿绿的、健康的食物", "example": "Eat more vegetables daily."},
  {"term": "window", "phonetic": "/ˈwɪn.dəʊ/", "level": "L2", "def": "窗户", "emoji": "🪟", "hook": "墙上透光能看外面的口", "example": "Open the window for fresh air."},
  {"term": "bridge", "phonetic": "/brɪdʒ/", "level": "L2", "def": "桥", "emoji": "🌉", "hook": "跨过河的通道", "example": "We crossed the bridge."},
  {"term": "telephone", "phonetic": "/ˈtel.ɪ.fəʊn/", "level": "L2", "def": "电话", "emoji": "📞", "hook": "用来远距离说话的工具", "example": "Call me on the telephone."},
  {"term": "birthday", "phonetic": "/ˈbɜːθ.deɪ/", "level": "L2", "def": "生日", "emoji": "🎂", "hook": "你来到这天的纪念日", "example": "Happy birthday to you!"},
  {"term": "weather", "phonetic": "/ˈweð.ər/", "level": "L2", "def": "天气", "emoji": "🌤️", "hook": "今天冷热处理况", "example": "The weather is nice today."},
  {"term": "language", "phonetic": "/ˈlæŋ.ɡwɪdʒ/", "level": "L2", "def": "语言", "emoji": "🗣️", "hook": "人和人沟通的密码", "example": "English is a useful language."},
  {"term": "travel", "phonetic": "/ˈtræv.əl/", "level": "L2", "def": "旅行", "emoji": "✈️", "hook": "去远方看世界的动作", "example": "We love to travel in summer."},
  {"term": "healthy", "phonetic": "/ˈhel.θi/", "level": "L2", "def": "健康的", "emoji": "💪", "hook": "身体棒、少生病 → 健康的", "example": "Eat well to stay healthy."},
  {"term": "hospital", "phonetic": "/ˈhɒs.pɪ.tl/", "level": "L2", "def": "医院", "emoji": "🏥", "hook": "🏥 医院 —— 多读多听，记住 hospital", "example": "跟读：\"hospital\" 意思是「医院」"},
  {"term": "nurse", "phonetic": "/nɜːs/", "level": "L2", "def": "护士", "emoji": "👩‍⚕️", "hook": "👩‍⚕️ 护士 —— 多读多听，记住 nurse", "example": "跟读：\"nurse\" 意思是「护士」"},
  {"term": "medicine", "phonetic": "/ˈmed.ɪ.sɪn/", "level": "L2", "def": "药", "emoji": "💊", "hook": "💊 药 —— 多读多听，记住 medicine", "example": "跟读：\"medicine\" 意思是「药」"},
  {"term": "sick", "phonetic": "/sɪk/", "level": "L2", "def": "生病的", "emoji": "🤒", "hook": "🤒 生病的 —— 多读多听，记住 sick", "example": "跟读：\"sick\" 意思是「生病的」"},
  {"term": "sky", "phonetic": "/skaɪ/", "level": "L2", "def": "天空", "emoji": "🌌", "hook": "🌌 天空 —— 多读多听，记住 sky", "example": "跟读：\"sky\" 意思是「天空」"},
  {"term": "ice", "phonetic": "/aɪs/", "level": "L2", "def": "冰", "emoji": "🧊", "hook": "🧊 冰 —— 多读多听，记住 ice", "example": "跟读：\"ice\" 意思是「冰」"},
  {"term": "horse", "phonetic": "/hɔːs/", "level": "L2", "def": "马", "emoji": "🐴", "hook": "🐴 马 —— 多读多听，记住 horse", "example": "跟读：\"horse\" 意思是「马」"},
  {"term": "cow", "phonetic": "/kaʊ/", "level": "L2", "def": "奶牛", "emoji": "🐄", "hook": "🐄 奶牛 —— 多读多听，记住 cow", "example": "跟读：\"cow\" 意思是「奶牛」"},
  {"term": "pig", "phonetic": "/pɪɡ/", "level": "L2", "def": "猪", "emoji": "🐷", "hook": "🐷 猪 —— 多读多听，记住 pig", "example": "跟读：\"pig\" 意思是「猪」"},
  {"term": "sheep", "phonetic": "/ʃiːp/", "level": "L2", "def": "羊", "emoji": "🐑", "hook": "🐑 羊 —— 多读多听，记住 sheep", "example": "跟读：\"sheep\" 意思是「羊」"},
  {"term": "rabbit", "phonetic": "/ˈræb.ɪt/", "level": "L2", "def": "兔子", "emoji": "🐰", "hook": "🐰 兔子 —— 多读多听，记住 rabbit", "example": "跟读：\"rabbit\" 意思是「兔子」"},
  {"term": "monkey", "phonetic": "/ˈmʌŋ.ki/", "level": "L2", "def": "猴子", "emoji": "🐵", "hook": "🐵 猴子 —— 多读多听，记住 monkey", "example": "跟读：\"monkey\" 意思是「猴子」"},
  {"term": "tiger", "phonetic": "/ˈtaɪ.ɡər/", "level": "L2", "def": "老虎", "emoji": "🐯", "hook": "🐯 老虎 —— 多读多听，记住 tiger", "example": "跟读：\"tiger\" 意思是「老虎」"},
  {"term": "lion", "phonetic": "/ˈlaɪ.ən/", "level": "L2", "def": "狮子", "emoji": "🦁", "hook": "🦁 狮子 —— 多读多听，记住 lion", "example": "跟读：\"lion\" 意思是「狮子」"},
  {"term": "bear", "phonetic": "/beər/", "level": "L2", "def": "熊", "emoji": "🐻", "hook": "🐻 熊 —— 多读多听，记住 bear", "example": "跟读：\"bear\" 意思是「熊」"},
  {"term": "snake", "phonetic": "/sneɪk/", "level": "L2", "def": "蛇", "emoji": "🐍", "hook": "🐍 蛇 —— 多读多听，记住 snake", "example": "跟读：\"snake\" 意思是「蛇」"},
  {"term": "mouse", "phonetic": "/maʊs/", "level": "L2", "def": "老鼠", "emoji": "🐭", "hook": "🐭 老鼠 —— 多读多听，记住 mouse", "example": "跟读：\"mouse\" 意思是「老鼠」"},
  {"term": "long", "phonetic": "/lɒŋ/", "level": "L2", "def": "长的", "emoji": "📏", "hook": "📏 长的 —— 多读多听，记住 long", "example": "跟读：\"long\" 意思是「长的」"},
  {"term": "short", "phonetic": "/ʃɔːt/", "level": "L2", "def": "短的", "emoji": "✂️", "hook": "✂️ 短的 —— 多读多听，记住 short", "example": "跟读：\"short\" 意思是「短的」"},
  {"term": "tall", "phonetic": "/tɔːl/", "level": "L2", "def": "高的", "emoji": "📏", "hook": "📏 高的 —— 多读多听，记住 tall", "example": "跟读：\"tall\" 意思是「高的」"},
  {"term": "early", "phonetic": "/ˈɜːli/", "level": "L2", "def": "早的", "emoji": "🌅", "hook": "🌅 早的 —— 多读多听，记住 early", "example": "跟读：\"early\" 意思是「早的」"},
  {"term": "late", "phonetic": "/leɪt/", "level": "L2", "def": "晚的", "emoji": "🌙", "hook": "🌙 晚的 —— 多读多听，记住 late", "example": "跟读：\"late\" 意思是「晚的」"},
  {"term": "young", "phonetic": "/jʌŋ/", "level": "L2", "def": "年轻的", "emoji": "🧒", "hook": "🧒 年轻的 —— 多读多听，记住 young", "example": "跟读：\"young\" 意思是「年轻的」"},
  {"term": "busy", "phonetic": "/ˈbɪz.i/", "level": "L2", "def": "忙碌的", "emoji": "🏃", "hook": "🏃 忙碌的 —— 多读多听，记住 busy", "example": "跟读：\"busy\" 意思是「忙碌的」"},
  {"term": "free", "phonetic": "/friː/", "level": "L2", "def": "空闲的", "emoji": "🆓", "hook": "🆓 空闲的 —— 多读多听，记住 free", "example": "跟读：\"free\" 意思是「空闲的」"},
  {"term": "buy", "phonetic": "/baɪ/", "level": "L2", "def": "买", "emoji": "🛒", "hook": "🛒 买 —— 多读多听，记住 buy", "example": "跟读：\"buy\" 意思是「买」"},
  {"term": "sell", "phonetic": "/sel/", "level": "L2", "def": "卖", "emoji": "💱", "hook": "💱 卖 —— 多读多听，记住 sell", "example": "跟读：\"sell\" 意思是「卖」"},
  {"term": "price", "phonetic": "/praɪs/", "level": "L2", "def": "价格", "emoji": "🏷️", "hook": "🏷️ 价格 —— 多读多听，记住 price", "example": "跟读：\"price\" 意思是「价格」"},
  {"term": "market", "phonetic": "/ˈmɑː.kɪt/", "level": "L2", "def": "市场", "emoji": "🛒", "hook": "🛒 市场 —— 多读多听，记住 market", "example": "跟读：\"market\" 意思是「市场」"},
  {"term": "shop", "phonetic": "/ʃɒp/", "level": "L2", "def": "商店", "emoji": "🏪", "hook": "🏪 商店 —— 多读多听，记住 shop", "example": "跟读：\"shop\" 意思是「商店」"},
  {"term": "bank", "phonetic": "/bæŋk/", "level": "L2", "def": "银行", "emoji": "🏦", "hook": "🏦 银行 —— 多读多听，记住 bank", "example": "跟读：\"bank\" 意思是「银行」"},
  {"term": "post", "phonetic": "/pəʊst/", "level": "L2", "def": "邮政", "emoji": "📮", "hook": "📮 邮政 —— 多读多听，记住 post", "example": "跟读：\"post\" 意思是「邮政」"},
  {"term": "gift", "phonetic": "/ɡɪft/", "level": "L2", "def": "礼物", "emoji": "🎁", "hook": "🎁 礼物 —— 多读多听，记住 gift", "example": "跟读：\"gift\" 意思是「礼物」"},
  {"term": "party", "phonetic": "/ˈpɑː.ti/", "level": "L2", "def": "聚会", "emoji": "🎉", "hook": "🎉 聚会 —— 多读多听，记住 party", "example": "跟读：\"party\" 意思是「聚会」"},
  {"term": "holiday", "phonetic": "/ˈhɒl.ə.deɪ/", "level": "L2", "def": "假期", "emoji": "🏖️", "hook": "🏖️ 假期 —— 多读多听，记住 holiday", "example": "跟读：\"holiday\" 意思是「假期」"},
  {"term": "trip", "phonetic": "/trɪp/", "level": "L2", "def": "旅行", "emoji": "🧳", "hook": "🧳 旅行 —— 多读多听，记住 trip", "example": "跟读：\"trip\" 意思是「旅行」"},
  {"term": "country", "phonetic": "/ˈkʌn.tri/", "level": "L2", "def": "国家", "emoji": "🏳️", "hook": "🏳️ 国家 —— 多读多听，记住 country", "example": "跟读：\"country\" 意思是「国家」"},
  {"term": "world", "phonetic": "/wɜːld/", "level": "L2", "def": "世界", "emoji": "🌐", "hook": "🌐 世界 —— 多读多听，记住 world", "example": "跟读：\"world\" 意思是「世界」"},
  {"term": "culture", "phonetic": "/ˈkʌl.tʃər/", "level": "L2", "def": "文化", "emoji": "🏛️", "hook": "🏛️ 文化 —— 多读多听，记住 culture", "example": "跟读：\"culture\" 意思是「文化」"},
  {"term": "history", "phonetic": "/ˈhɪs.tə.ri/", "level": "L2", "def": "历史", "emoji": "📜", "hook": "📜 历史 —— 多读多听，记住 history", "example": "跟读：\"history\" 意思是「历史」"},
  {"term": "future", "phonetic": "/ˈfjuː.tʃər/", "level": "L2", "def": "未来", "emoji": "🔮", "hook": "🔮 未来 —— 多读多听，记住 future", "example": "跟读：\"future\" 意思是「未来」"},
  {"term": "past", "phonetic": "/pɑːst/", "level": "L2", "def": "过去", "emoji": "⏳", "hook": "⏳ 过去 —— 多读多听，记住 past", "example": "跟读：\"past\" 意思是「过去」"},
  {"term": "airport", "phonetic": "/ˈeə.pɔːt/", "level": "L2", "def": "机场", "emoji": "✈️", "hook": "✈️ 机场 —— 多读多听，记住 airport", "example": "跟读：\"airport\" 意思是「机场」"},
  {"term": "station", "phonetic": "/ˈsteɪ.ʃən/", "level": "L2", "def": "车站", "emoji": "🚉", "hook": "🚉 车站 —— 多读多听，记住 station", "example": "跟读：\"station\" 意思是「车站」"},
  {"term": "ticket", "phonetic": "/ˈtɪk.ɪt/", "level": "L2", "def": "票", "emoji": "🎫", "hook": "🎫 票 —— 多读多听，记住 ticket", "example": "跟读：\"ticket\" 意思是「票」"},
  {"term": "beach", "phonetic": "/biːtʃ/", "level": "L2", "def": "海滩", "emoji": "🏖️", "hook": "🏖️ 海滩 —— 多读多听，记住 beach", "example": "跟读：\"beach\" 意思是「海滩」"},
  {"term": "island", "phonetic": "/ˈaɪ.lənd/", "level": "L2", "def": "岛屿", "emoji": "🏝️", "hook": "🏝️ 岛屿 —— 多读多听，记住 island", "example": "跟读：\"island\" 意思是「岛屿」"},
  {"term": "lake", "phonetic": "/leɪk/", "level": "L2", "def": "湖", "emoji": "🏞️", "hook": "🏞️ 湖 —— 多读多听，记住 lake", "example": "跟读：\"lake\" 意思是「湖」"},
  {"term": "river", "phonetic": "/ˈrɪv.ər/", "level": "L2", "def": "河流", "emoji": "🌊", "hook": "🌊 河流 —— 多读多听，记住 river", "example": "跟读：\"river\" 意思是「河流」"},
  {"term": "road", "phonetic": "/rəʊd/", "level": "L2", "def": "道路", "emoji": "🛣️", "hook": "🛣️ 道路 —— 多读多听，记住 road", "example": "跟读：\"road\" 意思是「道路」"},
  {"term": "train", "phonetic": "/treɪn/", "level": "L2", "def": "火车", "emoji": "🚄", "hook": "🚄 火车 —— 多读多听，记住 train", "example": "跟读：\"train\" 意思是「火车」"},
  {"term": "boat", "phonetic": "/bəʊt/", "level": "L2", "def": "小船", "emoji": "⛵", "hook": "⛵ 小船 —— 多读多听，记住 boat", "example": "跟读：\"boat\" 意思是「小船」"},
  {"term": "ship", "phonetic": "/ʃɪp/", "level": "L2", "def": "轮船", "emoji": "🚢", "hook": "🚢 轮船 —— 多读多听，记住 ship", "example": "跟读：\"ship\" 意思是「轮船」"},
  {"term": "plane", "phonetic": "/pleɪn/", "level": "L2", "def": "飞机", "emoji": "✈️", "hook": "✈️ 飞机 —— 多读多听，记住 plane", "example": "跟读：\"plane\" 意思是「飞机」"},
  {"term": "bus", "phonetic": "/bʌs/", "level": "L2", "def": "公交车", "emoji": "🚌", "hook": "🚌 公交车 —— 多读多听，记住 bus", "example": "跟读：\"bus\" 意思是「公交车」"},
  {"term": "subway", "phonetic": "/ˈsʌb.weɪ/", "level": "L2", "def": "地铁", "emoji": "🚇", "hook": "🚇 地铁 —— 多读多听，记住 subway", "example": "跟读：\"subway\" 意思是「地铁」"},
  {"term": "cinema", "phonetic": "/ˈsɪn.ə.mə/", "level": "L2", "def": "电影院", "emoji": "🎬", "hook": "🎬 电影院 —— 多读多听，记住 cinema", "example": "跟读：\"cinema\" 意思是「电影院」"},
  {"term": "museum", "phonetic": "/mjuˈziː.əm/", "level": "L2", "def": "博物馆", "emoji": "🏛️", "hook": "🏛️ 博物馆 —— 多读多听，记住 museum", "example": "跟读：\"museum\" 意思是「博物馆」"},
  {"term": "theater", "phonetic": "/ˈθɪə.tər/", "level": "L2", "def": "剧院", "emoji": "🎭", "hook": "🎭 剧院 —— 多读多听，记住 theater", "example": "跟读：\"theater\" 意思是「剧院」"},
  {"term": "supermarket", "phonetic": "/ˈsuː.pəˌmɑː.kɪt/", "level": "L2", "def": "超市", "emoji": "🛒", "hook": "🛒 超市 —— 多读多听，记住 supermarket", "example": "跟读：\"supermarket\" 意思是「超市」"},
  {"term": "hotel", "phonetic": "/həʊˈtel/", "level": "L2", "def": "酒店", "emoji": "🏨", "hook": "🏨 酒店 —— 多读多听，记住 hotel", "example": "跟读：\"hotel\" 意思是「酒店」"},
  {"term": "garden", "phonetic": "/ˈɡɑː.dən/", "level": "L2", "def": "花园", "emoji": "🌷", "hook": "🌷 花园 —— 多读多听，记住 garden", "example": "跟读：\"garden\" 意思是「花园」"},
  {"term": "kitchen", "phonetic": "/ˈkɪtʃ.ɪn/", "level": "L2", "def": "厨房", "emoji": "🍳", "hook": "🍳 厨房 —— 多读多听，记住 kitchen", "example": "跟读：\"kitchen\" 意思是「厨房」"},
  {"term": "bedroom", "phonetic": "/ˈbed.rʊm/", "level": "L2", "def": "卧室", "emoji": "🛏️", "hook": "🛏️ 卧室 —— 多读多听，记住 bedroom", "example": "跟读：\"bedroom\" 意思是「卧室」"},
  {"term": "bathroom", "phonetic": "/ˈbɑːθ.rʊm/", "level": "L2", "def": "浴室", "emoji": "🛁", "hook": "🛁 浴室 —— 多读多听，记住 bathroom", "example": "跟读：\"bathroom\" 意思是「浴室」"},
  {"term": "office", "phonetic": "/ˈɒf.ɪs/", "level": "L2", "def": "办公室", "emoji": "🏢", "hook": "🏢 办公室 —— 多读多听，记住 office", "example": "跟读：\"office\" 意思是「办公室」"},
  {"term": "factory", "phonetic": "/ˈfæk.tər.i/", "level": "L2", "def": "工厂", "emoji": "🏭", "hook": "🏭 工厂 —— 多读多听，记住 factory", "example": "跟读：\"factory\" 意思是「工厂」"},
  {"term": "farm", "phonetic": "/fɑːm/", "level": "L2", "def": "农场", "emoji": "🚜", "hook": "🚜 农场 —— 多读多听，记住 farm", "example": "跟读：\"farm\" 意思是「农场」"},
  {"term": "field", "phonetic": "/fiːld/", "level": "L2", "def": "田野", "emoji": "🌾", "hook": "🌾 田野 —— 多读多听，记住 field", "example": "跟读：\"field\" 意思是「田野」"},
  {"term": "cloud", "phonetic": "/klaʊd/", "level": "L2", "def": "云", "emoji": "☁️", "hook": "☁️ 云 —— 多读多听，记住 cloud", "example": "跟读：\"cloud\" 意思是「云」"},
  {"term": "wind", "phonetic": "/wɪnd/", "level": "L2", "def": "风", "emoji": "🌬️", "hook": "🌬️ 风 —— 多读多听，记住 wind", "example": "跟读：\"wind\" 意思是「风」"},
  {"term": "snow", "phonetic": "/snəʊ/", "level": "L2", "def": "雪", "emoji": "❄️", "hook": "❄️ 雪 —— 多读多听，记住 snow", "example": "跟读：\"snow\" 意思是「雪」"},
  {"term": "storm", "phonetic": "/stɔːm/", "level": "L2", "def": "暴风雨", "emoji": "⛈️", "hook": "⛈️ 暴风雨 —— 多读多听，记住 storm", "example": "跟读：\"storm\" 意思是「暴风雨」"},
  {"term": "spring", "phonetic": "/sprɪŋ/", "level": "L2", "def": "春天", "emoji": "🌸", "hook": "🌸 春天 —— 多读多听，记住 spring", "example": "跟读：\"spring\" 意思是「春天」"},
  {"term": "summer", "phonetic": "/ˈsʌm.ər/", "level": "L2", "def": "夏天", "emoji": "☀️", "hook": "☀️ 夏天 —— 多读多听，记住 summer", "example": "跟读：\"summer\" 意思是「夏天」"},
  {"term": "autumn", "phonetic": "/ˈɔː.təm/", "level": "L2", "def": "秋天", "emoji": "🍂", "hook": "🍂 秋天 —— 多读多听，记住 autumn", "example": "跟读：\"autumn\" 意思是「秋天」"},
  {"term": "winter", "phonetic": "/ˈwɪn.tər/", "level": "L2", "def": "冬天", "emoji": "⛄", "hook": "⛄ 冬天 —— 多读多听，记住 winter", "example": "跟读：\"winter\" 意思是「冬天」"},
  {"term": "weekend", "phonetic": "/ˈwiːk.end/", "level": "L2", "def": "周末", "emoji": "🎏", "hook": "🎏 周末 —— 多读多听，记住 weekend", "example": "跟读：\"weekend\" 意思是「周末」"},
  {"term": "festival", "phonetic": "/ˈfes.tɪ.vəl/", "level": "L2", "def": "节日", "emoji": "🎊", "hook": "🎊 节日 —— 多读多听，记住 festival", "example": "跟读：\"festival\" 意思是「节日」"},
  {"term": "guest", "phonetic": "/ɡest/", "level": "L2", "def": "客人", "emoji": "🙋", "hook": "🙋 客人 —— 多读多听，记住 guest", "example": "跟读：\"guest\" 意思是「客人」"},
  {"term": "neighbor", "phonetic": "/ˈneɪ.bər/", "level": "L2", "def": "邻居", "emoji": "🏘️", "hook": "🏘️ 邻居 —— 多读多听，记住 neighbor", "example": "跟读：\"neighbor\" 意思是「邻居」"},
  {"term": "letter", "phonetic": "/ˈlet.ər/", "level": "L2", "def": "信", "emoji": "✉️", "hook": "✉️ 信 —— 多读多听，记住 letter", "example": "跟读：\"letter\" 意思是「信」"},
  {"term": "email", "phonetic": "/ˈiː.meɪl/", "level": "L2", "def": "电子邮件", "emoji": "📧", "hook": "📧 电子邮件 —— 多读多听，记住 email", "example": "跟读：\"email\" 意思是「电子邮件」"},
  {"term": "message", "phonetic": "/ˈmes.ɪdʒ/", "level": "L2", "def": "消息", "emoji": "💬", "hook": "💬 消息 —— 多读多听，记住 message", "example": "跟读：\"message\" 意思是「消息」"},
  {"term": "call", "phonetic": "/kɔːl/", "level": "L2", "def": "打电话", "emoji": "📞", "hook": "📞 打电话 —— 多读多听，记住 call", "example": "跟读：\"call\" 意思是「打电话」"},
  {"term": "meet", "phonetic": "/miːt/", "level": "L2", "def": "遇见", "emoji": "🤝", "hook": "🤝 遇见 —— 多读多听，记住 meet", "example": "跟读：\"meet\" 意思是「遇见」"},
  {"term": "invite", "phonetic": "/ɪnˈvaɪt/", "level": "L2", "def": "邀请", "emoji": "✉️", "hook": "✉️ 邀请 —— 多读多听，记住 invite", "example": "跟读：\"invite\" 意思是「邀请」"},
  {"term": "celebrate", "phonetic": "/ˈsel.ɪ.breɪt/", "level": "L2", "def": "庆祝", "emoji": "🎉", "hook": "🎉 庆祝 —— 多读多听，记住 celebrate", "example": "跟读：\"celebrate\" 意思是「庆祝」"},
  {"term": "win", "phonetic": "/wɪn/", "level": "L2", "def": "赢", "emoji": "🥇", "hook": "🥇 赢 —— 多读多听，记住 win", "example": "跟读：\"win\" 意思是「赢」"},
  {"term": "lose", "phonetic": "/luːz/", "level": "L2", "def": "输", "emoji": "😞", "hook": "😞 输 —— 多读多听，记住 lose", "example": "跟读：\"lose\" 意思是「输」"},
  {"term": "compete", "phonetic": "/kəmˈpiːt/", "level": "L2", "def": "竞争", "emoji": "🏅", "hook": "🏅 竞争 —— 多读多听，记住 compete", "example": "跟读：\"compete\" 意思是「竞争」"},
  {"term": "ambition", "phonetic": "/æmˈbɪʃ.ən/", "level": "L3", "def": "野心；抱负", "emoji": "🚀", "hook": "心里有火想往上冲 → 野心/抱负", "example": "His ambition is to be a pilot."},
  {"term": "circumstance", "phonetic": "/ˈsɜː.kəm.stɑːns/", "level": "L3", "def": "环境；情况", "emoji": "🔄", "hook": "站在圆环(circle)里做事 → 周围的情况", "example": "Under the circumstance, we waited."},
  {"term": "dilemma", "phonetic": "/dɪˈlem.ə/", "level": "L3", "def": "困境；两难", "emoji": "😣", "hook": "两难(di=双)的困境", "example": "He faced a real dilemma."},
  {"term": "elaborate", "phonetic": "/ɪˈlæb.ər.ət/", "level": "L3", "def": "精心制作的；详尽的", "emoji": "🎨", "hook": "往外(e-)劳动(labor)打磨 → 精心制作的", "example": "She made an elaborate plan."},
  {"term": "phenomenon", "phonetic": "/fəˈnɒm.ɪ.nən/", "level": "L3", "def": "现象", "emoji": "🌈", "hook": "天上出现的奇景 → 现象", "example": "The rainbow is a natural phenomenon."},
  {"term": "spontaneous", "phonetic": "/spɒnˈteɪ.ni.əs/", "level": "L3", "def": "自发的", "emoji": "✨", "hook": "自己(spon)冒出来的 → 自发的", "example": "A spontaneous trip sounds fun."},
  {"term": "reluctant", "phonetic": "/rɪˈlʌk.tənt/", "level": "L3", "def": "不情愿的", "emoji": "🛑", "hook": "不肯往前 → 不情愿的", "example": "He was reluctant to leave."},
  {"term": "tedious", "phonetic": "/ˈtiː.di.əs/", "level": "L3", "def": "冗长乏味的", "emoji": "⏳", "hook": "时间长到让人烦 → 冗长乏味的", "example": "The meeting was tedious."},
  {"term": "vulnerable", "phonetic": "/ˈvʌl.nər.ə.bəl/", "level": "L3", "def": "脆弱的", "emoji": "🛡️", "hook": "盾牌挡不住 → 脆弱的", "example": "Children are vulnerable."},
  {"term": "alleviate", "phonetic": "/əˈliː.vi.eɪt/", "level": "L3", "def": "缓解；减轻", "emoji": "🪶", "hook": "把重量(lev)减轻 → 缓解", "example": "This medicine alleviates pain."},
  {"term": "magnificent", "phonetic": "/mæɡˈnɪf.ɪ.sənt/", "level": "L3", "def": "宏伟的；壮丽的", "emoji": "👑", "hook": "配得上加冕的 → 宏伟的/壮丽的", "example": "What a magnificent view!"},
  {"term": "subsequent", "phonetic": "/ˈsʌb.sɪ.kwənt/", "level": "L3", "def": "随后的", "emoji": "➡️", "hook": "跟在(sub-)后面的 → 随后的", "example": "Subsequent events proved him right."},
  {"term": "inevitable", "phonetic": "/ɪnˈev.ɪ.tə.bəl/", "level": "L3", "def": "不可避免的", "emoji": "⛓️", "hook": "躲不掉的 → 必然发生的", "example": "Mistakes are inevitable sometimes."},
  {"term": "comprehensive", "phonetic": "/ˌkɒm.prɪˈhen.sɪv/", "level": "L3", "def": "全面的；综合的", "emoji": "🧩", "hook": "全抓(com-)理解 → 全面的", "example": "We need a comprehensive plan."},
  {"term": "scrutinize", "phonetic": "/ˈskruː.tɪ.naɪz/", "level": "L3", "def": "仔细审查", "emoji": "🔍", "hook": "用放大镜看 → 细查", "example": "Scrutinize the contract carefully."},
  {"term": "resilient", "phonetic": "/rɪˈzɪl.i.ənt/", "level": "L3", "def": "有韧性的", "emoji": "🌱", "hook": "压弯还能弹回 → 坚韧的", "example": "She is resilient under pressure."},
  {"term": "profound", "phonetic": "/prəˈfaʊnd/", "level": "L3", "def": "深刻的", "emoji": "🌊", "hook": "像深海一样深 → 深刻的", "example": "A profound question worth thinking."},
  {"term": "diligent", "phonetic": "/ˈdɪl.ɪ.dʒənt/", "level": "L3", "def": "勤勉的", "emoji": "📖", "hook": "努力不偷懒 → 勤奋的", "example": "A diligent student studies daily."},
  {"term": "candidate", "phonetic": "/ˈkæn.dɪ.dət/", "level": "L3", "def": "候选人", "emoji": "🗳️", "hook": "等着被选的人 → 候选人", "example": "He is a candidate for the job."},
  {"term": "negotiate", "phonetic": "/nɪˈɡəʊ.ʃi.eɪt/", "level": "L3", "def": "谈判；协商", "emoji": "🤝", "hook": "双方来回谈条件 → 协商", "example": "They negotiate a better price."},
  {"term": "abandon", "phonetic": "/əˈbæn.dən/", "level": "L3", "def": "放弃", "emoji": "🚪", "hook": "a(离开)+band(绑)→ 解开束缚 → 放弃", "example": "跟读：\"abandon\" 意思是「放弃」"},
  {"term": "accumulate", "phonetic": "/əˈkjuː.mjə.leɪt/", "level": "L3", "def": "积累", "emoji": "📚", "hook": "积累(ac-)到一起 → 越攒越多", "example": "跟读：\"accumulate\" 意思是「积累」"},
  {"term": "adequate", "phonetic": "/ˈæd.ɪ.kwət/", "level": "L3", "def": "足够的", "emoji": "✅", "hook": "ad(去)+equ(相等)→ 刚好够 → 足够的", "example": "跟读：\"adequate\" 意思是「足够的」"},
  {"term": "anticipate", "phonetic": "/ænˈtɪs.ɪ.peɪt/", "level": "L3", "def": "预期", "emoji": "🔮", "hook": "提前(after)抓(cap)住 → 预期", "example": "跟读：\"anticipate\" 意思是「预期」"},
  {"term": "apparent", "phonetic": "/əˈpær.ənt/", "level": "L3", "def": "明显的", "emoji": "👀", "hook": "👀 明显的 —— 多读多听，记住 apparent", "example": "跟读：\"apparent\" 意思是「明显的」"},
  {"term": "approximate", "phonetic": "/əˈprɒk.sɪ.mət/", "level": "L3", "def": "近似的", "emoji": "📏", "hook": "📏 近似的 —— 多读多听，记住 approximate", "example": "跟读：\"approximate\" 意思是「近似的」"},
  {"term": "arbitrary", "phonetic": "/ˈɑː.bɪ.trər.i/", "level": "L3", "def": "武断的", "emoji": "🎲", "hook": "🎲 武断的 —— 多读多听，记住 arbitrary", "example": "跟读：\"arbitrary\" 意思是「武断的」"},
  {"term": "assess", "phonetic": "/əˈses/", "level": "L3", "def": "评估", "emoji": "⚖️", "hook": "坐下来细看 → 评估", "example": "跟读：\"assess\" 意思是「评估」"},
  {"term": "attribute", "phonetic": "/əˈtrɪb.juːt/", "level": "L3", "def": "归因于", "emoji": "🔗", "hook": "把原因(a-)归给(tribute) → 归因于", "example": "跟读：\"attribute\" 意思是「归因于」"},
  {"term": "authentic", "phonetic": "/ɔːˈθen.tɪk/", "level": "L3", "def": "真实的", "emoji": "✅", "hook": "✅ 真实的 —— 多读多听，记住 authentic", "example": "跟读：\"authentic\" 意思是「真实的」"},
  {"term": "bias", "phonetic": "/ˈbaɪ.əs/", "level": "L3", "def": "偏见", "emoji": "⚖️", "hook": "⚖️ 偏见 —— 多读多听，记住 bias", "example": "跟读：\"bias\" 意思是「偏见」"},
  {"term": "coherent", "phonetic": "/kəʊˈhɪə.rənt/", "level": "L3", "def": "连贯的", "emoji": "🔗", "hook": "🔗 连贯的 —— 多读多听，记住 coherent", "example": "跟读：\"coherent\" 意思是「连贯的」"},
  {"term": "comply", "phonetic": "/kəmˈplaɪ/", "level": "L3", "def": "遵守", "emoji": "📋", "hook": "com(一起)+ply(折)→ 折服照做 → 遵守", "example": "跟读：\"comply\" 意思是「遵守」"},
  {"term": "conceive", "phonetic": "/kənˈsiːv/", "level": "L3", "def": "构想", "emoji": "💡", "hook": "💡 构想 —— 多读多听，记住 conceive", "example": "跟读：\"conceive\" 意思是「构想」"},
  {"term": "consequence", "phonetic": "/ˈkɒn.sɪ.kwəns/", "level": "L3", "def": "后果", "emoji": "⛓️", "hook": "跟着(con-)结果(sequence)→ 后果", "example": "跟读：\"consequence\" 意思是「后果」"},
  {"term": "consolidate", "phonetic": "/kənˈsɒl.ɪ.deɪt/", "level": "L3", "def": "巩固", "emoji": "🧱", "hook": "一起(con-)变 solid → 巩固", "example": "跟读：\"consolidate\" 意思是「巩固」"},
  {"term": "contemporary", "phonetic": "/kənˈtem.pər.ər.i/", "level": "L3", "def": "当代的", "emoji": "🕰️", "hook": "🕰️ 当代的 —— 多读多听，记住 contemporary", "example": "跟读：\"contemporary\" 意思是「当代的」"},
  {"term": "contradict", "phonetic": "/ˌkɒn.trəˈdɪkt/", "level": "L3", "def": "矛盾", "emoji": "⚡", "hook": "contra(反)+dict(说)→ 反着说 → 矛盾", "example": "跟读：\"contradict\" 意思是「矛盾」"},
  {"term": "deliberate", "phonetic": "/dɪˈlɪb.ər.ət/", "level": "L3", "def": "故意的", "emoji": "🎯", "hook": "de(下)+liber(秤)→ 掂量后 → 故意的", "example": "跟读：\"deliberate\" 意思是「故意的」"},
  {"term": "diminish", "phonetic": "/dɪˈmɪn.ɪʃ/", "level": "L3", "def": "减少", "emoji": "📉", "hook": "一点点(min)变小 → 减少", "example": "跟读：\"diminish\" 意思是「减少」"},
  {"term": "distinct", "phonetic": "/dɪˈstɪŋkt/", "level": "L3", "def": "明显的", "emoji": "🔍", "hook": "🔍 明显的 —— 多读多听，记住 distinct", "example": "跟读：\"distinct\" 意思是「明显的」"},
  {"term": "elegant", "phonetic": "/ˈel.ɪ.ɡənt/", "level": "L3", "def": "优雅的", "emoji": "💃", "hook": "💃 优雅的 —— 多读多听，记住 elegant", "example": "跟读：\"elegant\" 意思是「优雅的」"},
  {"term": "emphasize", "phonetic": "/ˈem.fə.saɪz/", "level": "L3", "def": "强调", "emoji": "📣", "hook": "em(使)+phase(显)→ 使其显眼 → 强调", "example": "跟读：\"emphasize\" 意思是「强调」"},
  {"term": "enhance", "phonetic": "/ɪnˈhɑːns/", "level": "L3", "def": "提升", "emoji": "⬆️", "hook": "en(使)+hance(高)→ 抬高 → 提升", "example": "跟读：\"enhance\" 意思是「提升」"},
  {"term": "explicit", "phonetic": "/ɪkˈsplɪs.ɪt/", "level": "L3", "def": "明确的", "emoji": "🗣️", "hook": "🗣️ 明确的 —— 多读多听，记住 explicit", "example": "跟读：\"explicit\" 意思是「明确的」"},
  {"term": "feasible", "phonetic": "/ˈfiː.zə.bəl/", "level": "L3", "def": "可行的", "emoji": "✅", "hook": "✅ 可行的 —— 多读多听，记住 feasible", "example": "跟读：\"feasible\" 意思是「可行的」"},
  {"term": "fluctuate", "phonetic": "/ˈflʌk.tʃu.eɪt/", "level": "L3", "def": "波动", "emoji": "📈", "hook": "📈 波动 —— 多读多听，记住 fluctuate", "example": "跟读：\"fluctuate\" 意思是「波动」"},
  {"term": "formulate", "phonetic": "/ˈfɔː.mju.leɪt/", "level": "L3", "def": "制定", "emoji": "📝", "hook": "📝 制定 —— 多读多听，记住 formulate", "example": "跟读：\"formulate\" 意思是「制定」"},
  {"term": "fundamental", "phonetic": "/ˌfʌn.dəˈmen.təl/", "level": "L3", "def": "基本的", "emoji": "🏗️", "hook": "🏗️ 基本的 —— 多读多听，记住 fundamental", "example": "跟读：\"fundamental\" 意思是「基本的」"},
  {"term": "hypothesis", "phonetic": "/haɪˈpɒθ.ə.sɪs/", "level": "L3", "def": "假设", "emoji": "❓", "hook": "❓ 假设 —— 多读多听，记住 hypothesis", "example": "跟读：\"hypothesis\" 意思是「假设」"},
  {"term": "implement", "phonetic": "/ˈɪm.plɪ.ment/", "level": "L3", "def": "实施", "emoji": "🔧", "hook": "im(进)+ple(满)→ 落实填满 → 实施", "example": "跟读：\"implement\" 意思是「实施」"},
  {"term": "integrate", "phonetic": "/ˈɪn.tɪ.ɡreɪt/", "level": "L3", "def": "整合", "emoji": "🧩", "hook": "in(整)+teg(触)→ 触成一体 → 整合", "example": "跟读：\"integrate\" 意思是「整合」"},
  {"term": "legitimate", "phonetic": "/lɪˈdʒɪt.ɪ.mət/", "level": "L3", "def": "合法的", "emoji": "⚖️", "hook": "⚖️ 合法的 —— 多读多听，记住 legitimate", "example": "跟读：\"legitimate\" 意思是「合法的」"},
  {"term": "manipulate", "phonetic": "/məˈnɪp.jə.leɪt/", "level": "L3", "def": "操纵", "emoji": "🕹️", "hook": "🕹️ 操纵 —— 多读多听，记住 manipulate", "example": "跟读：\"manipulate\" 意思是「操纵」"},
  {"term": "negligible", "phonetic": "/ˈneɡ.lɪ.dʒə.bəl/", "level": "L3", "def": "可忽略的", "emoji": "🤏", "hook": "🤏 可忽略的 —— 多读多听，记住 negligible", "example": "跟读：\"negligible\" 意思是「可忽略的」"},
  {"term": "notion", "phonetic": "/ˈnəʊ.ʃən/", "level": "L3", "def": "概念", "emoji": "💭", "hook": "💭 概念 —— 多读多听，记住 notion", "example": "跟读：\"notion\" 意思是「概念」"},
  {"term": "objective", "phonetic": "/əbˈdʒek.tɪv/", "level": "L3", "def": "客观的", "emoji": "🎯", "hook": "obj(物)+ive→ 看物体而非主观 → 客观的", "example": "跟读：\"objective\" 意思是「客观的」"},
  {"term": "paradox", "phonetic": "/ˈpær.ə.dɒks/", "level": "L3", "def": "悖论", "emoji": "🌀", "hook": "🌀 悖论 —— 多读多听，记住 paradox", "example": "跟读：\"paradox\" 意思是「悖论」"},
  {"term": "persist", "phonetic": "/pəˈsɪst/", "level": "L3", "def": "坚持", "emoji": "💪", "hook": "per(始终)+sist(站)→ 一直站着 → 坚持", "example": "跟读：\"persist\" 意思是「坚持」"},
  {"term": "prevalent", "phonetic": "/ˈprev.əl.ənt/", "level": "L3", "def": "普遍的", "emoji": "🌐", "hook": "🌐 普遍的 —— 多读多听，记住 prevalent", "example": "跟读：\"prevalent\" 意思是「普遍的」"},
  {"term": "rational", "phonetic": "/ˈræʃ.ən.əl/", "level": "L3", "def": "理性的", "emoji": "🧠", "hook": "🧠 理性的 —— 多读多听，记住 rational", "example": "跟读：\"rational\" 意思是「理性的」"},
  {"term": "reinforce", "phonetic": "/ˌriː.ɪnˈfɔːs/", "level": "L3", "def": "加强", "emoji": "🛡️", "hook": "re(再)+in(入)+force→ 再加力 → 加强", "example": "跟读：\"reinforce\" 意思是「加强」"},
  {"term": "subtle", "phonetic": "/ˈsʌt.əl/", "level": "L3", "def": "微妙的", "emoji": "🔍", "hook": "🔍 微妙的 —— 多读多听，记住 subtle", "example": "跟读：\"subtle\" 意思是「微妙的」"},
  {"term": "tremendous", "phonetic": "/trəˈmen.dəs/", "level": "L3", "def": "巨大的", "emoji": "🌟", "hook": "trem(颤抖)→ 大得让人抖 → 巨大的", "example": "跟读：\"tremendous\" 意思是「巨大的」"},
  {"term": "unanimous", "phonetic": "/juˈnæn.ɪ.məs/", "level": "L3", "def": "一致的", "emoji": "🤝", "hook": "🤝 一致的 —— 多读多听，记住 unanimous", "example": "跟读：\"unanimous\" 意思是「一致的」"},
  {"term": "versatile", "phonetic": "/ˈvɜː.sə.taɪl/", "level": "L3", "def": "多才多艺的", "emoji": "🎨", "hook": "🎨 多才多艺的 —— 多读多听，记住 versatile", "example": "跟读：\"versatile\" 意思是「多才多艺的」"},
  {"term": "vivid", "phonetic": "/ˈvɪv.ɪd/", "level": "L3", "def": "生动的", "emoji": "🌈", "hook": "🌈 生动的 —— 多读多听，记住 vivid", "example": "跟读：\"vivid\" 意思是「生动的」"},
  {"term": "abundant", "phonetic": "/əˈbʌn.dənt/", "level": "L3", "def": "丰富的", "emoji": "🌊", "hook": "🌊 丰富的 —— 多读多听，记住 abundant", "example": "跟读：\"abundant\" 意思是「丰富的」"},
  {"term": "accelerate", "phonetic": "/əkˈsel.ə.reɪt/", "level": "L3", "def": "加速", "emoji": "🚀", "hook": "🚀 加速 —— 多读多听，记住 accelerate", "example": "跟读：\"accelerate\" 意思是「加速」"},
  {"term": "advocate", "phonetic": "/ˈæd.və.keɪt/", "level": "L3", "def": "提倡；拥护", "emoji": "📣", "hook": "ad(去)+voc(喊)+ate→ 去喊话支持 → 提倡/拥护", "example": "跟读：\"advocate\" 意思是「提倡；拥护」"},
  {"term": "allocate", "phonetic": "/ˈæl.ə.keɪt/", "level": "L3", "def": "分配", "emoji": "🪙", "hook": "🪙 分配 —— 多读多听，记住 allocate", "example": "跟读：\"allocate\" 意思是「分配」"},
  {"term": "analyze", "phonetic": "/ˈæn.ə.laɪz/", "level": "L3", "def": "分析", "emoji": "🔬", "hook": "ana(分开)+lyze(解)→ 拆解开来研究 → 分析", "example": "跟读：\"analyze\" 意思是「分析」"},
  {"term": "ascend", "phonetic": "/əˈsend/", "level": "L3", "def": "上升", "emoji": "⬆️", "hook": "⬆️ 上升 —— 多读多听，记住 ascend", "example": "跟读：\"ascend\" 意思是「上升」"},
  {"term": "assert", "phonetic": "/əˈsɜːt/", "level": "L3", "def": "断言；坚持", "emoji": "🗣️", "hook": "as(朝)+sert(加入)→ 坚定加入己见 → 断言", "example": "跟读：\"assert\" 意思是「断言；坚持」"},
  {"term": "assume", "phonetic": "/əˈsjuːm/", "level": "L3", "def": "假定", "emoji": "❓", "hook": "❓ 假定 —— 多读多听，记住 assume", "example": "跟读：\"assume\" 意思是「假定」"},
  {"term": "confirm", "phonetic": "/kənˈfɜːm/", "level": "L3", "def": "确认", "emoji": "✅", "hook": "con(共同)+firm(稳)→ 一起稳住 → 确认", "example": "跟读：\"confirm\" 意思是「确认」"},
  {"term": "confront", "phonetic": "/kənˈfrʌnt/", "level": "L3", "def": "面对；对抗", "emoji": "⚔️", "hook": "⚔️ 面对；对抗 —— 多读多听，记住 confront", "example": "跟读：\"confront\" 意思是「面对；对抗」"},
  {"term": "constitute", "phonetic": "/ˈkɒn.stɪ.tjuːt/", "level": "L3", "def": "构成", "emoji": "🧱", "hook": "🧱 构成 —— 多读多听，记住 constitute", "example": "跟读：\"constitute\" 意思是「构成」"},
  {"term": "constrain", "phonetic": "/kənˈstreɪn/", "level": "L3", "def": "限制", "emoji": "⛓️", "hook": "⛓️ 限制 —— 多读多听，记住 constrain", "example": "跟读：\"constrain\" 意思是「限制」"},
  {"term": "contribute", "phonetic": "/kənˈtrɪb.juːt/", "level": "L3", "def": "贡献", "emoji": "🤝", "hook": "con(共同)+tribute(给)→ 共同给予 → 贡献", "example": "跟读：\"contribute\" 意思是「贡献」"},
  {"term": "convince", "phonetic": "/kənˈvɪns/", "level": "L3", "def": "说服", "emoji": "🗣️", "hook": "con(共同)+vince(赢)→ 赢得对方认同 → 说服", "example": "跟读：\"convince\" 意思是「说服」"},
  {"term": "decline", "phonetic": "/dɪˈklaɪn/", "level": "L3", "def": "下降；婉拒", "emoji": "📉", "hook": "de(下)+cline(斜)→ 向下斜 → 下降/婉拒", "example": "跟读：\"decline\" 意思是「下降；婉拒」"},
  {"term": "dedicate", "phonetic": "/ˈded.ɪ.keɪt/", "level": "L3", "def": "奉献", "emoji": "🎯", "hook": "🎯 奉献 —— 多读多听，记住 dedicate", "example": "跟读：\"dedicate\" 意思是「奉献」"},
  {"term": "deliver", "phonetic": "/dɪˈlɪv.ər/", "level": "L3", "def": "递送；发表", "emoji": "📦", "hook": "📦 递送；发表 —— 多读多听，记住 deliver", "example": "跟读：\"deliver\" 意思是「递送；发表」"},
  {"term": "demonstrate", "phonetic": "/ˈdem.ən.streɪt/", "level": "L3", "def": "证明；展示", "emoji": "📊", "hook": "📊 证明；展示 —— 多读多听，记住 demonstrate", "example": "跟读：\"demonstrate\" 意思是「证明；展示」"},
  {"term": "deprive", "phonetic": "/dɪˈpraɪv/", "level": "L3", "def": "剥夺", "emoji": "🚫", "hook": "de(夺)+prive(私)→ 夺走私有 → 剥夺", "example": "跟读：\"deprive\" 意思是「剥夺」"},
  {"term": "derive", "phonetic": "/dɪˈraɪv/", "level": "L3", "def": "源自", "emoji": "🌱", "hook": "de(下)+rive(河)→ 从河流引出 → 源自", "example": "跟读：\"derive\" 意思是「源自」"},
  {"term": "deserve", "phonetic": "/dɪˈzɜːv/", "level": "L3", "def": "应得", "emoji": "🏆", "hook": "🏆 应得 —— 多读多听，记住 deserve", "example": "跟读：\"deserve\" 意思是「应得」"},
  {"term": "deteriorate", "phonetic": "/dɪˈtɪə.ri.ə.reɪt/", "level": "L3", "def": "恶化", "emoji": "📉", "hook": "📉 恶化 —— 多读多听，记住 deteriorate", "example": "跟读：\"deteriorate\" 意思是「恶化」"},
  {"term": "disclose", "phonetic": "/dɪsˈkləʊz/", "level": "L3", "def": "披露", "emoji": "📢", "hook": "dis(不)+close(关)→ 不再关着 → 披露", "example": "跟读：\"disclose\" 意思是「披露」"},
  {"term": "diverse", "phonetic": "/daɪˈvɜːs/", "level": "L3", "def": "多样的", "emoji": "🌈", "hook": "🌈 多样的 —— 多读多听，记住 diverse", "example": "跟读：\"diverse\" 意思是「多样的」"},
  {"term": "dominate", "phonetic": "/ˈdɒm.ɪ.neɪt/", "level": "L3", "def": "支配；主导", "emoji": "👑", "hook": "dom(统治)+ate→ 统治掌控 → 支配/主导", "example": "跟读：\"dominate\" 意思是「支配；主导」"},
  {"term": "eliminate", "phonetic": "/ɪˈlɪm.ɪ.neɪt/", "level": "L3", "def": "消除", "emoji": "❌", "hook": "e(出)+limin(门槛)→ 踢出门外 → 消除", "example": "跟读：\"eliminate\" 意思是「消除」"},
  {"term": "emerge", "phonetic": "/ɪˈmɜːdʒ/", "level": "L3", "def": "出现", "emoji": "🌅", "hook": "e(出)+merge(沉)→ 从沉没中冒出 → 出现", "example": "跟读：\"emerge\" 意思是「出现」"},
  {"term": "enforce", "phonetic": "/ɪnˈfɔːs/", "level": "L3", "def": "执行；强制", "emoji": "⚖️", "hook": "⚖️ 执行；强制 —— 多读多听，记住 enforce", "example": "跟读：\"enforce\" 意思是「执行；强制」"},
  {"term": "engage", "phonetic": "/ɪnˈɡeɪdʒ/", "level": "L3", "def": "参与；从事", "emoji": "🤝", "hook": "🤝 参与；从事 —— 多读多听，记住 engage", "example": "跟读：\"engage\" 意思是「参与；从事」"},
  {"term": "enlighten", "phonetic": "/ɪnˈlaɪ.tən/", "level": "L3", "def": "启发", "emoji": "💡", "hook": "💡 启发 —— 多读多听，记住 enlighten", "example": "跟读：\"enlighten\" 意思是「启发」"},
  {"term": "evolve", "phonetic": "/ɪˈvɒlv/", "level": "L3", "def": "进化；发展", "emoji": "🌱", "hook": "🌱 进化；发展 —— 多读多听，记住 evolve", "example": "跟读：\"evolve\" 意思是「进化；发展」"},
  {"term": "exceed", "phonetic": "/ɪkˈsiːd/", "level": "L3", "def": "超过", "emoji": "⬆️", "hook": "ex(超出)+ceed(走)→ 走过头 → 超过", "example": "跟读：\"exceed\" 意思是「超过」"},
  {"term": "exclude", "phonetic": "/ɪkˈskluːd/", "level": "L3", "def": "排除", "emoji": "🚫", "hook": "ex(外)+clude(关)→ 关在外面 → 排除", "example": "跟读：\"exclude\" 意思是「排除」"},
  {"term": "extract", "phonetic": "/ɪkˈstrækt/", "level": "L3", "def": "提取", "emoji": "🔧", "hook": "🔧 提取 —— 多读多听，记住 extract", "example": "跟读：\"extract\" 意思是「提取」"},
  {"term": "transform", "phonetic": "/trænsˈfɔːm/", "level": "L3", "def": "转变", "emoji": "🔄", "hook": "trans(跨)+form(形)→ 跨界变形 → 转变", "example": "跟读：\"transform\" 意思是「转变」"},
];
