# -*- coding: utf-8 -*-
"""
英语趣学 H5 · 词库生成器 (MVP 演示)
- 单一数据源：本脚本产出 js/words.js（前端原型用）
- 结构对齐将来 Laravel WordSeeder：term/phonetic/level/def/emoji/hook/example
- 后续可改成读取 GSL + CET-4 + CC-CEDICT 生成，字段不变即可直接复用
用法: python tools/gen_words.py  -> 写入 js/words.js
"""
import json, os, sys

# emoji 兜底映射（具体名词自动配图，抽象词给通用图标）
EMOJI_MAP = {
    'apple':'🍎','cat':'🐱','dog':'🐶','book':'📖','water':'💧','sun':'☀️','happy':'😊',
    'red':'🔴','eat':'🍴','go':'🚶','tree':'🌳','fish':'🐟','ambulance':'🚑','bicycle':'🚲',
    'forest':'🌲','secret':'🤫','fragile':'🥚','brilliant':'💡','enormous':'🐘','patient':'🧘',
    'environment':'🌍','consider':'🤔','whisper':'🤫','mountain':'⛰️','ambition':'🚀','circumstance':'🔄',
    'dilemma':'😣','elaborate':'🎨','phenomenon':'🌈','spontaneous':'✨','reluctant':'🛑','tedious':'⏳',
    'vulnerable':'🛡️','alleviate':'🪶','magnificent':'👑','subsequent':'➡️','bird':'🐦','egg':'🥚',
    'milk':'🥛','school':'🏫','teacher':'👩‍🏫','student':'🧑‍🎓','friend':'🤝','family':'👨‍👩‍👧',
    'house':'🏠','car':'🚗','bus':'🚌','train':'🚄','flower':'🌸','grass':'🌿','rain':'🌧️',
    'snow':'❄️','fire':'🔥','star':'⭐','moon':'🌙','night':'🌃','morning':'🌅','food':'🍲',
    'fruit':'🍓','vegetable':'🥦','rice':'🍚','bread':'🍞','meat':'🥩','door':'🚪','window':'🪟',
    'chair':'🪑','table':'🛋️','pen':'🖊️','paper':'📄','phone':'📱','computer':'💻','money':'💰',
    'time':'⏰','day':'📅','week':'🗓️','month':'📆','year':'🎉','weather':'🌤️','wind':'🌬️',
    'cloud':'☁️','light':'💡','dark':'🌑','cold':'🥶','hot':'🥵','warm':'🌡️','clean':'🧼',
    'dirty':'🪣','new':'🆕','old':'👴','big':'🐘','small':'🔹','fast':'💨','slow':'🐢',
    'high':'📏','low':'🔻','open':'🔓','close':'🔒','read':'📖','write':'✍️','listen':'👂',
    'speak':'🗣️','walk':'🚶','run':'🏃','jump':'🦘','swim':'🏊','sleep':'😴','wake':'⏰',
    'work':'💼','play':'🎮','sing':'🎤','dance':'💃','smile':'😄','cry':'😢','love':'❤️',
    'hate':'💢','help':'🆘','learn':'📚','think':'💭','know':'🧠','forget':'🤷','remember':'💾',
    'believe':'🙏','hope':'🌟','dream':'💭','wish':'⭐','peace':'🕊️','war':'⚔️','life':'🌱',
    'death':'💀','city':'🏙️','town':'🏘️','road':'🛣️','bridge':'🌉','river':'🌊','lake':'🏞️',
    'sea':'🌊','beach':'🏖️','island':'🏝️','field':'🌾','farm':'🚜','animal':'🐾','plant':'🌱',
    'spring':'🌸','summer':'☀️','autumn':'🍂','winter':'❄️','air':'💨','earth':'🌍','space':'🚀',
    'science':'🔬','art':'🎨','music':'🎵','sport':'⚽','game':'🎲','movie':'🎬','story':'📖',
    'song':'🎶','color':'🎨','number':'🔢','letter':'✉️','word':'🔤','name':'🏷️','question':'❓',
    'answer':'✅','problem':'⚠️','idea':'💡','plan':'📋','goal':'🎯','success':'🏆','fail':'💥',
    'win':'🥇','lose':'😞','strong':'💪','weak':'🥀','healthy':'💪','sick':'🤒','doctor':'🩺',
    'medicine':'💊','hospital':'🏥','market':'🛒','shop':'🏪','store':'🏬','bank':'🏦','post':'📮',
    'letter_mail':'✉️','gift':'🎁','party':'🎉','festival':'🎊','holiday':'🏖️','travel':'✈️','trip':'🧳',
    'country':'🏳️','world':'🌐','language':'🗣️','culture':'🏛️','history':'📜','future':'🔮','past':'⏳',
    'present':'🎁','child':'🧒','baby':'👶','man':'👨','woman':'👩','people':'👥','crowd':'👥',
}

def emoji_of(term, fallback='📝'):
    return EMOJI_MAP.get(term, fallback)

# 词库（演示用，精选高频 + 趣味联想）
# 字段: term, phonetic, level, def, emoji(None=自动), hook, example
RAW = [
    # ---------------- L1 基础（生活高频） ----------------
    ('apple','/ˈæp.əl/','L1','苹果','🍎','红红的、咬一口脆甜——🍎 就是苹果','I eat an apple every day.'),
    ('cat','/kæt/','L1','猫','🐱','喵星人，会撒娇的小动物','The cat is sleeping.'),
    ('dog','/dɒɡ/','L1','狗','🐶','人类最忠诚的朋友','A dog is a good friend.'),
    ('book','/bʊk/','L1','书','📖','知识的载体，翻开就有故事','I read a book at night.'),
    ('water','/ˈwɔː.tər/','L1','水','💧','生命之源，渴了喝它','Please drink more water.'),
    ('sun','/sʌn/','L1','太阳','☀️','白天发光发热的那颗恒星','The sun is bright.'),
    ('happy','/ˈhæp.i/','L1','开心的','😊','心里甜丝丝的开心','She is happy today.'),
    ('red','/red/','L1','红色','🔴','交通灯里“停”的颜色','I like the red apple.'),
    ('eat','/iːt/','L1','吃','🍴','把食物送进嘴里的动作','Let us eat lunch.'),
    ('go','/ɡəʊ/','L1','去；走','🚶','迈开腿往前走','We go to school.'),
    ('tree','/triː/','L1','树','🌳','大地上的绿色大伞','A bird is in the tree.'),
    ('fish','/fɪʃ/','L1','鱼','🐟','在水里游、不用肺呼吸的动物','The fish swims fast.'),
    ('bird','/bɜːd/','L1','鸟','🐦','长翅膀会飞的小动物','A bird is singing.'),
    ('egg','/eɡ/','L1','蛋','🥚','小鸡破壳前住的地方','I had an egg for breakfast.'),
    ('milk','/mɪlk/','L1','牛奶','🥛','奶牛给的白白营养饮品','Drink milk before bed.'),
    ('school','/skuːl/','L1','学校','🏫','每天去学知识的地方','We go to school by bus.'),
    ('friend','/frend/','L1','朋友','🤝','一起玩、互相帮的人','He is my best friend.'),
    ('house','/haʊs/','L1','房子','🏠','一家人住的小窝','Our house is near the park.'),
    ('car','/kɑːr/','L1','汽车','🚗','四个轮子带你去远方','The red car is fast.'),
    ('flower','/ˈflaʊ.ər/','L1','花','🌸','香香的、蜜蜂爱采它','She picked a flower.'),
    ('rain','/reɪn/','L1','雨','🌧️','天上掉下来的水珠','The rain stopped at noon.'),
    ('star','/stɑːr/','L1','星星','⭐','夜里天上眨眼的亮点','I wish upon a star.'),
    ('sleep','/sliːp/','L1','睡觉','😴','闭眼充电的休息时间','The baby is asleep.'),
    ('run','/rʌn/','L1','跑','🏃','比走快得多的移动','He can run very fast.'),
    # ---- L1 扩充（身体/家庭/食物/颜色/常用词） ----
    ('eye','/aɪ/','L1','眼睛','👁️'),
    ('hand','/hænd/','L1','手','✋'),
    ('foot','/fʊt/','L1','脚','🦶'),
    ('head','/hed/','L1','头','🙆'),
    ('mouth','/maʊθ/','L1','嘴','👄'),
    ('nose','/nəʊz/','L1','鼻子','👃'),
    ('ear','/ɪər/','L1','耳朵','👂'),
    ('face','/feɪs/','L1','脸','😊'),
    ('hair','/heər/','L1','头发','💇'),
    ('mother','/ˈmʌð.ər/','L1','妈妈','👩'),
    ('father','/ˈfɑː.ðər/','L1','爸爸','👨'),
    ('brother','/ˈbrʌð.ər/','L1','兄弟','👦'),
    ('sister','/ˈsɪs.tər/','L1','姐妹','👧'),
    ('boy','/bɔɪ/','L1','男孩','👦'),
    ('girl','/ɡɜːl/','L1','女孩','👧'),
    ('teacher','/ˈtiː.tʃər/','L1','老师','👩‍🏫'),
    ('student','/ˈstjuː.dənt/','L1','学生','🧑‍🎓'),
    ('bag','/bæɡ/','L1','书包','🎒'),
    ('pen','/pen/','L1','钢笔','🖊️'),
    ('tea','/tiː/','L1','茶','🍵'),
    ('coffee','/ˈkɒf.i/','L1','咖啡','☕'),
    ('sugar','/ˈʃʊɡ.ər/','L1','糖','🍬'),
    ('salt','/sɔːlt/','L1','盐','🧂'),
    ('ball','/bɔːl/','L1','球','⚽'),
    ('toy','/tɔɪ/','L1','玩具','🧸'),
    ('blue','/bluː/','L1','蓝色','🔵'),
    ('green','/ɡriːn/','L1','绿色','🟢'),
    ('yellow','/ˈjel.əʊ/','L1','黄色','🟡'),
    ('black','/blæk/','L1','黑色','⚫'),
    ('white','/waɪt/','L1','白色','⚪'),
    ('good','/ɡʊd/','L1','好的','👍'),
    ('bad','/bæd/','L1','坏的','👎'),
    ('today','/təˈdeɪ/','L1','今天','📅'),
    ('tomorrow','/təˈmɒr.əʊ/','L1','明天','📆'),
    ('hello','/həˈləʊ/','L1','你好','👋'),
    ('thanks','/θæŋks/','L1','谢谢','🙏'),
    ('please','/pliːz/','L1','请','🤲'),
    ('sorry','/ˈsɒr.i/','L1','抱歉','😔'),
    ('like','/laɪk/','L1','喜欢','💗'),
    ('want','/wɒnt/','L1','想要','🤲'),
    ('see','/siː/','L1','看见','👀'),
    ('look','/lʊk/','L1','看','👁️'),
    ('hear','/hɪər/','L1','听见','👂'),
    ('sad','/sæd/','L1','伤心的','😢'),
    ('angry','/ˈæŋ.ɡri/','L1','生气的','😠'),
    ('tired','/ˈtaɪ.əd/','L1','累的','😩'),
    # ---- L1 再扩充（日常动词/形容词/常见名词） ----
    ('walk','/wɔːk/','L1','走路','🚶'),
    ('talk','/tɔːk/','L1','说话','💬'),
    ('come','/kʌm/','L1','来','🚶'),
    ('play','/pleɪ/','L1','玩','🎮'),
    ('read','/riːd/','L1','读','📖'),
    ('write','/raɪt/','L1','写','✍️'),
    ('drink','/drɪŋk/','L1','喝','🥤'),
    ('sit','/sɪt/','L1','坐','🪑'),
    ('stand','/stænd/','L1','站','🧍'),
    ('open','/ˈəʊ.pən/','L1','打开','🔓'),
    ('close','/kləʊz/','L1','关上','🔒'),
    ('help','/help/','L1','帮助','🆘'),
    ('give','/ɡɪv/','L1','给','🎁'),
    ('take','/teɪk/','L1','拿','✋'),
    ('make','/meɪk/','L1','做；制作','🛠️'),
    ('find','/faɪnd/','L1','找到','🔎'),
    ('clean','/kliːn/','L1','干净的','🧼'),
    ('dirty','/ˈdɜː.ti/','L1','脏的','🪣'),
    ('hot','/hɒt/','L1','热的','🥵'),
    ('cold','/kəʊld/','L1','冷的','🥶'),
    ('new','/njuː/','L1','新的','🆕'),
    ('old','/əʊld/','L1','旧的；老的','👴'),
    ('big','/bɪɡ/','L1','大的','🐘'),
    ('small','/smɔːl/','L1','小的','🔹'),
    ('food','/fuːd/','L1','食物','🍲'),
    ('money','/ˈmʌn.i/','L1','钱','💰'),
    ('time','/taɪm/','L1','时间','⏰'),
    ('morning','/ˈmɔː.nɪŋ/','L1','早晨','🌅'),
    ('night','/naɪt/','L1','夜晚','🌃'),
    ('week','/wiːk/','L1','星期','🗓️'),
    ('name','/neɪm/','L1','名字','🏷️'),
    ('home','/həʊm/','L1','家','🏡'),
    ('door','/dɔːr/','L1','门','🚪'),
    ('light','/laɪt/','L1','灯；光','💡'),
    ('dark','/dɑːk/','L1','黑暗的','🌑'),
    ('warm','/wɔːm/','L1','温暖的','🌡️'),
    ('love','/lʌv/','L1','爱','❤️'),
    ('work','/wɜːk/','L1','工作','💼'),
    ('year','/jɪər/','L1','年','🎉'),
    ('number','/ˈnʌm.bər/','L1','数字','🔢'),
    ('city','/ˈsɪt.i/','L1','城市','🏙️'),
    ('park','/pɑːk/','L1','公园','🏞️'),
    ('chair','/tʃeər/','L1','椅子','🪑'),
    ('table','/ˈteɪ.bəl/','L1','桌子','🛋️'),
    ('phone','/fəʊn/','L1','电话','📱'),
    ('computer','/kəmˈpjuː.tər/','L1','电脑','💻'),
    ('music','/ˈmjuː.zɪk/','L1','音乐','🎵'),
    ('song','/sɒŋ/','L1','歌曲','🎶'),
    ('game','/ɡeɪm/','L1','游戏','🎲'),
    ('sport','/spɔːt/','L1','运动','⚽'),
    ('swim','/swɪm/','L1','游泳','🏊'),
    ('jump','/dʒʌmp/','L1','跳','🦘'),
    ('sing','/sɪŋ/','L1','唱歌','🎤'),
    ('dance','/dɑːns/','L1','跳舞','💃'),
    ('smile','/smaɪl/','L1','微笑','😄'),
    ('cry','/kraɪ/','L1','哭','😢'),
    ('know','/nəʊ/','L1','知道','🧠'),
    ('think','/θɪŋk/','L1','思考','💭'),
    ('learn','/lɜːn/','L1','学习','📚'),
    ('dream','/driːm/','L1','梦想','💭'),
    ('wish','/wɪʃ/','L1','愿望','⭐'),
    ('hope','/həʊp/','L1','希望','🌟'),
    # ---- L1 再再扩充（衣物/方位/数字/疑问词/常用动词形容词） ----
    ('shirt','/ʃɜːt/','L1','衬衫','👕'),
    ('coat','/kəʊt/','L1','外套','🧥'),
    ('shoe','/ʃuː/','L1','鞋','👟'),
    ('hat','/hæt/','L1','帽子','🎩'),
    ('sock','/sɒk/','L1','袜子','🧦'),
    ('dress','/dres/','L1','连衣裙','👗'),
    ('pants','/pænts/','L1','裤子','👖'),
    ('key','/kiː/','L1','钥匙','🔑'),
    ('bed','/bed/','L1','床','🛏️'),
    ('left','/left/','L1','左边','👈'),
    ('right','/raɪt/','L1','右边','👉'),
    ('up','/ʌp/','L1','向上','⬆️'),
    ('down','/daʊn/','L1','向下','⬇️'),
    ('here','/hɪər/','L1','这里','📍'),
    ('there','/ðeər/','L1','那里','📍'),
    ('one','/wʌn/','L1','一','1️⃣'),
    ('two','/tuː/','L1','二','2️⃣'),
    ('three','/θriː/','L1','三','3️⃣'),
    ('four','/fɔːr/','L1','四','4️⃣'),
    ('five','/faɪv/','L1','五','5️⃣'),
    ('six','/sɪks/','L1','六','6️⃣'),
    ('seven','/ˈsev.ən/','L1','七','7️⃣'),
    ('eight','/eɪt/','L1','八','8️⃣'),
    ('nine','/naɪn/','L1','九','9️⃣'),
    ('ten','/ten/','L1','十','🔟'),
    ('what','/wɒt/','L1','什么','❓'),
    ('where','/weər/','L1','哪里','📍'),
    ('when','/wen/','L1','什么时候','⏰'),
    ('who','/huː/','L1','谁','👤'),
    ('why','/waɪ/','L1','为什么','🤔'),
    ('how','/haʊ/','L1','怎样','💡'),
    ('this','/ðɪs/','L1','这个','👉'),
    ('that','/ðæt/','L1','那个','👉'),
    ('get','/ɡet/','L1','得到','🤲'),
    ('put','/pʊt/','L1','放','📥'),
    ('cut','/kʌt/','L1','切','✂️'),
    ('cook','/kʊk/','L1','烹饪','🍳'),
    ('wash','/wɒʃ/','L1','洗','🧼'),
    ('pay','/peɪ/','L1','支付','💳'),
    ('send','/send/','L1','发送','📤'),
    ('show','/ʃəʊ/','L1','展示','👀'),
    ('tell','/tel/','L1','告诉','🗣️'),
    ('ask','/ɑːsk/','L1','问','❓'),
    ('wait','/weɪt/','L1','等待','⏳'),
    ('leave','/liːv/','L1','离开','🚪'),
    ('arrive','/əˈraɪv/','L1','到达','✈️'),
    ('start','/stɑːt/','L1','开始','🚀'),
    ('stop','/stɒp/','L1','停止','🛑'),
    ('finish','/ˈfɪn.ɪʃ/','L1','完成','✅'),
    ('change','/tʃeɪndʒ/','L1','改变','🔄'),
    ('use','/juːz/','L1','使用','🔧'),
    ('need','/niːd/','L1','需要','🤲'),
    ('feel','/fiːl/','L1','感觉','💗'),
    ('live','/lɪv/','L1','居住','🏠'),
    ('full','/fʊl/','L1','满的','🈵'),
    ('empty','/ˈemp.ti/','L1','空的','🕳️'),
    ('easy','/ˈiː.zi/','L1','容易的','✅'),
    ('hard','/hɑːd/','L1','困难的','🪨'),
    ('cheap','/tʃiːp/','L1','便宜的','💲'),
    ('expensive','/ɪkˈspen.sɪv/','L1','昂贵的','💰'),
    ('quick','/kwɪk/','L1','快的','⚡'),
    ('beautiful','/ˈbjuː.tɪ.fəl/','L1','美丽的','🌸'),
    ('ugly','/ˈʌɡ.li/','L1','丑陋的','👹'),
    ('rich','/rɪtʃ/','L1','富有的','💰'),
    ('poor','/pʊər/','L1','贫穷的','🪙'),
    ('loud','/laʊd/','L1','大声的','🔊'),
    ('quiet','/ˈkwaɪ.ət/','L1','安静的','🤫'),
    ('same','/seɪm/','L1','相同的','🔁'),
    ('different','/ˈdɪf.ər.ənt/','L1','不同的','🔀'),
    ('true','/truː/','L1','真实的','✅'),
    ('false','/fɔːls/','L1','错误的','❌'),
    ('wrong','/rɒŋ/','L1','错的','❌'),
    ('near','/nɪər/','L1','近的','📍'),
    ('far','/fɑːr/','L1','远的','🌍'),
    ('first','/fɜːst/','L1','第一','1️⃣'),
    ('last','/lɑːst/','L1','最后的','🏁'),
    ('next','/nekst/','L1','下一个','➡️'),
    ('many','/ˈmen.i/','L1','许多','🔢'),
    ('few','/fjuː/','L1','很少','🔢'),
    ('some','/sʌm/','L1','一些','🔢'),
    ('all','/ɔːl/','L1','全部','🌐'),
    ('every','/ˈev.ri/','L1','每个','🔢'),
    ('never','/ˈnev.ər/','L1','从不','🚫'),
    ('always','/ˈɔːl.weɪz/','L1','总是','🔁'),
    ('often','/ˈɒf.ən/','L1','经常','🔁'),
    ('usually','/ˈjuː.ʒu.ə.li/','L1','通常','🔁'),

    # ---------------- L2 进阶（场景词） ----------------
    ('ambulance','/ˈæm.bjə.ləns/','L2','救护车','🚑','发音联想“俺不能死”→ 救护车救人命（正确拼写 a-m-b-u-l-a-n-c-e）','Call an ambulance now!'),
    ('bicycle','/ˈbaɪ.sɪ.kl/','L2','自行车','🚲','两个轮子(bi=双)的骑车工具','He rides a bicycle to work.'),
    ('forest','/ˈfɒr.ɪst/','L2','森林','🌲','很多树连成片的大森林','They walked into the forest.'),
    ('secret','/ˈsiː.krət/','L2','秘密','🤫','不能说的悄悄话','It is a secret between us.'),
    ('fragile','/ˈfrædʒ.aɪl/','L2','易碎的','🥚','像鸡蛋一样一碰就碎 → 易碎的','The box is fragile.'),
    ('brilliant','/ˈbrɪl.jənt/','L2','聪明的；耀眼的','💡','像灯泡突然亮了 → 聪明的/耀眼的','She is a brilliant student.'),
    ('enormous','/ɪˈnɔː.məs/','L2','巨大的','🐘','比大象还大 → 巨大的','An enormous whale appeared.'),
    ('patient','/ˈpeɪ.ʃənt/','L2','病人；有耐心的','🧘','生病时等你的是病人；能等的是有耐心的','Be patient, it takes time.'),
    ('environment','/ɪnˈvaɪ.rən.mənt/','L2','环境','🌍','我们周围的“环”境','We must protect the environment.'),
    ('consider','/kənˈsɪd.ər/','L2','考虑','🤔','把事放在心里反复想 → 考虑','Please consider my idea.'),
    ('whisper','/ˈwɪs.pər/','L2','耳语；低声说','🤫','凑近耳朵轻轻说 → 耳语','She whispered to me.'),
    ('mountain','/ˈmaʊn.tən/','L2','山','⛰️','高耸入云的大山','We climbed the mountain.'),
    ('library','/ˈlaɪ.brər.i/','L2','图书馆','📚','摆满书、安静看书的地方','I borrow books from the library.'),
    ('restaurant','/ˈres.trɒnt/','L2','餐厅','🍽️','点菜吃饭的地方','We met at a restaurant.'),
    ('umbrella','/ʌmˈbrel.ə/','L2','雨伞','☂️','下雨撑开挡雨的用具','Take an umbrella, it may rain.'),
    ('vegetable','/ˈvedʒ.tə.bəl/','L2','蔬菜','🥦','绿绿的、健康的食物','Eat more vegetables daily.'),
    ('window','/ˈwɪn.dəʊ/','L2','窗户','🪟','墙上透光能看外面的口','Open the window for fresh air.'),
    ('bridge','/brɪdʒ/','L2','桥','🌉','跨过河的通道','We crossed the bridge.'),
    ('telephone','/ˈtel.ɪ.fəʊn/','L2','电话','📞','用来远距离说话的工具','Call me on the telephone.'),
    ('birthday','/ˈbɜːθ.deɪ/','L2','生日','🎂','你来到这天的纪念日','Happy birthday to you!'),
    ('weather','/ˈweð.ər/','L2','天气','🌤️','今天冷热处理况','The weather is nice today.'),
    ('language','/ˈlæŋ.ɡwɪdʒ/','L2','语言','🗣️','人和人沟通的密码','English is a useful language.'),
    ('travel','/ˈtræv.əl/','L2','旅行','✈️','去远方看世界的动作','We love to travel in summer.'),
    ('healthy','/ˈhel.θi/','L2','健康的','💪','身体棒、少生病 → 健康的','Eat well to stay healthy.'),
    # ---- L2 扩充（医疗/动物/形容词/购物/社会） ----
    ('hospital','/ˈhɒs.pɪ.tl/','L2','医院','🏥'),
    ('nurse','/nɜːs/','L2','护士','👩‍⚕️'),
    ('medicine','/ˈmed.ɪ.sɪn/','L2','药','💊'),
    ('sick','/sɪk/','L2','生病的','🤒'),
    ('sky','/skaɪ/','L2','天空','🌌'),
    ('ice','/aɪs/','L2','冰','🧊'),
    ('horse','/hɔːs/','L2','马','🐴'),
    ('cow','/kaʊ/','L2','奶牛','🐄'),
    ('pig','/pɪɡ/','L2','猪','🐷'),
    ('sheep','/ʃiːp/','L2','羊','🐑'),
    ('rabbit','/ˈræb.ɪt/','L2','兔子','🐰'),
    ('monkey','/ˈmʌŋ.ki/','L2','猴子','🐵'),
    ('tiger','/ˈtaɪ.ɡər/','L2','老虎','🐯'),
    ('lion','/ˈlaɪ.ən/','L2','狮子','🦁'),
    ('bear','/beər/','L2','熊','🐻'),
    ('snake','/sneɪk/','L2','蛇','🐍'),
    ('mouse','/maʊs/','L2','老鼠','🐭'),
    ('long','/lɒŋ/','L2','长的','📏'),
    ('short','/ʃɔːt/','L2','短的','✂️'),
    ('tall','/tɔːl/','L2','高的','📏'),
    ('early','/ˈɜːli/','L2','早的','🌅'),
    ('late','/leɪt/','L2','晚的','🌙'),
    ('young','/jʌŋ/','L2','年轻的','🧒'),
    ('busy','/ˈbɪz.i/','L2','忙碌的','🏃'),
    ('free','/friː/','L2','空闲的','🆓'),
    ('buy','/baɪ/','L2','买','🛒'),
    ('sell','/sel/','L2','卖','💱'),
    ('price','/praɪs/','L2','价格','🏷️'),
    ('market','/ˈmɑː.kɪt/','L2','市场','🛒'),
    ('shop','/ʃɒp/','L2','商店','🏪'),
    ('bank','/bæŋk/','L2','银行','🏦'),
    ('post','/pəʊst/','L2','邮政','📮'),
    ('gift','/ɡɪft/','L2','礼物','🎁'),
    ('party','/ˈpɑː.ti/','L2','聚会','🎉'),
    ('holiday','/ˈhɒl.ə.deɪ/','L2','假期','🏖️'),
    ('trip','/trɪp/','L2','旅行','🧳'),
    ('country','/ˈkʌn.tri/','L2','国家','🏳️'),
    ('world','/wɜːld/','L2','世界','🌐'),
    ('culture','/ˈkʌl.tʃər/','L2','文化','🏛️'),
    ('history','/ˈhɪs.tə.ri/','L2','历史','📜'),
    ('future','/ˈfjuː.tʃər/','L2','未来','🔮'),
    ('past','/pɑːst/','L2','过去','⏳'),
    ('airport','/ˈeə.pɔːt/','L2','机场','✈️'),
    ('station','/ˈsteɪ.ʃən/','L2','车站','🚉'),
    ('ticket','/ˈtɪk.ɪt/','L2','票','🎫'),
    # ---- L2 再扩充（自然/交通/场所/生活/社交） ----
    ('beach','/biːtʃ/','L2','海滩','🏖️'),
    ('island','/ˈaɪ.lənd/','L2','岛屿','🏝️'),
    ('lake','/leɪk/','L2','湖','🏞️'),
    ('river','/ˈrɪv.ər/','L2','河流','🌊'),
    ('road','/rəʊd/','L2','道路','🛣️'),
    ('train','/treɪn/','L2','火车','🚄'),
    ('boat','/bəʊt/','L2','小船','⛵'),
    ('ship','/ʃɪp/','L2','轮船','🚢'),
    ('plane','/pleɪn/','L2','飞机','✈️'),
    ('bus','/bʌs/','L2','公交车','🚌'),
    ('subway','/ˈsʌb.weɪ/','L2','地铁','🚇'),
    ('cinema','/ˈsɪn.ə.mə/','L2','电影院','🎬'),
    ('museum','/mjuˈziː.əm/','L2','博物馆','🏛️'),
    ('theater','/ˈθɪə.tər/','L2','剧院','🎭'),
    ('supermarket','/ˈsuː.pəˌmɑː.kɪt/','L2','超市','🛒'),
    ('hotel','/həʊˈtel/','L2','酒店','🏨'),
    ('garden','/ˈɡɑː.dən/','L2','花园','🌷'),
    ('kitchen','/ˈkɪtʃ.ɪn/','L2','厨房','🍳'),
    ('bedroom','/ˈbed.rʊm/','L2','卧室','🛏️'),
    ('bathroom','/ˈbɑːθ.rʊm/','L2','浴室','🛁'),
    ('office','/ˈɒf.ɪs/','L2','办公室','🏢'),
    ('factory','/ˈfæk.tər.i/','L2','工厂','🏭'),
    ('farm','/fɑːm/','L2','农场','🚜'),
    ('field','/fiːld/','L2','田野','🌾'),
    ('cloud','/klaʊd/','L2','云','☁️'),
    ('wind','/wɪnd/','L2','风','🌬️'),
    ('snow','/snəʊ/','L2','雪','❄️'),
    ('storm','/stɔːm/','L2','暴风雨','⛈️'),
    ('spring','/sprɪŋ/','L2','春天','🌸'),
    ('summer','/ˈsʌm.ər/','L2','夏天','☀️'),
    ('autumn','/ˈɔː.təm/','L2','秋天','🍂'),
    ('winter','/ˈwɪn.tər/','L2','冬天','⛄'),
    ('weekend','/ˈwiːk.end/','L2','周末','🎏'),
    ('festival','/ˈfes.tɪ.vəl/','L2','节日','🎊'),
    ('guest','/ɡest/','L2','客人','🙋'),
    ('neighbor','/ˈneɪ.bər/','L2','邻居','🏘️'),
    ('letter','/ˈlet.ər/','L2','信','✉️'),
    ('email','/ˈiː.meɪl/','L2','电子邮件','📧'),
    ('message','/ˈmes.ɪdʒ/','L2','消息','💬'),
    ('call','/kɔːl/','L2','打电话','📞'),
    ('meet','/miːt/','L2','遇见','🤝'),
    ('invite','/ɪnˈvaɪt/','L2','邀请','✉️'),
    ('celebrate','/ˈsel.ɪ.breɪt/','L2','庆祝','🎉'),
    ('win','/wɪn/','L2','赢','🥇'),
    ('lose','/luːz/','L2','输','😞'),
    ('compete','/kəmˈpiːt/','L2','竞争','🏅'),
    # ---- L2 再再扩充（职业/家庭/学科/学习） ----
    ('doctor','/ˈdɒk.tər/','L2','医生','🩺'),
    ('lawyer','/ˈlɔː.jər/','L2','律师','👨‍⚖️'),
    ('engineer','/ˌen.dʒɪˈnɪər/','L2','工程师','👷'),
    ('artist','/ˈɑː.tɪst/','L2','艺术家','🎨'),
    ('writer','/ˈraɪ.tər/','L2','作家','✍️'),
    ('actor','/ˈæk.tər/','L2','演员','🎭'),
    ('chef','/ʃef/','L2','厨师','👨‍🍳'),
    ('farmer','/ˈfɑː.mər/','L2','农民','🚜'),
    ('policeman','/pəˈliːs.mən/','L2','警察','👮'),
    ('scientist','/ˈsaɪ.ən.tɪst/','L2','科学家','🔬'),
    ('king','/kɪŋ/','L2','国王','👑'),
    ('queen','/kwiːn/','L2','女王','👸'),
    ('parent','/ˈpeə.rənt/','L2','父母','👨‍👩‍👧'),
    ('daughter','/ˈdɔː.tər/','L2','女儿','👧'),
    ('son','/sʌn/','L2','儿子','👦'),
    ('wife','/waɪf/','L2','妻子','👩'),
    ('husband','/ˈhʌz.bənd/','L2','丈夫','👨'),
    ('classmate','/ˈklɑːs.meɪt/','L2','同学','🧑‍🎓'),
    ('stranger','/ˈstreɪn.dʒər/','L2','陌生人','🧑'),
    ('enemy','/ˈen.ə.mi/','L2','敌人','⚔️'),
    ('hero','/ˈhɪə.rəʊ/','L2','英雄','🦸'),
    ('team','/tiːm/','L2','团队','🤝'),
    ('group','/ɡruːp/','L2','小组','👥'),
    ('member','/ˈmem.bər/','L2','成员','👤'),
    ('leader','/ˈliː.dər/','L2','领导','🧑‍💼'),
    ('company','/ˈkʌmp.ə.ni/','L2','公司','🏢'),
    ('government','/ˈɡʌv.ən.mənt/','L2','政府','🏛️'),
    ('university','/ˌjuː.nɪˈvɜː.sə.ti/','L2','大学','🎓'),
    ('college','/ˈkɒl.ɪdʒ/','L2','学院','🏫'),
    ('class','/klɑːs/','L2','班级','🏫'),
    ('lesson','/ˈles.ən/','L2','课','📚'),
    ('subject','/ˈsʌb.dʒekt/','L2','科目','📖'),
    ('math','/mæθ/','L2','数学','➗'),
    ('physics','/ˈfɪz.ɪks/','L2','物理','⚛️'),
    ('chemistry','/ˈkem.ɪ.stri/','L2','化学','🧪'),
    ('biology','/baɪˈɒl.ə.dʒi/','L2','生物','🧬'),
    ('geography','/dʒiˈɒɡ.rə.fi/','L2','地理','🗺️'),
    ('grammar','/ˈɡræm.ər/','L2','语法','📐'),
    ('test','/test/','L2','考试','📝'),
    ('exam','/ɪɡˈzæm/','L2','测验','📝'),
    ('score','/skɔːr/','L2','分数','🔢'),
    ('practice','/ˈpræk.tɪs/','L2','练习','🏋️'),
    ('improve','/ɪmˈpruːv/','L2','提高','⬆️'),
    ('progress','/ˈprəʊ.ɡres/','L2','进步','📈'),
    ('skill','/skɪl/','L2','技能','🛠️'),
    ('hobby','/ˈhɒb.i/','L2','爱好','🎨'),
    ('reason','/ˈriː.zən/','L2','原因','💭'),
    ('result','/rɪˈzʌlt/','L2','结果','📊'),
    ('choice','/tʃɔɪs/','L2','选择','🔘'),
    ('method','/ˈmeθ.əd/','L2','方法','🛠️'),

    # ---------------- L3 高阶（考试核心） ----------------
    ('ambition','/æmˈbɪʃ.ən/','L3','野心；抱负','🚀','心里有火想往上冲 → 野心/抱负','His ambition is to be a pilot.'),
    ('circumstance','/ˈsɜː.kəm.stɑːns/','L3','环境；情况','🔄','站在圆环(circle)里做事 → 周围的情况','Under the circumstance, we waited.'),
    ('dilemma','/dɪˈlem.ə/','L3','困境；两难','😣','两难(di=双)的困境','He faced a real dilemma.'),
    ('elaborate','/ɪˈlæb.ər.ət/','L3','精心制作的；详尽的','🎨','往外(e-)劳动(labor)打磨 → 精心制作的','She made an elaborate plan.'),
    ('phenomenon','/fəˈnɒm.ɪ.nən/','L3','现象','🌈','天上出现的奇景 → 现象','The rainbow is a natural phenomenon.'),
    ('spontaneous','/spɒnˈteɪ.ni.əs/','L3','自发的','✨','自己(spon)冒出来的 → 自发的','A spontaneous trip sounds fun.'),
    ('reluctant','/rɪˈlʌk.tənt/','L3','不情愿的','🛑','不肯往前 → 不情愿的','He was reluctant to leave.'),
    ('tedious','/ˈtiː.di.əs/','L3','冗长乏味的','⏳','时间长到让人烦 → 冗长乏味的','The meeting was tedious.'),
    ('vulnerable','/ˈvʌl.nər.ə.bəl/','L3','脆弱的','🛡️','盾牌挡不住 → 脆弱的','Children are vulnerable.'),
    ('alleviate','/əˈliː.vi.eɪt/','L3','缓解；减轻','🪶','把重量(lev)减轻 → 缓解','This medicine alleviates pain.'),
    ('magnificent','/mæɡˈnɪf.ɪ.sənt/','L3','宏伟的；壮丽的','👑','配得上加冕的 → 宏伟的/壮丽的','What a magnificent view!'),
    ('subsequent','/ˈsʌb.sɪ.kwənt/','L3','随后的','➡️','跟在(sub-)后面的 → 随后的','Subsequent events proved him right.'),
    ('inevitable','/ɪnˈev.ɪ.tə.bəl/','L3','不可避免的','⛓️','躲不掉的 → 必然发生的','Mistakes are inevitable sometimes.'),
    ('comprehensive','/ˌkɒm.prɪˈhen.sɪv/','L3','全面的；综合的','🧩','全抓(com-)理解 → 全面的','We need a comprehensive plan.'),
    ('scrutinize','/ˈskruː.tɪ.naɪz/','L3','仔细审查','🔍','用放大镜看 → 细查','Scrutinize the contract carefully.'),
    ('resilient','/rɪˈzɪl.i.ənt/','L3','有韧性的','🌱','压弯还能弹回 → 坚韧的','She is resilient under pressure.'),
    ('profound','/prəˈfaʊnd/','L3','深刻的','🌊','像深海一样深 → 深刻的','A profound question worth thinking.'),
    ('diligent','/ˈdɪl.ɪ.dʒənt/','L3','勤勉的','📖','努力不偷懒 → 勤奋的','A diligent student studies daily.'),
    ('candidate','/ˈkæn.dɪ.dət/','L3','候选人','🗳️','等着被选的人 → 候选人','He is a candidate for the job.'),
    ('negotiate','/nɪˈɡəʊ.ʃi.eɪt/','L3','谈判；协商','🤝','双方来回谈条件 → 协商','They negotiate a better price.'),
    # ---- L3 扩充（考试核心高频） ----
    ('abandon','/əˈbæn.dən/','L3','放弃','🚪'),
    ('accumulate','/əˈkjuː.mjə.leɪt/','L3','积累','📚'),
    ('adequate','/ˈæd.ɪ.kwət/','L3','足够的','✅'),
    ('anticipate','/ænˈtɪs.ɪ.peɪt/','L3','预期','🔮'),
    ('apparent','/əˈpær.ənt/','L3','明显的','👀'),
    ('approximate','/əˈprɒk.sɪ.mət/','L3','近似的','📏'),
    ('arbitrary','/ˈɑː.bɪ.trər.i/','L3','武断的','🎲'),
    ('assess','/əˈses/','L3','评估','⚖️'),
    ('attribute','/əˈtrɪb.juːt/','L3','归因于','🔗'),
    ('authentic','/ɔːˈθen.tɪk/','L3','真实的','✅'),
    ('bias','/ˈbaɪ.əs/','L3','偏见','⚖️'),
    ('coherent','/kəʊˈhɪə.rənt/','L3','连贯的','🔗'),
    ('comply','/kəmˈplaɪ/','L3','遵守','📋'),
    ('conceive','/kənˈsiːv/','L3','构想','💡'),
    ('consequence','/ˈkɒn.sɪ.kwəns/','L3','后果','⛓️'),
    ('consolidate','/kənˈsɒl.ɪ.deɪt/','L3','巩固','🧱'),
    ('contemporary','/kənˈtem.pər.ər.i/','L3','当代的','🕰️'),
    ('contradict','/ˌkɒn.trəˈdɪkt/','L3','矛盾','⚡'),
    ('deliberate','/dɪˈlɪb.ər.ət/','L3','故意的','🎯'),
    ('diminish','/dɪˈmɪn.ɪʃ/','L3','减少','📉'),
    ('distinct','/dɪˈstɪŋkt/','L3','明显的','🔍'),
    ('elegant','/ˈel.ɪ.ɡənt/','L3','优雅的','💃'),
    ('emphasize','/ˈem.fə.saɪz/','L3','强调','📣'),
    ('enhance','/ɪnˈhɑːns/','L3','提升','⬆️'),
    ('explicit','/ɪkˈsplɪs.ɪt/','L3','明确的','🗣️'),
    ('feasible','/ˈfiː.zə.bəl/','L3','可行的','✅'),
    ('fluctuate','/ˈflʌk.tʃu.eɪt/','L3','波动','📈'),
    ('formulate','/ˈfɔː.mju.leɪt/','L3','制定','📝'),
    ('fundamental','/ˌfʌn.dəˈmen.təl/','L3','基本的','🏗️'),
    ('hypothesis','/haɪˈpɒθ.ə.sɪs/','L3','假设','❓'),
    ('implement','/ˈɪm.plɪ.ment/','L3','实施','🔧'),
    ('integrate','/ˈɪn.tɪ.ɡreɪt/','L3','整合','🧩'),
    ('legitimate','/lɪˈdʒɪt.ɪ.mət/','L3','合法的','⚖️'),
    ('manipulate','/məˈnɪp.jə.leɪt/','L3','操纵','🕹️'),
    ('negligible','/ˈneɡ.lɪ.dʒə.bəl/','L3','可忽略的','🤏'),
    ('notion','/ˈnəʊ.ʃən/','L3','概念','💭'),
    ('objective','/əbˈdʒek.tɪv/','L3','客观的','🎯'),
    ('paradox','/ˈpær.ə.dɒks/','L3','悖论','🌀'),
    ('persist','/pəˈsɪst/','L3','坚持','💪'),
    ('prevalent','/ˈprev.əl.ənt/','L3','普遍的','🌐'),
    ('rational','/ˈræʃ.ən.əl/','L3','理性的','🧠'),
    ('reinforce','/ˌriː.ɪnˈfɔːs/','L3','加强','🛡️'),
    ('subtle','/ˈsʌt.əl/','L3','微妙的','🔍'),
    ('tremendous','/trəˈmen.dəs/','L3','巨大的','🌟'),
    ('unanimous','/juˈnæn.ɪ.məs/','L3','一致的','🤝'),
    ('versatile','/ˈvɜː.sə.taɪl/','L3','多才多艺的','🎨'),
    ('vivid','/ˈvɪv.ɪd/','L3','生动的','🌈'),
    # ---- L3 再扩充（考试核心高频） ----
    ('abundant','/əˈbʌn.dənt/','L3','丰富的','🌊'),
    ('accelerate','/əkˈsel.ə.reɪt/','L3','加速','🚀'),
    ('advocate','/ˈæd.və.keɪt/','L3','提倡；拥护','📣'),
    ('allocate','/ˈæl.ə.keɪt/','L3','分配','🪙'),
    ('analyze','/ˈæn.ə.laɪz/','L3','分析','🔬'),
    ('ascend','/əˈsend/','L3','上升','⬆️'),
    ('assert','/əˈsɜːt/','L3','断言；坚持','🗣️'),
    ('assume','/əˈsjuːm/','L3','假定','❓'),
    ('confirm','/kənˈfɜːm/','L3','确认','✅'),
    ('confront','/kənˈfrʌnt/','L3','面对；对抗','⚔️'),
    ('constitute','/ˈkɒn.stɪ.tjuːt/','L3','构成','🧱'),
    ('constrain','/kənˈstreɪn/','L3','限制','⛓️'),
    ('contribute','/kənˈtrɪb.juːt/','L3','贡献','🤝'),
    ('convince','/kənˈvɪns/','L3','说服','🗣️'),
    ('decline','/dɪˈklaɪn/','L3','下降；婉拒','📉'),
    ('dedicate','/ˈded.ɪ.keɪt/','L3','奉献','🎯'),
    ('deliver','/dɪˈlɪv.ər/','L3','递送；发表','📦'),
    ('demonstrate','/ˈdem.ən.streɪt/','L3','证明；展示','📊'),
    ('deprive','/dɪˈpraɪv/','L3','剥夺','🚫'),
    ('derive','/dɪˈraɪv/','L3','源自','🌱'),
    ('deserve','/dɪˈzɜːv/','L3','应得','🏆'),
    ('deteriorate','/dɪˈtɪə.ri.ə.reɪt/','L3','恶化','📉'),
    ('disclose','/dɪsˈkləʊz/','L3','披露','📢'),
    ('diverse','/daɪˈvɜːs/','L3','多样的','🌈'),
    ('dominate','/ˈdɒm.ɪ.neɪt/','L3','支配；主导','👑'),
    ('eliminate','/ɪˈlɪm.ɪ.neɪt/','L3','消除','❌'),
    ('emerge','/ɪˈmɜːdʒ/','L3','出现','🌅'),
    ('enforce','/ɪnˈfɔːs/','L3','执行；强制','⚖️'),
    ('engage','/ɪnˈɡeɪdʒ/','L3','参与；从事','🤝'),
    ('enlighten','/ɪnˈlaɪ.tən/','L3','启发','💡'),
    ('evolve','/ɪˈvɒlv/','L3','进化；发展','🌱'),
    ('exceed','/ɪkˈsiːd/','L3','超过','⬆️'),
    ('exclude','/ɪkˈskluːd/','L3','排除','🚫'),
    ('extract','/ɪkˈstrækt/','L3','提取','🔧'),
    ('transform','/trænsˈfɔːm/','L3','转变','🔄'),
    # ---- L3 再再扩充（考试核心高频） ----
    ('absorb','/əbˈzɔːb/','L3','吸收','🧽'),
    ('abstract','/ˈæb.strækt/','L3','抽象的','🔺'),
    ('accomplish','/əˈkʌm.plɪʃ/','L3','完成','✅'),
    ('accurate','/ˈæk.jə.rət/','L3','准确的','🎯'),
    ('acquire','/əˈkwaɪər/','L3','获得','🤝'),
    ('adapt','/əˈdæpt/','L3','适应','🔄'),
    ('adjust','/əˈdʒʌst/','L3','调整','🔧'),
    ('admire','/ədˈmaɪər/','L3','钦佩','👏'),
    ('adopt','/əˈdɒpt/','L3','采纳','🤝'),
    ('affect','/əˈfekt/','L3','影响','💥'),
    ('amend','/əˈmend/','L3','修订','✏️'),
    ('appreciate','/əˈpriː.ʃi.eɪt/','L3','欣赏','🌟'),
    ('articulate','/ɑːˈtɪk.jə.lət/','L3','清晰表达','🗣️'),
    ('attain','/əˈteɪn/','L3','达到','🎯'),
    ('authorize','/ˈɔː.θər.aɪz/','L3','授权','✅'),
    ('automatic','/ˌɔː.təˈmæt.ɪk/','L3','自动的','🤖'),
    ('avoid','/əˈvɔɪd/','L3','避免','🚫'),
    ('boost','/buːst/','L3','提升','⬆️'),
    ('capable','/ˈkeɪ.pə.bəl/','L3','有能力的','💪'),
    ('capture','/ˈkæp.tʃər/','L3','捕获','📸'),
    ('cease','/siːs/','L3','停止','🛑'),
    ('challenge','/ˈtʃæl.ɪndʒ/','L3','挑战','⚔️'),
    ('cite','/saɪt/','L3','引用','📑'),
    ('clarify','/ˈklær.ɪ.faɪ/','L3','澄清','💡'),
    ('coincide','/ˌkəʊ.ɪnˈsaɪd/','L3','重合','🔄'),
    ('collapse','/kəˈlæps/','L3','崩溃','💥'),
    ('commence','/kəˈmens/','L3','开始','🚀'),
    ('commit','/kəˈmɪt/','L3','承诺','🤝'),
    ('compose','/kəmˈpəʊz/','L3','组成','🎼'),
    ('conclude','/kənˈkluːd/','L3','总结','🔚'),
    ('conduct','/kənˈdʌkt/','L3','引导','🧭'),
    ('conserve','/kənˈsɜːv/','L3','保存','🌿'),
    ('consist','/kənˈsɪst/','L3','由…组成','🧱'),
    ('construct','/kənˈstrʌkt/','L3','建设','🏗️'),
    ('consume','/kənˈsjuːm/','L3','消耗','🔥'),
    ('contain','/kənˈteɪn/','L3','包含','📦'),
    ('convey','/kənˈveɪ/','L3','传达','📨'),
    ('cope','/kəʊp/','L3','应对','🛡️'),
    ('crucial','/ˈkruː.ʃəl/','L3','关键的','🔑'),
    ('cultivate','/ˈkʌl.tɪ.veɪt/','L3','培养','🌱'),
    ('deduce','/dɪˈdjuːs/','L3','推断','🔍'),
    ('defend','/dɪˈfend/','L3','辩护','🛡️'),
    ('define','/dɪˈfaɪn/','L3','定义','📐'),
    ('denote','/dɪˈnəʊt/','L3','表示','🔤'),
    ('depict','/dɪˈpɪkt/','L3','描绘','🎨'),
    ('designate','/ˈdez.ɪɡ.neɪt/','L3','指定','🎯'),
    ('devote','/dɪˈvəʊt/','L3','奉献','🎯'),
    ('discriminate','/dɪˈskrɪm.ɪ.neɪt/','L3','区分','⚖️'),
    ('display','/dɪˈspleɪ/','L3','展示','🖥️'),
    ('distribute','/dɪˈstrɪb.juːt/','L3','分发','📦'),
    ('doubt','/daʊt/','L3','怀疑','❓'),
    ('durable','/ˈdjʊə.rə.bəl/','L3','持久的','🧱'),
    ('empirical','/ɪmˈpɪr.ɪ.kəl/','L3','经验的','🔬'),
    ('enable','/ɪˈneɪ.bəl/','L3','使能够','✅'),
    ('encounter','/ɪnˈkaʊn.tər/','L3','遭遇','⚔️'),
    ('endure','/ɪnˈdjʊər/','L3','忍受','🛡️'),
    ('ensure','/ɪnˈʃʊər/','L3','确保','🛡️'),
    ('exemplify','/ɪɡˈzem.plɪ.faɪ/','L3','举例','📝'),
    ('exhibit','/ɪɡˈzɪb.ɪt/','L3','展览','🖼️'),
    ('expand','/ɪkˈspænd/','L3','扩张','📈'),
    ('expect','/ɪkˈspekt/','L3','期望','⭐'),
    ('expert','/ˈek.spɜːt/','L3','专家','🧠'),
    ('explore','/ɪkˈsplɔːr/','L3','探索','🧭'),
    ('extend','/ɪkˈstend/','L3','延伸','➡️'),
    ('facilitate','/fəˈsɪl.ɪ.teɪt/','L3','促进','🤝'),
    ('forbid','/fəˈbɪd/','L3','禁止','🚫'),
    ('forge','/fɔːdʒ/','L3','锻造','🔨'),
    ('foster','/ˈfɒs.tər/','L3','培养','🌱'),
    ('fulfill','/fʊlˈfɪl/','L3','实现','✅'),
    ('generate','/ˈdʒen.ə.reɪt/','L3','产生','⚡'),
    ('genuine','/ˈdʒen.ju.ɪn/','L3','真正的','✅'),
    ('govern','/ˈɡʌv.ən/','L3','统治','🏛️'),
    ('guarantee','/ˌɡær.ənˈtiː/','L3','保证','🛡️'),
    ('observe','/əbˈzɜːv/','L3','观察','👀'),
    ('obtain','/əbˈteɪn/','L3','获得','🤝'),
    ('occupy','/ˈɒk.jə.paɪ/','L3','占据','📦'),
    ('occur','/əˈkɜːr/','L3','发生','💥'),
    ('oppose','/əˈpəʊz/','L3','反对','⚔️'),
    ('overcome','/ˌəʊ.vəˈkʌm/','L3','克服','🛡️'),
    ('perceive','/pəˈsiːv/','L3','感知','👁️'),
    ('predict','/prɪˈdɪkt/','L3','预测','🔮'),
    ('pursue','/pəˈsjuː/','L3','追求','🎯'),
    ('recover','/rɪˈkʌv.ər/','L3','恢复','🔄'),
    ('reflect','/rɪˈflekt/','L3','反映','🪞'),
    ('reject','/rɪˈdʒekt/','L3','拒绝','🚫'),
    ('release','/rɪˈliːs/','L3','释放','🕊️'),
    ('relieve','/rɪˈliːv/','L3','缓解','🪶'),
    ('remain','/rɪˈmeɪn/','L3','保持','➡️'),
    ('remove','/rɪˈmuːv/','L3','移除','🗑️'),
    ('replace','/rɪˈpleɪs/','L3','替换','🔄'),
    ('restore','/rɪˈstɔːr/','L3','恢复','🔄'),
    ('retain','/rɪˈteɪn/','L3','保留','📦'),
    ('reveal','/rɪˈviːl/','L3','揭示','🔍'),
    ('revise','/rɪˈvaɪz/','L3','修订','✏️'),
    ('secure','/sɪˈkjʊər/','L3','安全的','🔒'),
    ('seek','/siːk/','L3','寻求','🔍'),
    ('select','/sɪˈlekt/','L3','选择','🔘'),
    ('settle','/ˈset.əl/','L3','解决','⚖️'),
    ('signify','/ˈsɪɡ.nɪ.faɪ/','L3','意味着','🔤'),
    ('solve','/sɒlv/','L3','解决','💡'),
    ('specify','/ˈspes.ɪ.faɪ/','L3','指明','📌'),
    ('stimulate','/ˈstɪm.jə.leɪt/','L3','刺激','⚡'),
    ('submit','/səbˈmɪt/','L3','提交','📨'),
    ('suffice','/səˈfaɪs/','L3','足够','✅'),
    ('sustain','/səˈsteɪn/','L3','维持','🌿'),
    ('trace','/treɪs/','L3','追踪','🔍'),
    ('transfer','/trænsˈfɜːr/','L3','转移','🔄'),
    ('transmit','/trænsˈmɪt/','L3','传播','📡'),
    ('undertake','/ˌʌn.dəˈteɪk/','L3','承担','🤝'),
    ('update','/ʌpˈdeɪt/','L3','更新','🔄'),
    ('utilize','/ˈjuː.tɪ.laɪz/','L3','利用','⚙️'),
    ('verify','/ˈver.ɪ.faɪ/','L3','核实','✅'),
    ('violate','/ˈvaɪ.ə.leɪt/','L3','违反','⚖️'),
]

# 强记忆点词的趣味钩子（与正确拼写视觉分离，绝不诱导错误拼写）
HOOK_MAP = {
    'ambulance':'发音联想“俺不能死”→ 救护车救人命（正确拼写 a-m-b-u-l-a-n-c-e）',
    'bicycle':'两个轮子(bi=双)的骑车工具',
    'fragile':'像鸡蛋一样一碰就碎 → 易碎的',
    'brilliant':'像灯泡突然亮了 → 聪明的/耀眼的',
    'enormous':'比大象还大 → 巨大的',
    'environment':'我们周围的“环”境',
    'circumstance':'站在圆环(circle)里做事 → 周围的情况',
    'dilemma':'两难(di=双)的困境',
    'elaborate':'往外(e-)劳动(labor)打磨 → 精心制作的',
    'spontaneous':'自己(spon)冒出来的 → 自发的',
    'reluctant':'不肯往前 → 不情愿的',
    'tedious':'时间长到让人烦 → 冗长乏味的',
    'vulnerable':'盾牌挡不住 → 脆弱的',
    'alleviate':'把重量(lev)减轻 → 缓解',
    'magnificent':'配得上加冕的 → 宏伟的/壮丽的',
    'subsequent':'跟在(sub-)后面的 → 随后的',
    'inevitable':'躲不掉的 → 必然发生的',
    'comprehensive':'全抓(com-)理解 → 全面的',
    'scrutinize':'用放大镜看 → 细查',
    'resilient':'压弯还能弹回 → 坚韧的',
    'profound':'像深海一样深 → 深刻的',
    'diligent':'努力不偷懒 → 勤奋的',
    'candidate':'等着被选的人 → 候选人',
    'negotiate':'双方来回谈条件 → 协商',
    'patient':'生病时等你的是病人；能等的是有耐心的',
    'consider':'把事放在心里反复想 → 考虑',
    'whisper':'凑近耳朵轻轻说 → 耳语',
    'secret':'不能说的悄悄话',
    'abandon':'a(离开)+band(绑)→ 解开束缚 → 放弃',
    'accumulate':'积累(ac-)到一起 → 越攒越多',
    'adequate':'ad(去)+equ(相等)→ 刚好够 → 足够的',
    'anticipate':'提前(after)抓(cap)住 → 预期',
    'assess':'坐下来细看 → 评估',
    'attribute':'把原因(a-)归给(tribute) → 归因于',
    'comply':'com(一起)+ply(折)→ 折服照做 → 遵守',
    'consequence':'跟着(con-)结果(sequence)→ 后果',
    'consolidate':'一起(con-)变 solid → 巩固',
    'contradict':'contra(反)+dict(说)→ 反着说 → 矛盾',
    'deliberate':'de(下)+liber(秤)→ 掂量后 → 故意的',
    'diminish':'一点点(min)变小 → 减少',
    'emphasize':'em(使)+phase(显)→ 使其显眼 → 强调',
    'enhance':'en(使)+hance(高)→ 抬高 → 提升',
    'implement':'im(进)+ple(满)→ 落实填满 → 实施',
    'integrate':'in(整)+teg(触)→ 触成一体 → 整合',
    'objective':'obj(物)+ive→ 看物体而非主观 → 客观的',
    'persist':'per(始终)+sist(站)→ 一直站着 → 坚持',
    'reinforce':'re(再)+in(入)+force→ 再加力 → 加强',
    'tremendous':'trem(颤抖)→ 大得让人抖 → 巨大的',
    # L3 再扩充词的趣味钩子
    'advocate':'ad(去)+voc(喊)+ate→ 去喊话支持 → 提倡/拥护',
    'analyze':'ana(分开)+lyze(解)→ 拆解开来研究 → 分析',
    'convince':'con(共同)+vince(赢)→ 赢得对方认同 → 说服',
    'derive':'de(下)+rive(河)→ 从河流引出 → 源自',
    'dominate':'dom(统治)+ate→ 统治掌控 → 支配/主导',
    'emerge':'e(出)+merge(沉)→ 从沉没中冒出 → 出现',
    'exceed':'ex(超出)+ceed(走)→ 走过头 → 超过',
    'exclude':'ex(外)+clude(关)→ 关在外面 → 排除',
    'eliminate':'e(出)+limin(门槛)→ 踢出门外 → 消除',
    'contribute':'con(共同)+tribute(给)→ 共同给予 → 贡献',
    'decline':'de(下)+cline(斜)→ 向下斜 → 下降/婉拒',
    'deprive':'de(夺)+prive(私)→ 夺走私有 → 剥夺',
    'disclose':'dis(不)+close(关)→ 不再关着 → 披露',
    'transform':'trans(跨)+form(形)→ 跨界变形 → 转变',
    'assert':'as(朝)+sert(加入)→ 坚定加入己见 → 断言',
    'confirm':'con(共同)+firm(稳)→ 一起稳住 → 确认',
    # L3 再再扩充词的趣味钩子
    'absorb':'ab(离开)+sorb(吸)→ 吸走 → 吸收',
    'abstract':'abs(离开)+tract(拉)→ 抽离出来 → 抽象的',
    'accomplish':'ac(去)+com(全)+plish(满)→ 圆满做成 → 完成',
    'accurate':'ac(去)+cur(关心)+ate→ 做到位 → 准确的',
    'acquire':'ac(去)+quir(求)→ 求得 → 获得',
    'adapt':'ad(去)+apt(适合)→ 变得适合 → 适应',
    'adjust':'ad(去)+just(正)→ 调正 → 调整',
    'adopt':'ad(去)+opt(选)→ 选来用 → 采纳',
    'affect':'af(去)+fect(做)→ 施加作用 → 影响',
    'amend':'a(去)+mend(修)→ 修订',
    'appreciate':'ap(去)+preci(价值)+ate→ 看出价值 → 欣赏',
    'attain':'at(去)+tain(握)→ 握住 → 达到',
    'authorize':'author(权威)+ize→ 授权',
    'avoid':'a(离开)+void(空)→ 躲开 → 避免',
    'capable':'cap(抓)+able→ 抓得住 → 有能力的',
    'capture':'cap(抓)+ture→ 抓取 → 捕获',
    'clarify':'clar(清楚)+ify→ 弄清 → 澄清',
    'coincide':'co(共同)+in(入)+cide(落)→ 落到一起 → 重合',
    'collapse':'col(共同)+lapse(滑)→ 一起滑倒 → 崩溃',
    'commit':'com(共同)+mit(送)→ 托付 → 承诺',
    'compose':'com(共同)+pose(放)→ 放到一起 → 组成',
    'conclude':'con(共同)+clude(关)→ 收尾 → 总结',
    'conduct':'con(共同)+duct(引)→ 引导',
    'conserve':'con(共同)+serve(保)→ 保存',
    'consist':'con(共同)+sist(站)→ 站在一起 → 由…组成',
    'construct':'con(共同)+struct(建)→ 建设',
    'consume':'con(共同)+sume(拿)→ 拿光 → 消耗',
    'contain':'con(共同)+tain(握)→ 握住 → 包含',
    'convey':'con(共同)+vey(路)→ 上路送达 → 传达',
    'crucial':'cruc(十字)+ial→ 十字路口般关键 → 关键的',
    'cultivate':'cult(耕)+ivate→ 耕作培养 → 培养',
    'deduce':'de(下)+duce(引)→ 引出来 → 推断',
    'defend':'de(下)+fend(击)→ 挡开 → 辩护',
    'define':'de(下)+fine(终)→ 定下边界 → 定义',
    'denote':'de(下)+note(记)→ 记下来表示 → 表示',
    'depict':'de(下)+pict(画)→ 画下 → 描绘',
    'designate':'de(下)+sign(标)+ate→ 标出 → 指定',
    'devote':'de(下)+vote(誓)→ 立誓 → 奉献',
    'discriminate':'dis(分)+crimin(辨)+ate→ 分辨 → 区分',
    'display':'dis(分)+play(展)→ 展开 → 展示',
    'distribute':'dis(分)+tribute(给)→ 分发给 → 分发',
    'durable':'dur(久)+able→ 耐久的',
    'empirical':'em(在)+piri(经验)+cal→ 凭经验的',
    'enable':'en(使)+able→ 使能够',
    'encounter':'en(使)+counter(对抗)→ 遭遇',
    'endure':'en(使)+dure(久)→ 持久忍受',
    'ensure':'en(使)+sure(稳)→ 确保',
    'exemplify':'ex(出)+empl(例)+ify→ 举例',
    'exhibit':'ex(出)+hibit(持)→ 拿出展示 → 展览',
    'expand':'ex(出)+pand(伸)→ 伸展开 → 扩张',
    'expect':'ex(出)+pect(看)→ 向外看 → 期望',
    'expert':'ex(出)+pert(试)→ 试出来的 → 专家',
    'extend':'ex(出)+tend(伸)→ 延伸',
    'facilitate':'fac(做)+ilitate→ 使易做 → 促进',
    'forbid':'for(离)+bid(命令)→ 命令不许 → 禁止',
    'fulfill':'full(满)+fill→ 填满实现 → 实现',
    'generate':'gen(生)+erate→ 产生',
    'genuine':'gen(生)+uine→ 天生的 → 真正的',
    'observe':'ob(向)+serve(保)→ 盯着看 → 观察',
    'obtain':'ob(向)+tain(握)→ 握住 → 获得',
    'occupy':'oc(向)+cupy(占)→ 占据',
    'occur':'oc(向)+cur(跑)→ 跑来 → 发生',
    'oppose':'op(反)+pose(放)→ 反着放 → 反对',
    'overcome':'over(过)+come(来)→ 跨过 → 克服',
    'perceive':'per(完全)+ceive(抓)→ 抓全 → 感知',
    'predict':'pre(前)+dict(说)→ 事前说 → 预测',
    'pursue':'pur(前)+sue(跟)→ 追 → 追求',
    'recover':'re(再)+cover(盖)→ 重新盖好 → 恢复',
    'reflect':'re(回)+flect(折)→ 折回 → 反映',
    'reject':'re(回)+ject(扔)→ 扔回 → 拒绝',
    'release':'re(回)+lease(松)→ 松开 → 释放',
    'relieve':'re(回)+lieve(轻)→ 减轻 → 缓解',
    'remain':'re(再)+main(留)→ 留下 → 保持',
    'remove':'re(回)+move(动)→ 移走 → 移除',
    'replace':'re(再)+place(放)→ 重新放 → 替换',
    'restore':'re(再)+store(存)→ 恢复',
    'retain':'re(回)+tain(握)→ 握住 → 保留',
    'reveal':'re(回)+veal(面)→ 露面 → 揭示',
    'revise':'re(再)+vise(看)→ 再看 → 修订',
    'secure':'se(分)+cure(心)→ 安心的 → 安全的',
    'select':'se(分)+lect(选)→ 选出 → 选择',
    'signify':'sign(标记)+ify→ 意味着',
    'specify':'spec(看)+ify→ 指明',
    'stimulate':'sti(刺)+ulate→ 刺激',
    'submit':'sub(下)+mit(送)→ 送呈 → 提交',
    'suffice':'suf(下)+fice(做)→ 够做 → 足够',
    'sustain':'sus(下)+tain(握)→ 撑住 → 维持',
    'transfer':'trans(跨)+fer(带)→ 转移',
    'transmit':'trans(跨)+mit(送)→ 传播',
    'undertake':'under(下)+take(拿)→ 承担',
    'update':'up(上)+date(日期)→ 更新',
    'utilize':'util(用)+ize→ 利用',
    'verify':'ver(真)+ify→ 核实',
}

def generate_hook(term, df, em):
    if term in HOOK_MAP: return HOOK_MAP[term]
    return f'{em} {df} —— 多读多听，记住 {term}'

def generate_example(term, df):
    return f'跟读："{term}" 意思是「{df}」'

def build():
    out = []
    for row in RAW:
        if len(row) == 7:
            term, ph, lv, df, em, hook, ex = row
        elif len(row) == 5:
            term, ph, lv, df, em = row
            hook, ex = '', ''
        else:
            term, ph, lv, df = row
            em, hook, ex = None, '', ''
        if not hook: hook = generate_hook(term, df, em or emoji_of(term))
        if not ex: ex = generate_example(term, df)
        out.append({
            'term': term,
            'phonetic': ph,
            'level': lv,
            'def': df,
            'emoji': em if em else emoji_of(term),
            'hook': hook,
            'example': ex,
        })
    return out

def to_js(words):
    lines = []
    lines.append('// 英语趣学 H5 · 种子词库（MVP 演示，由 tools/gen_words.py 生成）')
    lines.append('// 字段: term 单词, phonetic 音标, level 级别, def 中文释义,')
    lines.append('//       emoji 联想图, hook 记忆口诀(趣味钩子，与正确拼写视觉分离), example 例句')
    lines.append('const WORD_BANK = [')
    for w in words:
        lines.append('  ' + json.dumps(w, ensure_ascii=False) + ',')
    lines.append('];')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    words = build()
    js = to_js(words)
    out_path = os.path.join(os.path.dirname(__file__), '..', 'js', 'words.js')
    out_path = os.path.abspath(out_path)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(js)
    # 统计分级
    from collections import Counter
    c = Counter(w['level'] for w in words)
    print(f'生成完成: {len(words)} 词 -> {out_path}')
    print('分级统计:', dict(c))
